// Curated Nifty 500-style universe — top constituents grouped by index bucket.
// Sourced from Nifty index factsheets (niftyindices.com). Static seed for the
// asset picker; live pricing flows through the existing Yahoo→Marketstack chain.

export type IndexBucket = "nifty50" | "next50" | "midcap150" | "smallcap250" | "nifty500";

export interface NiftyStock {
  symbol: string;        // NSE symbol (without suffix)
  name: string;
  sector: string;
  bucket: IndexBucket;
  // Optional seed fundamentals (Screener.in snapshot Jun 2026). Live price
  // feed overrides `cmp`; the rest power Deep Research models 18–22.
  cmp?: number;
  pe?: number;
  marCap?: number;       // ₹ crore
  divYld?: number;       // %
  roce?: number;         // %
  qtrProfitVar?: number; // %
  qtrSalesVar?: number;  // %
  debtEquity?: number;
}

// ~250 names — covers Nifty 50 (50), Next 50 (50), top of Midcap 150 (~80), top of Smallcap 250 (~70).
// Enough to feel "Nifty 500-like" without shipping a 200KB JSON.
export const NIFTY500: NiftyStock[] = [
  // ===== Nifty 50 =====
  { symbol: "RELIANCE", name: "Reliance Industries", sector: "Energy", bucket: "nifty50" },
  { symbol: "TCS", name: "Tata Consultancy Services", sector: "IT", bucket: "nifty50" },
  { symbol: "HDFCBANK", name: "HDFC Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecom", bucket: "nifty50" },
  { symbol: "ICICIBANK", name: "ICICI Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "INFY", name: "Infosys", sector: "IT", bucket: "nifty50" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking", bucket: "nifty50" },
  { symbol: "LICI", name: "Life Insurance Corporation of India", sector: "Insurance", bucket: "nifty50" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", sector: "FMCG", bucket: "nifty50" },
  { symbol: "ITC", name: "ITC", sector: "FMCG", bucket: "nifty50" },
  { symbol: "LT", name: "Larsen & Toubro", sector: "Capital Goods", bucket: "nifty50" },
  { symbol: "HCLTECH", name: "HCL Technologies", sector: "IT", bucket: "nifty50" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", sector: "NBFC", bucket: "nifty50" },
  { symbol: "MARUTI", name: "Maruti Suzuki India", sector: "Auto", bucket: "nifty50" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", sector: "Pharma", bucket: "nifty50" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "AXISBANK", name: "Axis Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "M&M", name: "Mahindra & Mahindra", sector: "Auto", bucket: "nifty50" },
  { symbol: "TITAN", name: "Titan Company", sector: "Consumer", bucket: "nifty50" },
  { symbol: "NTPC", name: "NTPC", sector: "Utilities", bucket: "nifty50" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", sector: "Cement", bucket: "nifty50" },
  { symbol: "ADANIENT", name: "Adani Enterprises", sector: "Conglomerate", bucket: "nifty50" },
  { symbol: "ASIANPAINT", name: "Asian Paints", sector: "Consumer", bucket: "nifty50" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", sector: "Utilities", bucket: "nifty50" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation", sector: "Energy", bucket: "nifty50" },
  { symbol: "WIPRO", name: "Wipro", sector: "IT", bucket: "nifty50" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", sector: "Financial", bucket: "nifty50" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", sector: "Infrastructure", bucket: "nifty50" },
  { symbol: "JSWSTEEL", name: "JSW Steel", sector: "Metals", bucket: "nifty50" },
  { symbol: "TATAMOTORS", name: "Tata Motors", sector: "Auto", bucket: "nifty50" },
  { symbol: "COALINDIA", name: "Coal India", sector: "Energy", bucket: "nifty50" },
  { symbol: "NESTLEIND", name: "Nestle India", sector: "FMCG", bucket: "nifty50" },
  { symbol: "TATASTEEL", name: "Tata Steel", sector: "Metals", bucket: "nifty50" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd", sector: "Banking", bucket: "nifty50", cmp: 950.0 },
  { symbol: "GRASIM", name: "Grasim Industries", sector: "Cement", bucket: "nifty50" },
  { symbol: "HINDALCO", name: "Hindalco Industries", sector: "Metals", bucket: "nifty50" },
  { symbol: "TECHM", name: "Tech Mahindra", sector: "IT", bucket: "nifty50" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories", sector: "Pharma", bucket: "nifty50" },
  { symbol: "CIPLA", name: "Cipla", sector: "Pharma", bucket: "nifty50" },
  { symbol: "EICHERMOT", name: "Eicher Motors", sector: "Auto", bucket: "nifty50" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", sector: "Auto", bucket: "nifty50" },
  { symbol: "BRITANNIA", name: "Britannia Industries", sector: "FMCG", bucket: "nifty50" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd", sector: "Auto", bucket: "nifty50", cmp: 5071.3, pe: 18.33, marCap: 101408.0, divYld: 3.26, roce: 30.34, qtrProfitVar: 22.49, qtrSalesVar: 21.71 },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd", sector: "FMCG", bucket: "nifty50", cmp: 1050.0 },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise", sector: "Healthcare", bucket: "nifty50" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance", sector: "NBFC", bucket: "nifty50" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", sector: "Insurance", bucket: "nifty50" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", sector: "Insurance", bucket: "nifty50" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd", sector: "Pharma", bucket: "nifty50", cmp: 6638.0, pe: 67.22, marCap: 176330.0, divYld: 0.45, roce: 21.96, qtrProfitVar: 13.44, qtrSalesVar: 9.52 },
  { symbol: "TRENT", name: "Trent Ltd", sector: "Retail", bucket: "nifty50", cmp: 6200.0 },

  // ===== Nifty Next 50 =====
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd", sector: "Renewables", bucket: "next50", cmp: 1485.7, pe: 133.72, marCap: 244788.0, divYld: 0.0, roce: 7.39, qtrProfitVar: 55.75, qtrSalesVar: 13.96 },
  { symbol: "ADANIPOWER", name: "Adani Power Ltd", sector: "Energy", bucket: "next50", cmp: 223.07, pe: 33.65, marCap: 429904.0, divYld: 0.0, roce: 17.22, qtrProfitVar: 52.34, qtrSalesVar: -0.1 },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd", sector: "Cement", bucket: "next50", cmp: 578.0 },
  { symbol: "ATGL", name: "Adani Total Gas", sector: "Utilities", bucket: "next50" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings & Investment", sector: "Financial", bucket: "next50" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking", bucket: "next50", cmp: 274.75, pe: 7.17, marCap: 142216.0, divYld: 3.09, roce: 5.63, qtrProfitVar: 7.03, qtrSalesVar: 5.16 },
  { symbol: "BEL", name: "Bharat Electronics Ltd", sector: "Defence", bucket: "next50", cmp: 295.0 },
  { symbol: "BERGEPAINT", name: "Berger Paints India Ltd", sector: "Consumer", bucket: "next50", cmp: 490.0 },
  { symbol: "BOSCHLTD", name: "Bosch", sector: "Auto", bucket: "next50" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking", bucket: "next50" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance", sector: "NBFC", bucket: "next50", cmp: 1568.1, pe: 25.58, marCap: 133835.0, divYld: 0.13, roce: 9.7, qtrProfitVar: 30.62, qtrSalesVar: 19.46 },
  { symbol: "DABUR", name: "Dabur India", sector: "FMCG", bucket: "next50" },
  { symbol: "DLF", name: "DLF Ltd", sector: "Realty", bucket: "next50", cmp: 587.05, pe: 34.31, marCap: 145248.0, divYld: 1.02, roce: 6.34, qtrProfitVar: -3.22, qtrSalesVar: -42.0 },
  { symbol: "DMART", name: "Avenue Supermarts Ltd", sector: "Retail", bucket: "next50", cmp: 3993.6, pe: 87.69, marCap: 260487.0, divYld: 0.0, roce: 17.19, qtrProfitVar: 19.18, qtrSalesVar: 18.91 },
  { symbol: "GAIL", name: "GAIL (India) Ltd", sector: "Energy", bucket: "next50", cmp: 198.0 },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Ltd", sector: "FMCG", bucket: "next50", cmp: 1230.0 },
  { symbol: "HAL", name: "Hindustan Aeronautics Ltd", sector: "Defence", bucket: "next50", cmp: 4192.3, pe: 30.76, marCap: 280424.0, divYld: 0.95, roce: 31.96, qtrProfitVar: 5.52, qtrSalesVar: 1.77 },
  { symbol: "HAVELLS", name: "Havells India Ltd", sector: "Capital Goods", bucket: "next50", cmp: 1750.0 },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", sector: "Insurance", bucket: "next50", cmp: 1779.0, pe: 31.96, marCap: 88595.0, divYld: 0.71, roce: 23.52, qtrProfitVar: 7.25, qtrSalesVar: 12.78 },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance", sector: "Insurance", bucket: "next50" },
  { symbol: "INDIGO", name: "InterGlobe Aviation (IndiGo)", sector: "Aviation", bucket: "next50" },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd", sector: "Energy", bucket: "next50", cmp: 140.94, pe: 4.72, marCap: 198861.0, divYld: 4.97, roce: 18.78, qtrProfitVar: 77.99, qtrSalesVar: 6.67 },
  { symbol: "IRCTC", name: "Indian Railway Catering & Tourism", sector: "Consumer", bucket: "next50", cmp: 820.0 },
  { symbol: "IRFC", name: "Indian Railway Finance Corp", sector: "NBFC", bucket: "next50", cmp: 175.0 },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", sector: "Metals", bucket: "next50" },
  { symbol: "JSWENERGY", name: "JSW Energy Ltd", sector: "Utilities", bucket: "next50", cmp: 580.9, pe: 44.11, marCap: 102098.0, divYld: 0.34, roce: 6.49, qtrProfitVar: 173.41, qtrSalesVar: 67.36 },
  { symbol: "LODHA", name: "Macrotech Developers Ltd", sector: "Realty", bucket: "next50", cmp: 1350.0 },
  { symbol: "LTIM", name: "LTIMindtree", sector: "IT", bucket: "next50" },
  { symbol: "MARICO", name: "Marico Ltd", sector: "FMCG", bucket: "next50", cmp: 778.4, pe: 58.96, marCap: 101060.0, divYld: 1.34, roce: 45.16, qtrProfitVar: 12.03, qtrSalesVar: 26.59 },
  { symbol: "NAUKRI", name: "Info Edge (India) Ltd", sector: "Technology", bucket: "next50", cmp: 8950.0 },
  { symbol: "PFC", name: "Power Finance Corporation Ltd", sector: "NBFC", bucket: "next50", cmp: 421.05, pe: 5.36, marCap: 138967.0, divYld: 3.75, roce: 9.71, qtrProfitVar: 10.81, qtrSalesVar: -1.18 },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd", sector: "Chemicals", bucket: "next50", cmp: 1535.5, pe: 63.55, marCap: 156279.0, divYld: 0.65, roce: 30.97, qtrProfitVar: 32.82, qtrSalesVar: 14.08 },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking", bucket: "next50" },
  { symbol: "RECLTD", name: "REC Ltd", sector: "NBFC", bucket: "next50", cmp: 440.0 },
  { symbol: "SBICARD", name: "SBI Cards & Payment Services", sector: "NBFC", bucket: "next50" },
  { symbol: "SIEMENS", name: "Siemens Ltd", sector: "Capital Goods", bucket: "next50", cmp: 3250.0 },
  { symbol: "TATAPOWER", name: "Tata Power Company", sector: "Utilities", bucket: "next50" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd", sector: "Pharma", bucket: "next50", cmp: 4571.2, pe: 70.63, marCap: 154784.0, divYld: 0.83, roce: 15.19, qtrProfitVar: -20.58, qtrSalesVar: 41.84 },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking", bucket: "next50" },
  { symbol: "VBL", name: "Varun Beverages Ltd", sector: "FMCG", bucket: "next50", cmp: 522.2, pe: 55.52, marCap: 176674.0, divYld: 0.29, roce: 19.71, qtrProfitVar: 20.08, qtrSalesVar: 18.09 },
  { symbol: "VEDL", name: "Vedanta", sector: "Metals", bucket: "next50" },
  { symbol: "ZOMATO", name: "Zomato Ltd (Eternal)", sector: "Consumer Tech", bucket: "next50", cmp: 250.0 },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Ltd", sector: "Pharma", bucket: "next50", cmp: 1052.0 },
  { symbol: "ABB", name: "ABB India Ltd", sector: "Capital Goods", bucket: "next50", cmp: 6770.5, pe: 94.13, marCap: 143387.0, divYld: 0.58, roce: 29.93, qtrProfitVar: -25.23, qtrSalesVar: 5.78 },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Ltd", sector: "Pharma", bucket: "next50", cmp: 1350.0 },
  { symbol: "COLPAL", name: "Colgate-Palmolive (India) Ltd", sector: "FMCG", bucket: "next50", cmp: 2850.0 },
  { symbol: "HDFCAMC", name: "HDFC Asset Management", sector: "Financial", bucket: "next50" },
  { symbol: "INDHOTEL", name: "Indian Hotels Company Ltd", sector: "Hospitality", bucket: "next50", cmp: 800.0 },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", sector: "NBFC", bucket: "next50" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Ltd", sector: "NBFC", bucket: "next50", cmp: 2250.0 },

  // ===== Midcap 150 (selected ~80) =====
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital Ltd", sector: "Financial", bucket: "midcap150", cmp: 338.3, pe: 24.99, marCap: 88678.0, divYld: 0.0, roce: 9.33, qtrProfitVar: 40.3, qtrSalesVar: 27.4 },
  { symbol: "ABFRL", name: "Aditya Birla Fashion & Retail", sector: "Retail", bucket: "midcap150" },
  { symbol: "ACC", name: "ACC", sector: "Cement", bucket: "midcap150" },
  { symbol: "ALKEM", name: "Alkem Laboratories Ltd", sector: "Pharma", bucket: "midcap150", cmp: 5700.0 },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Ltd", sector: "Metals", bucket: "midcap150", cmp: 1850.0 },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Ltd", sector: "Auto", bucket: "midcap150", cmp: 167.52, pe: 27.27, marCap: 98340.0, divYld: 1.87, roce: 14.26, qtrProfitVar: 34.52, qtrSalesVar: 23.63 },
  { symbol: "ASTRAL", name: "Astral Ltd", sector: "Building Matl.", bucket: "midcap150", cmp: 2100.0 },
  { symbol: "AUBANK", name: "AU Small Finance Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", sector: "Auto", bucket: "midcap150" },
  { symbol: "BHARATFORG", name: "Bharat Forge Ltd", sector: "Auto Ancillary", bucket: "midcap150", cmp: 1892.6, pe: 77.51, marCap: 90502.0, divYld: 0.45, roce: 12.18, qtrProfitVar: 40.77, qtrSalesVar: 24.96 },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd", sector: "Capital Goods", bucket: "midcap150", cmp: 355.0, pe: 151.78, marCap: 123588.0, divYld: 0.14, roce: 4.87, qtrProfitVar: 189.83, qtrSalesVar: 16.44 },
  { symbol: "BIOCON", name: "Biocon", sector: "Pharma", bucket: "midcap150" },
  { symbol: "BSE", name: "BSE Ltd", sector: "Financial", bucket: "midcap150", cmp: 3626.1, pe: 67.7, marCap: 147690.0, divYld: 0.17, roce: 46.57, qtrProfitVar: 175.79, qtrSalesVar: 61.97 },
  { symbol: "CGPOWER", name: "CG Power & Industrial Solutions", sector: "Capital Goods", bucket: "midcap150", cmp: 914.45, pe: 117.14, marCap: 144030.0, divYld: 0.14, roce: 27.01, qtrProfitVar: 33.67, qtrSalesVar: 25.03 },
  { symbol: "COFORGE", name: "Coforge Ltd", sector: "IT", bucket: "midcap150", cmp: 9500.0 },
  { symbol: "COROMANDEL", name: "Coromandel International", sector: "Chemicals", bucket: "midcap150" },
  { symbol: "CUMMINSIND", name: "Cummins India Ltd", sector: "Capital Goods", bucket: "midcap150", cmp: 5621.5, pe: 64.33, marCap: 155957.0, divYld: 1.17, roce: 39.5, qtrProfitVar: 18.0, qtrSalesVar: 21.89 },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Ltd", sector: "Chemicals", bucket: "midcap150", cmp: 2450.0 },
  { symbol: "DIXON", name: "Dixon Technologies India Ltd", sector: "Electronics", bucket: "midcap150", cmp: 16500.0 },
  { symbol: "ESCORTS", name: "Escorts Kubota", sector: "Auto", bucket: "midcap150" },
  { symbol: "EXIDEIND", name: "Exide Industries", sector: "Auto", bucket: "midcap150" },
  { symbol: "FEDERALBNK", name: "Federal Bank Ltd", sector: "Banking", bucket: "midcap150", cmp: 200.0 },
  { symbol: "GLAND", name: "Gland Pharma Ltd", sector: "Pharma", bucket: "midcap150", cmp: 1750.0 },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure", sector: "Infrastructure", bucket: "midcap150" },
  { symbol: "GODREJPROP", name: "Godrej Properties Ltd", sector: "Realty", bucket: "midcap150", cmp: 2800.0 },
  { symbol: "GUJGASLTD", name: "Gujarat Gas", sector: "Utilities", bucket: "midcap150" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation", sector: "Energy", bucket: "midcap150", cmp: 400.0 },
  { symbol: "IDEA", name: "Vodafone Idea Ltd", sector: "Telecom", bucket: "midcap150", cmp: 9.95, marCap: 107801.0, divYld: 0.0, roce: -1.93, qtrProfitVar: 3.72, qtrSalesVar: 1.85 },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd", sector: "Banking", bucket: "midcap150", cmp: 68.0 },
  { symbol: "IGL", name: "Indraprastha Gas", sector: "Utilities", bucket: "midcap150" },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Banking", bucket: "midcap150", cmp: 899.65, pe: 10.07, marCap: 121100.0, divYld: 1.8, roce: 6.38, qtrProfitVar: 8.15, qtrSalesVar: 8.45 },
  { symbol: "INDUSTOWER", name: "Indus Towers Ltd", sector: "Telecom", bucket: "midcap150", cmp: 413.95, pe: 15.29, marCap: 109030.0, divYld: 0.0, roce: 28.99, qtrProfitVar: -55.64, qtrSalesVar: 7.94 },
  { symbol: "IPCALAB", name: "IPCA Laboratories", sector: "Pharma", bucket: "midcap150" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks Ltd", sector: "Consumer", bucket: "midcap150", cmp: 720.0 },
  { symbol: "L&TFH", name: "L&T Finance Holdings", sector: "NBFC", bucket: "midcap150" },
  { symbol: "LAURUSLABS", name: "Laurus Labs", sector: "Pharma", bucket: "midcap150" },
  { symbol: "LUPIN", name: "Lupin Ltd", sector: "Pharma", bucket: "midcap150", cmp: 2302.1, pe: 21.16, marCap: 105258.0, divYld: 0.52, roce: 21.3, qtrProfitVar: 75.99, qtrSalesVar: 24.27 },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services", sector: "NBFC", bucket: "midcap150" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance", sector: "NBFC", bucket: "midcap150" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute Ltd", sector: "Healthcare", bucket: "midcap150", cmp: 1180.0 },
  { symbol: "MFSL", name: "Max Financial Services", sector: "Insurance", bucket: "midcap150" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson Intl.", sector: "Auto Ancillary", bucket: "midcap150", cmp: 143.4, pe: 36.62, marCap: 151339.0, divYld: 0.42, roce: 13.08, qtrProfitVar: 55.33, qtrSalesVar: 17.03 },
  { symbol: "MPHASIS", name: "Mphasis Ltd", sector: "IT", bucket: "midcap150", cmp: 3200.0 },
  { symbol: "MRF", name: "MRF", sector: "Auto", bucket: "midcap150" },
  { symbol: "NMDC", name: "NMDC", sector: "Metals", bucket: "midcap150" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", sector: "Realty", bucket: "midcap150" },
  { symbol: "OFSS", name: "Oracle Financial Services Software", sector: "IT", bucket: "midcap150", cmp: 9604.9, pe: 31.7, marCap: 83645.0, divYld: 2.76, roce: 45.28, qtrProfitVar: 30.72, qtrSalesVar: 20.33 },
  { symbol: "PAGEIND", name: "Page Industries", sector: "Consumer", bucket: "midcap150" },
  { symbol: "PERSISTENT", name: "Persistent Systems Ltd", sector: "IT", bucket: "midcap150", cmp: 6800.0 },
  { symbol: "PETRONET", name: "Petronet LNG Ltd", sector: "Energy", bucket: "midcap150", cmp: 320.0 },
  { symbol: "PIIND", name: "PI Industries Ltd", sector: "Agrochemicals", bucket: "midcap150", cmp: 4400.0 },
  { symbol: "POLYCAB", name: "Polycab India Ltd", sector: "Capital Goods", bucket: "midcap150", cmp: 8254.0, pe: 47.3, marCap: 124214.0, divYld: 0.42, roce: 29.72, qtrProfitVar: 35.87, qtrSalesVar: 46.12 },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects Ltd", sector: "Realty", bucket: "midcap150", cmp: 1800.0 },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd", sector: "Infrastructure", bucket: "midcap150", cmp: 410.0 },
  { symbol: "SAIL", name: "Steel Authority of India", sector: "Metals", bucket: "midcap150" },
  { symbol: "SHREECEM", name: "Shree Cement Ltd", sector: "Cement", bucket: "midcap150", cmp: 27800.0 },
  { symbol: "SOLARINDS", name: "Solar Industries India Ltd", sector: "Defence", bucket: "midcap150", cmp: 17143.0, pe: 92.44, marCap: 155075.0, divYld: 0.06, roce: 36.79, qtrProfitVar: 69.95, qtrSalesVar: 40.9 },
  { symbol: "SRF", name: "SRF Ltd", sector: "Chemicals", bucket: "midcap150", cmp: 2600.0 },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance Ltd", sector: "NBFC", bucket: "midcap150", cmp: 4800.0 },
  { symbol: "SUPREMEIND", name: "Supreme Industries Ltd", sector: "Chemicals", bucket: "midcap150", cmp: 4800.0 },
  { symbol: "SYNGENE", name: "Syngene International", sector: "Pharma", bucket: "midcap150" },
  { symbol: "TATAELXSI", name: "Tata Elxsi Ltd", sector: "IT", bucket: "midcap150", cmp: 6400.0 },
  { symbol: "TATATECH", name: "Tata Technologies Ltd", sector: "IT", bucket: "midcap150", cmp: 950.0 },
  { symbol: "TIINDIA", name: "Tube Investments of India", sector: "Auto", bucket: "midcap150" },
  { symbol: "TORNTPOWER", name: "Torrent Power Ltd", sector: "Utilities", bucket: "midcap150", cmp: 1690.0 },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd", sector: "Auto", bucket: "midcap150", cmp: 3312.8, pe: 51.61, marCap: 157401.0, divYld: 0.36, roce: 17.42, qtrProfitVar: 20.91, qtrSalesVar: 30.42 },
  { symbol: "UBL", name: "United Breweries", sector: "FMCG", bucket: "midcap150" },
  { symbol: "UPL", name: "UPL", sector: "Chemicals", bucket: "midcap150" },
  { symbol: "VOLTAS", name: "Voltas Ltd", sector: "Capital Goods", bucket: "midcap150", cmp: 1580.0 },
  { symbol: "YESBANK", name: "Yes Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises", sector: "Media", bucket: "midcap150" },
  { symbol: "JSWINFRA", name: "JSW Infrastructure Ltd", sector: "Infrastructure", bucket: "midcap150", cmp: 350.0 },
  { symbol: "KPITTECH", name: "KPIT Technologies Ltd", sector: "IT", bucket: "midcap150", cmp: 1500.0 },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders Ltd", sector: "Defence", bucket: "midcap150", cmp: 2190.0 },
  { symbol: "POLICYBZR", name: "PB Fintech Ltd", sector: "Fintech", bucket: "midcap150", cmp: 2100.0 },
  { symbol: "PAYTM", name: "One 97 Communications Ltd", sector: "Fintech", bucket: "midcap150", cmp: 900.0 },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures Ltd", sector: "Consumer Tech", bucket: "midcap150", cmp: 185.0 },
  { symbol: "HUDCO", name: "Housing & Urban Development Corp", sector: "NBFC", bucket: "midcap150" },
  { symbol: "IDBI", name: "IDBI Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "RBLBANK", name: "RBL Bank", sector: "Banking", bucket: "midcap150" },

  // ===== Smallcap 250 (selected ~70) =====
  { symbol: "AARTIIND", name: "Aarti Industries", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "AAVAS", name: "Aavas Financiers", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "ABBOTINDIA", name: "Abbott India", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "ACE", name: "Action Construction Equipment", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "AETHER", name: "Aether Industries", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "AFFLE", name: "Affle India", sector: "Internet", bucket: "smallcap250" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy & Mobility", sector: "Auto", bucket: "smallcap250" },
  { symbol: "ANGELONE", name: "Angel One Ltd", sector: "Financial", bucket: "smallcap250", cmp: 2800.0 },
  { symbol: "APARINDS", name: "Apar Industries", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "ASTERDM", name: "Aster DM Healthcare", sector: "Healthcare", bucket: "smallcap250" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "BATAINDIA", name: "Bata India", sector: "Retail", bucket: "smallcap250" },
  { symbol: "BAYERCROP", name: "Bayer CropScience", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "BIRLACORPN", name: "Birla Corporation", sector: "Cement", bucket: "smallcap250" },
  { symbol: "BLUEDART", name: "Blue Dart Express", sector: "Logistics", bucket: "smallcap250" },
  { symbol: "BLUESTARCO", name: "Blue Star", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "BSOFT", name: "BirlaSoft", sector: "IT", bucket: "smallcap250" },
  { symbol: "CAMPUS", name: "Campus Activewear", sector: "Retail", bucket: "smallcap250" },
  { symbol: "CANFINHOME", name: "Can Fin Homes", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "CASTROLIND", name: "Castrol India", sector: "Energy", bucket: "smallcap250" },
  { symbol: "CEATLTD", name: "CEAT", sector: "Auto", bucket: "smallcap250" },
  { symbol: "CENTRALBK", name: "Central Bank of India", sector: "Banking", bucket: "smallcap250" },
  { symbol: "CENTURYTEX", name: "Century Textiles & Industries", sector: "Realty", bucket: "smallcap250" },
  { symbol: "CESC", name: "CESC", sector: "Utilities", bucket: "smallcap250" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilizers", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "CHENNPETRO", name: "Chennai Petroleum Corporation", sector: "Energy", bucket: "smallcap250" },
  { symbol: "CRISIL", name: "CRISIL", sector: "Financial", bucket: "smallcap250" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Elec.", sector: "Consumer", bucket: "smallcap250", cmp: 420.0 },
  { symbol: "CUB", name: "City Union Bank", sector: "Banking", bucket: "smallcap250" },
  { symbol: "CYIENT", name: "Cyient", sector: "IT", bucket: "smallcap250" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilizers", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "DELHIVERY", name: "Delhivery Ltd", sector: "Logistics", bucket: "smallcap250", cmp: 390.0 },
  { symbol: "EIDPARRY", name: "EID Parry (India)", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "EIHOTEL", name: "EIH", sector: "Hospitality", bucket: "smallcap250" },
  { symbol: "EMAMILTD", name: "Emami", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "ENGINERSIN", name: "Engineers India", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank", sector: "Banking", bucket: "smallcap250" },
  { symbol: "FACT", name: "Fertilizers & Chemicals Travancore", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "FINCABLES", name: "Finolex Cables", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "FINPIPE", name: "Finolex Industries", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "FIVESTAR", name: "Five Star Business Finance", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "FSL", name: "Firstsource Solutions", sector: "IT", bucket: "smallcap250" },
  { symbol: "GAEL", name: "Gujarat Ambuja Exports", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "GICRE", name: "General Insurance Corporation", sector: "Insurance", bucket: "smallcap250" },
  { symbol: "GILLETTE", name: "Gillette India", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "GMDCLTD", name: "Gujarat Mineral Development", sector: "Metals", bucket: "smallcap250" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips India", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "GRANULES", name: "Granules India", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "GRINDWELL", name: "Grindwell Norton", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "GSPL", name: "Gujarat State Petronet", sector: "Energy", bucket: "smallcap250" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", sector: "IT", bucket: "smallcap250" },
  { symbol: "HATSUN", name: "Hatsun Agro Product", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "HEG", name: "HEG", sector: "Metals", bucket: "smallcap250" },
  { symbol: "HFCL", name: "HFCL", sector: "Telecom", bucket: "smallcap250" },
  { symbol: "HONAUT", name: "Honeywell Automation India", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "IDFC", name: "IDFC", sector: "Financial", bucket: "smallcap250" },
  { symbol: "IIFL", name: "IIFL Finance", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH", sector: "Internet", bucket: "smallcap250" },
  { symbol: "INDIANHUME", name: "Indian Hume Pipe", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "IOB", name: "Indian Overseas Bank", sector: "Banking", bucket: "smallcap250" },
  { symbol: "IRCON", name: "Ircon International Ltd", sector: "Infrastructure", bucket: "smallcap250", cmp: 220.0 },
  { symbol: "JBCHEPHARM", name: "JB Chemicals & Pharmaceuticals", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "JKCEMENT", name: "JK Cement Ltd", sector: "Cement", bucket: "smallcap250", cmp: 4800.0 },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India Ltd", sector: "Consumer", bucket: "smallcap250", cmp: 600.0 },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank", sector: "Banking", bucket: "smallcap250" },
  { symbol: "KEC", name: "KEC International", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "KFINTECH", name: "KFin Technologies Ltd", sector: "Financial", bucket: "smallcap250", cmp: 1100.0 },
  { symbol: "KIRLOSENG", name: "Kirloskar Oil Engines", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "KPRMILL", name: "KPR Mill", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs", sector: "Healthcare", bucket: "smallcap250" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics", sector: "IT", bucket: "smallcap250" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "LTTS", name: "L&T Technology Services Ltd", sector: "IT", bucket: "smallcap250", cmp: 5200.0 },
  { symbol: "NIACL", name: "NIACL", sector: "Other", bucket: "nifty500" },
  { symbol: "IFCI", name: "IFCI", sector: "Other", bucket: "nifty500" },
  { symbol: "TARIL", name: "TARIL", sector: "Other", bucket: "nifty500" },
  { symbol: "AMBER", name: "AMBER", sector: "Other", bucket: "nifty500" },
  { symbol: "NETWEB", name: "NETWEB", sector: "Other", bucket: "nifty500" },
  { symbol: "TEJASNET", name: "TEJASNET", sector: "Other", bucket: "nifty500" },
  { symbol: "HSCL", name: "HSCL", sector: "Other", bucket: "nifty500" },
  { symbol: "PINELABS", name: "PINELABS", sector: "Other", bucket: "nifty500" },
  { symbol: "SUZLON", name: "Suzlon Energy Ltd", sector: "Renewables", bucket: "nifty500", cmp: 58.0 },
  { symbol: "DATAPATTNS", name: "DATAPATTNS", sector: "Other", bucket: "nifty500" },
  { symbol: "MCX", name: "Multi Commodity Exchange of India", sector: "Financial", bucket: "nifty500", cmp: 6800.0 },
  { symbol: "REDINGTON", name: "REDINGTON", sector: "Other", bucket: "nifty500" },
  { symbol: "GROWW", name: "Billionbrains Garage Ventures", sector: "Fintech", bucket: "nifty500", cmp: 219.85, pe: 66.61, marCap: 138758.0, divYld: 0.0, roce: 37.32, qtrProfitVar: 122.06, qtrSalesVar: 87.93 },
  { symbol: "OLECTRA", name: "OLECTRA", sector: "Other", bucket: "nifty500" },
  { symbol: "MEESHO", name: "MEESHO", sector: "Other", bucket: "nifty500" },
  { symbol: "WAAREEENER", name: "Waaree Energies Ltd", sector: "Renewables", bucket: "nifty500", cmp: 3453.6, pe: 28.54, marCap: 99337.0, divYld: 0.06, roce: 34.94, qtrProfitVar: 158.06, qtrSalesVar: 118.81 },
  { symbol: "BDL", name: "BDL", sector: "Other", bucket: "nifty500" },
  { symbol: "JYOTICNC", name: "JYOTICNC", sector: "Other", bucket: "nifty500" },
  { symbol: "PIRAMALFIN", name: "PIRAMALFIN", sector: "Other", bucket: "nifty500" },
  { symbol: "CDSL", name: "Central Depository Services Ltd", sector: "Financial", bucket: "nifty500", cmp: 1900.0 },
  { symbol: "JBMA", name: "JBMA", sector: "Other", bucket: "nifty500" },
  { symbol: "OLAELEC", name: "OLAELEC", sector: "Other", bucket: "nifty500" },
  { symbol: "VAML", name: "VAML", sector: "Other", bucket: "nifty500" },
  { symbol: "ETERNAL", name: "ETERNAL", sector: "Other", bucket: "nifty500" },
  { symbol: "GRSE", name: "GRSE", sector: "Other", bucket: "nifty500" },
  { symbol: "TMPV", name: "TMPV", sector: "Other", bucket: "nifty500" },
  { symbol: "LTM", name: "LTM", sector: "Other", bucket: "nifty500" },
  { symbol: "ZENTEC", name: "ZENTEC", sector: "Other", bucket: "nifty500" },
  { symbol: "GVT&D", name: "GVT&D", sector: "Other", bucket: "nifty500" },
  { symbol: "VOGL", name: "VOGL", sector: "Other", bucket: "nifty500" },
  { symbol: "JIOFIN", name: "JIOFIN", sector: "Other", bucket: "nifty500" },
  { symbol: "CARBORUNIV", name: "CARBORUNIV", sector: "Other", bucket: "nifty500" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India Ltd", sector: "Capital Goods", bucket: "nifty500", cmp: 32805.0, pe: 165.79, marCap: 146233.0, divYld: 0.02, roce: 19.44, qtrProfitVar: 119.97, qtrSalesVar: 28.51 },
  { symbol: "RADICO", name: "RADICO", sector: "Other", bucket: "nifty500" },
  { symbol: "POONAWALLA", name: "POONAWALLA", sector: "Other", bucket: "nifty500" },
  { symbol: "NBCC", name: "NBCC", sector: "Other", bucket: "nifty500" },
  { symbol: "NLCINDIA", name: "NLCINDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "ICICIAMC", name: "ICICI Prudential AMC Ltd", sector: "Financial", bucket: "nifty500", cmp: 3299.8, pe: 49.44, marCap: 163050.0, divYld: 0.45, roce: 115.1, qtrProfitVar: 10.37, qtrSalesVar: 19.53 },
  { symbol: "KAYNES", name: "Kaynes Technology India Ltd", sector: "Electronics", bucket: "nifty500", cmp: 5200.0 },
  { symbol: "NATIONALUM", name: "NATIONALUM", sector: "Other", bucket: "nifty500" },
  { symbol: "LENSKART", name: "Lenskart Solutions Ltd", sector: "Consumer", bucket: "nifty500", cmp: 537.0, pe: 245.93, marCap: 93174.0, divYld: 0.0, roce: 5.57, qtrProfitVar: 7141.21, qtrSalesVar: 38.28 },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions Ltd", sector: "Utilities", bucket: "nifty500", cmp: 1489.6, pe: 79.83, marCap: 178967.0, divYld: 0.0, roce: 9.65, qtrProfitVar: 5.66, qtrSalesVar: 16.76 },
  { symbol: "PWL", name: "PWL", sector: "Other", bucket: "nifty500" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Ltd", sector: "Metals", bucket: "nifty500", cmp: 559.9, pe: 17.32, marCap: 236597.0, divYld: 1.96, roce: 69.25, qtrProfitVar: 67.91, qtrSalesVar: 49.19 },
  { symbol: "SCI", name: "SCI", sector: "Other", bucket: "nifty500" },
  { symbol: "SWIGGY", name: "SWIGGY", sector: "Other", bucket: "nifty500" },
  { symbol: "ATHERENERG", name: "ATHERENERG", sector: "Other", bucket: "nifty500" },
  { symbol: "TMCV", name: "Tata Motors DVR", sector: "Auto", bucket: "nifty500", cmp: 390.3, pe: 25.99, marCap: 143701.0, divYld: 1.02, qtrProfitVar: 34.91, qtrSalesVar: 19.37 },
  { symbol: "BPCL", name: "BPCL Ltd", sector: "Energy", bucket: "nifty500", cmp: 302.35, pe: 5.02, marCap: 131174.0, divYld: 5.79, roce: 25.69, qtrProfitVar: 26.07, qtrSalesVar: 6.72 },
  { symbol: "KEI", name: "KEI", sector: "Other", bucket: "nifty500" },
  { symbol: "THELEELA", name: "THELEELA", sector: "Other", bucket: "nifty500" },
  { symbol: "NAM-INDIA", name: "NAM-INDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "SAMMAANCAP", name: "SAMMAANCAP", sector: "Other", bucket: "nifty500" },
  { symbol: "COCHINSHIP", name: "COCHINSHIP", sector: "Other", bucket: "nifty500" },
  { symbol: "ENRIN", name: "ENRIN", sector: "Other", bucket: "nifty500" },
  { symbol: "HBLENGINE", name: "HBLENGINE", sector: "Other", bucket: "nifty500" },
  { symbol: "STARHEALTH", name: "Star Health & Allied Insurance", sector: "Insurance", bucket: "nifty500", cmp: 490.0 },
  { symbol: "INOXWIND", name: "INOXWIND", sector: "Other", bucket: "nifty500" },
  { symbol: "GABRIEL", name: "GABRIEL", sector: "Other", bucket: "nifty500" },
  { symbol: "ITCHOTELS", name: "ITCHOTELS", sector: "Other", bucket: "nifty500" },
  { symbol: "WOCKPHARMA", name: "WOCKPHARMA", sector: "Other", bucket: "nifty500" },
  { symbol: "CARTRADE", name: "CARTRADE", sector: "Other", bucket: "nifty500" },
  { symbol: "BANKINDIA", name: "BANKINDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "HINDCOPPER", name: "HINDCOPPER", sector: "Other", bucket: "nifty500" },
  { symbol: "360ONE", name: "360ONE", sector: "Other", bucket: "nifty500" },
  { symbol: "CRAFTSMAN", name: "CRAFTSMAN", sector: "Other", bucket: "nifty500" },
  { symbol: "FORCEMOT", name: "FORCEMOT", sector: "Other", bucket: "nifty500" },
  { symbol: "PGEL", name: "PGEL", sector: "Other", bucket: "nifty500" },
  { symbol: "PREMIERENE", name: "PREMIERENE", sector: "Other", bucket: "nifty500" },
  { symbol: "CPPLUS", name: "CPPLUS", sector: "Other", bucket: "nifty500" },
  { symbol: "LGEINDIA", name: "LG Electronics India Ltd", sector: "Consumer", bucket: "nifty500", cmp: 1608.7, pe: 53.05, marCap: 109136.0, divYld: 0.0, roce: 56.83, qtrProfitVar: -61.59, qtrSalesVar: -6.4 },
  { symbol: "AWL", name: "AWL", sector: "Other", bucket: "nifty500" },
  { symbol: "RRKABEL", name: "RRKABEL", sector: "Other", bucket: "nifty500" },
  { symbol: "GMRAIRPORT", name: "GMR Airports Infrastructure Ltd", sector: "Infrastructure", bucket: "nifty500", cmp: 97.86, marCap: 103254.0, divYld: 0.0, roce: 6.92, qtrProfitVar: 317.8, qtrSalesVar: 50.53 },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International", sector: "Chemicals", bucket: "nifty500", cmp: 3200.0 },
  { symbol: "TATACOMM", name: "Tata Communications Ltd", sector: "Telecom", bucket: "nifty500", cmp: 1780.0 },
  { symbol: "PARADEEP", name: "PARADEEP", sector: "Other", bucket: "nifty500" },
  { symbol: "TATACAP", name: "Tata Capital Ltd", sector: "Financial", bucket: "nifty500", cmp: 326.05, pe: 28.37, marCap: 138403.0, divYld: 0.0, roce: 8.58, qtrProfitVar: 42.82, qtrSalesVar: 9.12 },
  { symbol: "ANANDRATHI", name: "ANANDRATHI", sector: "Other", bucket: "nifty500" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings Ltd", sector: "Auto Ancillary", bucket: "nifty500", cmp: 580.0 },
  { symbol: "MAHABANK", name: "MAHABANK", sector: "Other", bucket: "nifty500" },
  { symbol: "GESHIP", name: "GESHIP", sector: "Other", bucket: "nifty500" },
  { symbol: "BAJAJHFL", name: "Bajaj Housing Finance Ltd", sector: "NBFC", bucket: "nifty500", cmp: 140.0 },
  { symbol: "ANTHEM", name: "ANTHEM", sector: "Other", bucket: "nifty500" },
  { symbol: "SYRMA", name: "SYRMA", sector: "Other", bucket: "nifty500" },
  { symbol: "MANKIND", name: "Mankind Pharma Ltd", sector: "Pharma", bucket: "nifty500", cmp: 2267.0, pe: 50.46, marCap: 93699.0, divYld: 0.04, roce: 15.98, qtrProfitVar: 29.05, qtrSalesVar: 11.52 },
  { symbol: "ITI", name: "ITI", sector: "Other", bucket: "nifty500" },
  { symbol: "PHOENIXLTD", name: "PHOENIXLTD", sector: "Other", bucket: "nifty500" },
  { symbol: "BEML", name: "BEML", sector: "Other", bucket: "nifty500" },
  { symbol: "FORTIS", name: "FORTIS", sector: "Other", bucket: "nifty500" },
  { symbol: "BELRISE", name: "BELRISE", sector: "Other", bucket: "nifty500" },
  { symbol: "ACUTAAS", name: "ACUTAAS", sector: "Other", bucket: "nifty500" },
  { symbol: "WELSPUNLIV", name: "WELSPUNLIV", sector: "Other", bucket: "nifty500" },
  { symbol: "NATCOPHARM", name: "Natco Pharma Ltd", sector: "Pharma", bucket: "nifty500", cmp: 1400.0 },
  { symbol: "CHOICEIN", name: "CHOICEIN", sector: "Other", bucket: "nifty500" },
  { symbol: "CAMS", name: "CAMS", sector: "Other", bucket: "nifty500" },
  { symbol: "TENNIND", name: "TENNIND", sector: "Other", bucket: "nifty500" },
  { symbol: "CGCL", name: "CGCL", sector: "Other", bucket: "nifty500" },
  { symbol: "MRPL", name: "MRPL", sector: "Other", bucket: "nifty500" },
  { symbol: "RPOWER", name: "RPOWER", sector: "Other", bucket: "nifty500" },
  { symbol: "PCBL", name: "PCBL", sector: "Other", bucket: "nifty500" },
  { symbol: "CAPLIPOINT", name: "CAPLIPOINT", sector: "Other", bucket: "nifty500" },
  { symbol: "AIAENG", name: "AIAENG", sector: "Other", bucket: "nifty500" },
  { symbol: "ANANTRAJ", name: "ANANTRAJ", sector: "Other", bucket: "nifty500" },
  { symbol: "UNITDSPR", name: "UNITDSPR", sector: "Other", bucket: "nifty500" },
  { symbol: "PPLPHARMA", name: "PPLPHARMA", sector: "Other", bucket: "nifty500" },
  { symbol: "OIL", name: "OIL", sector: "Other", bucket: "nifty500" },
  { symbol: "SONATSOFTW", name: "SONATSOFTW", sector: "Other", bucket: "nifty500" },
  { symbol: "AEGISLOG", name: "AEGISLOG", sector: "Other", bucket: "nifty500" },
  { symbol: "SAGILITY", name: "SAGILITY", sector: "Other", bucket: "nifty500" },
  { symbol: "JINDALSAW", name: "JINDALSAW", sector: "Other", bucket: "nifty500" },
  { symbol: "NIVABUPA", name: "NIVABUPA", sector: "Other", bucket: "nifty500" },
  { symbol: "SCHAEFFLER", name: "SCHAEFFLER", sector: "Other", bucket: "nifty500" },
  { symbol: "TITAGARH", name: "TITAGARH", sector: "Other", bucket: "nifty500" },
  { symbol: "CONCOR", name: "CONCOR", sector: "Other", bucket: "nifty500" },
  { symbol: "LTF", name: "LTF", sector: "Other", bucket: "nifty500" },
  { symbol: "JPPOWER", name: "JPPOWER", sector: "Other", bucket: "nifty500" },
  { symbol: "VMM", name: "VMM", sector: "Other", bucket: "nifty500" },
  { symbol: "HDBFS", name: "HDBFS", sector: "Other", bucket: "nifty500" },
  { symbol: "TRITURBINE", name: "TRITURBINE", sector: "Other", bucket: "nifty500" },
  { symbol: "CEMPRO", name: "CEMPRO", sector: "Other", bucket: "nifty500" },
  { symbol: "DOMS", name: "DOMS", sector: "Other", bucket: "nifty500" },
  { symbol: "EMMVEE", name: "EMMVEE", sector: "Other", bucket: "nifty500" },
  { symbol: "KPIL", name: "KPIL", sector: "Other", bucket: "nifty500" },
  { symbol: "SAILIFE", name: "SAILIFE", sector: "Other", bucket: "nifty500" },
  { symbol: "WELCORP", name: "WELCORP", sector: "Other", bucket: "nifty500" },
  { symbol: "NCC", name: "NCC", sector: "Other", bucket: "nifty500" },
  { symbol: "PATANJALI", name: "PATANJALI", sector: "Other", bucket: "nifty500" },
  { symbol: "LEMONTREE", name: "LEMONTREE", sector: "Other", bucket: "nifty500" },
  { symbol: "ABSLAMC", name: "ABSLAMC", sector: "Other", bucket: "nifty500" },
  { symbol: "NHPC", name: "NHPC Ltd", sector: "Utilities", bucket: "nifty500", cmp: 85.38, pe: 27.15, marCap: 85785.0, divYld: 2.24, roce: 7.42, qtrProfitVar: -5.24, qtrSalesVar: -2.89 },
  { symbol: "NEWGEN", name: "NEWGEN", sector: "Other", bucket: "nifty500" },
  { symbol: "MMTC", name: "MMTC", sector: "Other", bucket: "nifty500" },
  { symbol: "NTPCGREEN", name: "NTPCGREEN", sector: "Other", bucket: "nifty500" },
  { symbol: "JSWCEMENT", name: "JSWCEMENT", sector: "Other", bucket: "nifty500" },
  { symbol: "HYUNDAI", name: "Hyundai Motor India Ltd", sector: "Auto", bucket: "nifty500", cmp: 1990.1, pe: 29.78, marCap: 161732.0, divYld: 1.06, roce: 38.42, qtrProfitVar: -22.22, qtrSalesVar: 5.44 },
  { symbol: "DEVYANI", name: "DEVYANI", sector: "Other", bucket: "nifty500" },
  { symbol: "MOTILALOFS", name: "MOTILALOFS", sector: "Other", bucket: "nifty500" },
  { symbol: "ABREL", name: "ABREL", sector: "Other", bucket: "nifty500" },
  { symbol: "IREDA", name: "IREDA", sector: "Other", bucket: "nifty500" },
  { symbol: "SCHNEIDER", name: "SCHNEIDER", sector: "Other", bucket: "nifty500" },
  { symbol: "NEULANDLAB", name: "NEULANDLAB", sector: "Other", bucket: "nifty500" },
  { symbol: "PTCIL", name: "PTCIL", sector: "Other", bucket: "nifty500" },
  { symbol: "JKTYRE", name: "JKTYRE", sector: "Other", bucket: "nifty500" },
  { symbol: "UNOMINDA", name: "UNOMINDA", sector: "Other", bucket: "nifty500" },
  { symbol: "ACMESOLAR", name: "ACMESOLAR", sector: "Other", bucket: "nifty500" },
  { symbol: "GLAXO", name: "GLAXO", sector: "Other", bucket: "nifty500" },
  { symbol: "INTELLECT", name: "INTELLECT", sector: "Other", bucket: "nifty500" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management Ltd", sector: "Financial", bucket: "nifty500", cmp: 7200.0 },
  { symbol: "JAINREC", name: "JAINREC", sector: "Other", bucket: "nifty500" },
  { symbol: "VTL", name: "VTL", sector: "Other", bucket: "nifty500" },
  { symbol: "FLUOROCHEM", name: "FLUOROCHEM", sector: "Other", bucket: "nifty500" },
  { symbol: "LLOYDSME", name: "LLOYDSME", sector: "Other", bucket: "nifty500" },
  { symbol: "SAREGAMA", name: "SAREGAMA", sector: "Other", bucket: "nifty500" },
  { symbol: "JMFINANCIL", name: "JMFINANCIL", sector: "Other", bucket: "nifty500" },
  { symbol: "HEXT", name: "HEXT", sector: "Other", bucket: "nifty500" },
  { symbol: "J&KBANK", name: "J&KBANK", sector: "Other", bucket: "nifty500" },
  { symbol: "IKS", name: "IKS", sector: "Other", bucket: "nifty500" },
  { symbol: "ZFCVINDIA", name: "ZFCVINDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "GRAVITA", name: "GRAVITA", sector: "Other", bucket: "nifty500" },
  { symbol: "KIMS", name: "KIMS", sector: "Other", bucket: "nifty500" },
  { symbol: "BHARTIHEXA", name: "BHARTIHEXA", sector: "Other", bucket: "nifty500" },
  { symbol: "NH", name: "NH", sector: "Other", bucket: "nifty500" },
  { symbol: "HONASA", name: "HONASA", sector: "Other", bucket: "nifty500" },
  { symbol: "JSL", name: "JSL", sector: "Other", bucket: "nifty500" },
  { symbol: "SHYAMMETL", name: "SHYAMMETL", sector: "Other", bucket: "nifty500" },
  { symbol: "CONCORDBIO", name: "CONCORDBIO", sector: "Other", bucket: "nifty500" },
  { symbol: "ZENSARTECH", name: "ZENSARTECH", sector: "Other", bucket: "nifty500" },
  { symbol: "BLS", name: "BLS", sector: "Other", bucket: "nifty500" },
  { symbol: "GODREJIND", name: "GODREJIND", sector: "Other", bucket: "nifty500" },
  { symbol: "MSUMI", name: "MSUMI", sector: "Other", bucket: "nifty500" },
  { symbol: "UCOBANK", name: "UCOBANK", sector: "Other", bucket: "nifty500" },
  { symbol: "COHANCE", name: "COHANCE", sector: "Other", bucket: "nifty500" },
  { symbol: "AADHARHFC", name: "AADHARHFC", sector: "Other", bucket: "nifty500" },
  { symbol: "JUBLINGREA", name: "JUBLINGREA", sector: "Other", bucket: "nifty500" },
  { symbol: "ARE&M", name: "ARE&M", sector: "Other", bucket: "nifty500" },
  { symbol: "THERMAX", name: "THERMAX", sector: "Other", bucket: "nifty500" },
  { symbol: "GPIL", name: "GPIL", sector: "Other", bucket: "nifty500" },
  { symbol: "PNBHOUSING", name: "PNBHOUSING", sector: "Other", bucket: "nifty500" },
  { symbol: "BRIGADE", name: "Brigade Enterprises Ltd", sector: "Realty", bucket: "nifty500", cmp: 1350.0 },
  { symbol: "TATAINVEST", name: "TATAINVEST", sector: "Other", bucket: "nifty500" },
  { symbol: "AIIL", name: "AIIL", sector: "Other", bucket: "nifty500" },
  { symbol: "PVRINOX", name: "PVRINOX", sector: "Other", bucket: "nifty500" },
  { symbol: "IEX", name: "IEX", sector: "Other", bucket: "nifty500" },
  { symbol: "MGL", name: "MGL", sector: "Other", bucket: "nifty500" },
  { symbol: "TATACHEM", name: "TATACHEM", sector: "Other", bucket: "nifty500" },
  { symbol: "ECLERX", name: "ECLERX", sector: "Other", bucket: "nifty500" },
  { symbol: "ANURAS", name: "ANURAS", sector: "Other", bucket: "nifty500" },
  { symbol: "APOLLOTYRE", name: "APOLLOTYRE", sector: "Other", bucket: "nifty500" },
  { symbol: "TRIDENT", name: "TRIDENT", sector: "Other", bucket: "nifty500" },
  { symbol: "JWL", name: "JWL", sector: "Other", bucket: "nifty500" },
  { symbol: "TIMKEN", name: "TIMKEN", sector: "Other", bucket: "nifty500" },
  { symbol: "MEDANTA", name: "MEDANTA", sector: "Other", bucket: "nifty500" },
  { symbol: "ELECON", name: "ELECON", sector: "Other", bucket: "nifty500" },
  { symbol: "TECHNOE", name: "TECHNOE", sector: "Other", bucket: "nifty500" },
  { symbol: "IRB", name: "IRB", sector: "Other", bucket: "nifty500" },
  { symbol: "SAPPHIRE", name: "SAPPHIRE", sector: "Other", bucket: "nifty500" },
  { symbol: "VIJAYA", name: "VIJAYA", sector: "Other", bucket: "nifty500" },
  { symbol: "GRAPHITE", name: "GRAPHITE", sector: "Other", bucket: "nifty500" },
  { symbol: "RAILTEL", name: "RAILTEL", sector: "Other", bucket: "nifty500" },
  { symbol: "URBANCO", name: "URBANCO", sector: "Other", bucket: "nifty500" },
  { symbol: "HOMEFIRST", name: "HOMEFIRST", sector: "Other", bucket: "nifty500" },
  { symbol: "CCL", name: "CCL", sector: "Other", bucket: "nifty500" },
  { symbol: "SIGNATURE", name: "SIGNATURE", sector: "Other", bucket: "nifty500" },
  { symbol: "AFCONS", name: "AFCONS", sector: "Other", bucket: "nifty500" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Ltd", sector: "Cement", bucket: "nifty500", cmp: 1980.0 },
  { symbol: "SPLPETRO", name: "SPLPETRO", sector: "Other", bucket: "nifty500" },
  { symbol: "NSLNISP", name: "NSLNISP", sector: "Other", bucket: "nifty500" },
  { symbol: "LTFOODS", name: "LTFOODS", sector: "Other", bucket: "nifty500" },
  { symbol: "BLUEJET", name: "BLUEJET", sector: "Other", bucket: "nifty500" },
  { symbol: "POLYMED", name: "POLYMED", sector: "Other", bucket: "nifty500" },
  { symbol: "EMCURE", name: "EMCURE", sector: "Other", bucket: "nifty500" },
  { symbol: "TBOTEK", name: "TBOTEK", sector: "Other", bucket: "nifty500" },
  { symbol: "APTUS", name: "APTUS", sector: "Other", bucket: "nifty500" },
  { symbol: "FIRSTCRY", name: "FIRSTCRY", sector: "Other", bucket: "nifty500" },
  { symbol: "AEGISVOPAK", name: "AEGISVOPAK", sector: "Other", bucket: "nifty500" },
  { symbol: "ONESOURCE", name: "ONESOURCE", sector: "Other", bucket: "nifty500" },
  { symbol: "MAPMYINDIA", name: "MAPMYINDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "SWANCORP", name: "SWANCORP", sector: "Other", bucket: "nifty500" },
  { symbol: "TEGA", name: "TEGA", sector: "Other", bucket: "nifty500" },
  { symbol: "RAINBOW", name: "RAINBOW", sector: "Other", bucket: "nifty500" },
  { symbol: "SBFC", name: "SBFC", sector: "Other", bucket: "nifty500" },
  { symbol: "USHAMART", name: "USHAMART", sector: "Other", bucket: "nifty500" },
  { symbol: "MINDACORP", name: "MINDACORP", sector: "Other", bucket: "nifty500" },
  { symbol: "CHALET", name: "CHALET", sector: "Other", bucket: "nifty500" },
  { symbol: "UTIAMC", name: "UTIAMC", sector: "Other", bucket: "nifty500" },
  { symbol: "ELGIEQUIP", name: "ELGIEQUIP", sector: "Other", bucket: "nifty500" },
  { symbol: "RKFORGE", name: "RKFORGE", sector: "Other", bucket: "nifty500" },
  { symbol: "ABDL", name: "ABDL", sector: "Other", bucket: "nifty500" },
  { symbol: "ENDURANCE", name: "ENDURANCE", sector: "Other", bucket: "nifty500" },
  { symbol: "SJVN", name: "SJVN", sector: "Other", bucket: "nifty500" },
  { symbol: "SARDAEN", name: "SARDAEN", sector: "Other", bucket: "nifty500" },
  { symbol: "NAVA", name: "NAVA", sector: "Other", bucket: "nifty500" },
  { symbol: "TTML", name: "TTML", sector: "Other", bucket: "nifty500" },
  { symbol: "GALLANTT", name: "GALLANTT", sector: "Other", bucket: "nifty500" },
  { symbol: "CHOLAHLDNG", name: "CHOLAHLDNG", sector: "Other", bucket: "nifty500" },
  { symbol: "INDGN", name: "INDGN", sector: "Other", bucket: "nifty500" },
  { symbol: "LINDEINDIA", name: "LINDEINDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "ATUL", name: "ATUL", sector: "Other", bucket: "nifty500" },
  { symbol: "CIEINDIA", name: "CIEINDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "ASAHIINDIA", name: "ASAHIINDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "SOBHA", name: "Sobha Ltd", sector: "Realty", bucket: "nifty500", cmp: 1800.0 },
  { symbol: "GODIGIT", name: "GODIGIT", sector: "Other", bucket: "nifty500" },
  { symbol: "SUNTV", name: "SUNTV", sector: "Other", bucket: "nifty500" },
  { symbol: "ERIS", name: "ERIS", sector: "Other", bucket: "nifty500" },
  { symbol: "RITES", name: "RITES", sector: "Other", bucket: "nifty500" },
  { symbol: "CREDITACC", name: "CREDITACC", sector: "Other", bucket: "nifty500" },
  { symbol: "CLEAN", name: "CLEAN", sector: "Other", bucket: "nifty500" },
  { symbol: "IGIL", name: "IGIL", sector: "Other", bucket: "nifty500" },
  { symbol: "WHIRLPOOL", name: "WHIRLPOOL", sector: "Other", bucket: "nifty500" },
  { symbol: "INDIACEM", name: "INDIACEM", sector: "Other", bucket: "nifty500" },
  { symbol: "ABLBL", name: "ABLBL", sector: "Other", bucket: "nifty500" },
  { symbol: "ZYDUSWELL", name: "ZYDUSWELL", sector: "Other", bucket: "nifty500" },
  { symbol: "PFIZER", name: "PFIZER", sector: "Other", bucket: "nifty500" },
  { symbol: "JUBLPHARMA", name: "JUBLPHARMA", sector: "Other", bucket: "nifty500" },
  { symbol: "3MINDIA", name: "3MINDIA", sector: "Other", bucket: "nifty500" },
  { symbol: "BIKAJI", name: "BIKAJI", sector: "Other", bucket: "nifty500" },
  { symbol: "NUVOCO", name: "NUVOCO", sector: "Other", bucket: "nifty500" },
  { symbol: "TRAVELFOOD", name: "TRAVELFOOD", sector: "Other", bucket: "nifty500" },
  { symbol: "SUMICHEM", name: "SUMICHEM", sector: "Other", bucket: "nifty500" },
  { symbol: "BBTC", name: "BBTC", sector: "Other", bucket: "nifty500" },
  { symbol: "RAMCOCEM", name: "Ramco Cements Ltd", sector: "Cement", bucket: "nifty500", cmp: 950.0 },
  { symbol: "JSWDULUX", name: "JSWDULUX", sector: "Other", bucket: "nifty500" },
  { symbol: "DCMSHRIRAM", name: "DCMSHRIRAM", sector: "Other", bucket: "nifty500" },
  { symbol: "RHIM", name: "RHIM", sector: "Other", bucket: "nifty500" },
  { symbol: "CANHLIFE", name: "CANHLIFE", sector: "Other", bucket: "nifty500" },

  // ===== Added Jun 2026 (Screener.in seed fundamentals) =====
  { symbol: "GVTD", name: "GE Vernova T&D India Ltd", sector: "Capital Goods", bucket: "midcap150", cmp: 4549.0, pe: 104.42, marCap: 116692.0, divYld: 0.11, roce: 54.74, qtrProfitVar: 138.53, qtrSalesVar: 58.4 },
  { symbol: "LAURUS", name: "Laurus Labs Ltd", sector: "Pharma", bucket: "midcap150", cmp: 560.0 },
  { symbol: "SBICARDS", name: "SBI Cards & Payment Services", sector: "Financial", bucket: "midcap150", cmp: 750.0 },
  { symbol: "PNCINFRA", name: "PNC Infratech Ltd", sector: "Infrastructure", bucket: "midcap150", cmp: 430.0 },
  { symbol: "TANLA", name: "Tanla Platforms Ltd", sector: "IT", bucket: "smallcap250", cmp: 920.0 },
  { symbol: "NUCLEUS", name: "Nucleus Software Exports Ltd", sector: "IT", bucket: "smallcap250", cmp: 1500.0 },
  { symbol: "MASTEK", name: "Mastek Ltd", sector: "IT", bucket: "smallcap250", cmp: 2800.0 },
  { symbol: "ZENSAR", name: "Zensar Technologies Ltd", sector: "IT", bucket: "smallcap250", cmp: 720.0 },
  { symbol: "ROUTE", name: "Route Mobile Ltd", sector: "IT", bucket: "smallcap250", cmp: 1400.0 },
  { symbol: "MSTROE", name: "Rategain Travel Technologies", sector: "IT", bucket: "smallcap250", cmp: 420.0 },
  { symbol: "BIRLASOFT", name: "Birlasoft Ltd", sector: "IT", bucket: "smallcap250", cmp: 620.0 },
  { symbol: "SOLARA", name: "Solara Active Pharma Sciences", sector: "Pharma", bucket: "smallcap250", cmp: 550.0 },
  { symbol: "SUVEN", name: "Suven Pharmaceuticals Ltd", sector: "Pharma", bucket: "smallcap250", cmp: 1250.0 },
  { symbol: "KRSNAA", name: "Krsnaa Diagnostics Ltd", sector: "Healthcare", bucket: "smallcap250", cmp: 620.0 },
  { symbol: "ASTER", name: "Aster DM Healthcare Ltd", sector: "Healthcare", bucket: "smallcap250", cmp: 450.0 },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Ltd", sector: "Healthcare", bucket: "smallcap250", cmp: 1850.0 },
  { symbol: "FINEORG", name: "Fine Organic Industries Ltd", sector: "Chemicals", bucket: "smallcap250", cmp: 5000.0 },
  { symbol: "AARTI", name: "Aarti Industries Ltd", sector: "Chemicals", bucket: "smallcap250", cmp: 550.0 },
  { symbol: "NACLIND", name: "NACL Industries Ltd", sector: "Agrochemicals", bucket: "smallcap250", cmp: 168.0 },
  { symbol: "SUPRAJIT", name: "Suprajit Engineering Ltd", sector: "Auto Ancillary", bucket: "smallcap250", cmp: 490.0 },
  { symbol: "SUNDRMFAST", name: "Sundram Fasteners Ltd", sector: "Auto Ancillary", bucket: "smallcap250", cmp: 1350.0 },
  { symbol: "SUBROS", name: "Subros Ltd", sector: "Auto Ancillary", bucket: "smallcap250", cmp: 650.0 },
  { symbol: "ATHER", name: "Ather Energy Ltd", sector: "Auto", bucket: "smallcap250", cmp: 380.0 },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank", sector: "Banking", bucket: "smallcap250", cmp: 48.0 },
  { symbol: "SURYODAY", name: "Suryoday Small Finance Bank", sector: "Banking", bucket: "smallcap250", cmp: 160.0 },
  { symbol: "KARURVSYA", name: "Karur Vysya Bank Ltd", sector: "Banking", bucket: "smallcap250", cmp: 230.0 },
  { symbol: "DCBBANK", name: "DCB Bank Ltd", sector: "Banking", bucket: "smallcap250", cmp: 140.0 },
  { symbol: "5PAISA", name: "5Paisa Capital Ltd", sector: "Financial", bucket: "smallcap250", cmp: 430.0 },
  { symbol: "PIRAMALFINANCE", name: "Piramal Finance Ltd", sector: "NBFC", bucket: "smallcap250", cmp: 350.0 },
  { symbol: "KOLTEPATIL", name: "Kolte-Patil Developers Ltd", sector: "Realty", bucket: "smallcap250", cmp: 450.0 },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace Developers", sector: "Realty", bucket: "smallcap250", cmp: 500.0 },
  { symbol: "ARVSMART", name: "Arvind SmartSpaces Ltd", sector: "Realty", bucket: "smallcap250", cmp: 620.0 },
  { symbol: "KNR", name: "KNR Constructions Ltd", sector: "Infrastructure", bucket: "smallcap250", cmp: 380.0 },
  { symbol: "HGINFRA", name: "H.G. Infra Engineering Ltd", sector: "Infrastructure", bucket: "smallcap250", cmp: 1250.0 },
  { symbol: "AHLUCONT", name: "Ahluwalia Contracts India Ltd", sector: "Infrastructure", bucket: "smallcap250", cmp: 820.0 },
  { symbol: "VSTIND", name: "VST Industries Ltd", sector: "FMCG", bucket: "smallcap250", cmp: 3500.0 },
  { symbol: "PRATAAP", name: "Prataap Snacks Ltd", sector: "FMCG", bucket: "smallcap250", cmp: 1350.0 },
  { symbol: "WESTLIFE", name: "Westlife Foodworld Ltd", sector: "Consumer", bucket: "smallcap250", cmp: 860.0 },
  { symbol: "BARBEQUE", name: "Barbeque Nation Hospitality", sector: "Consumer", bucket: "smallcap250", cmp: 580.0 },
  { symbol: "PARAS", name: "Paras Defence & Space Technologies", sector: "Defence", bucket: "smallcap250", cmp: 1200.0 },
  { symbol: "IDEAFORGE", name: "ideaForge Technology Ltd", sector: "Defence", bucket: "smallcap250", cmp: 650.0 },
  { symbol: "RATNAMANI", name: "Ratnamani Metals & Tubes Ltd", sector: "Metals", bucket: "smallcap250", cmp: 3700.0 },
  { symbol: "MOIL", name: "MOIL Ltd", sector: "Metals", bucket: "smallcap250", cmp: 395.0 },
  { symbol: "INDIGRID", name: "IndiGrid InvIT Fund", sector: "Utilities", bucket: "smallcap250", cmp: 180.0 },
  { symbol: "EIH", name: "EIH Ltd (Oberoi Hotels)", sector: "Hospitality", bucket: "smallcap250", cmp: 380.0 },
  { symbol: "RUPA", name: "Rupa & Company Ltd", sector: "Textiles", bucket: "smallcap250", cmp: 340.0 },
  { symbol: "ARVIND", name: "Arvind Ltd", sector: "Textiles", bucket: "smallcap250", cmp: 280.0 },
  { symbol: "TRIVENI", name: "Triveni Engineering & Industries", sector: "Sugar", bucket: "smallcap250", cmp: 480.0 },
  { symbol: "DWARIKESH", name: "Dwarikesh Sugar Industries Ltd", sector: "Sugar", bucket: "smallcap250", cmp: 98.0 },
  { symbol: "SENCO", name: "Senco Gold Ltd", sector: "Consumer", bucket: "smallcap250", cmp: 1100.0 },
  { symbol: "RAJESHEXPO", name: "Rajesh Exports Ltd", sector: "Consumer", bucket: "smallcap250", cmp: 390.0 },

  // ===== Added from Screener.in verified seed (12 Jul 2026) =====
];

export const BUCKET_LABEL: Record<IndexBucket, string> = {
  nifty50: "Nifty 50",
  next50: "Nifty Next 50",
  midcap150: "Nifty Midcap 150",
  smallcap250: "Nifty Smallcap 250",
  nifty500: "Nifty 500 (extended)",
};

export function searchStocks(query: string, limit = 50): NiftyStock[] {
  const q = query.trim().toLowerCase();
  if (!q) return NIFTY500.slice(0, limit);
  return NIFTY500.filter(
    (s) =>
      s.symbol.toLowerCase().includes(q) ||
      s.name.toLowerCase().includes(q) ||
      s.sector.toLowerCase().includes(q)
  ).slice(0, limit);
}

export function getStockBySymbol(symbol: string): NiftyStock | undefined {
  return NIFTY500.find((s) => s.symbol.toUpperCase() === symbol.toUpperCase());
}
