// Curated Nifty 500-style universe — top constituents grouped by index bucket.
// Sourced from Nifty index factsheets (niftyindices.com). Static seed for the
// asset picker; live pricing flows through the existing Yahoo→Marketstack chain.

export type IndexBucket = "nifty50" | "next50" | "midcap150" | "smallcap250";

export interface NiftyStock {
  symbol: string;        // NSE symbol (without suffix)
  name: string;
  sector: string;
  bucket: IndexBucket;
}

// ~250 names — covers Nifty 50 (50), Next 50 (50), top of Midcap 150 (~80), top of Smallcap 250 (~70).
// Enough to feel "Nifty 500-like" without shipping a 200KB JSON.
export const NIFTY500: NiftyStock[] = [
  // ===== Nifty 50 =====
  { symbol: "RELIANCE", name: "Reliance Industries", sector: "Energy", bucket: "nifty50" },
  { symbol: "TCS", name: "Tata Consultancy Services", sector: "IT", bucket: "nifty50" },
  { symbol: "HDFCBANK", name: "HDFC Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecom", bucket: "nifty50" },
  { symbol: "ICICIBANK", name: "ICICI Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "INFY", name: "Infosys", sector: "IT", bucket: "nifty50" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking", bucket: "nifty50" },
  { symbol: "LICI", name: "Life Insurance Corporation of India", sector: "Insurance", bucket: "nifty50" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", sector: "FMCG", bucket: "nifty50" },
  { symbol: "ITC", name: "ITC", sector: "FMCG", bucket: "nifty50" },
  { symbol: "LT", name: "Larsen & Toubro", sector: "Capital Goods", bucket: "nifty50" },
  { symbol: "HCLTECH", name: "HCL Technologies", sector: "IT", bucket: "nifty50" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", sector: "NBFC", bucket: "nifty50" },
  { symbol: "MARUTI", name: "Maruti Suzuki India", sector: "Auto", bucket: "nifty50" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", sector: "Pharma", bucket: "nifty50" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "AXISBANK", name: "Axis Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "M&M", name: "Mahindra & Mahindra", sector: "Auto", bucket: "nifty50" },
  { symbol: "TITAN", name: "Titan Company", sector: "Consumer", bucket: "nifty50" },
  { symbol: "NTPC", name: "NTPC", sector: "Utilities", bucket: "nifty50" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", sector: "Cement", bucket: "nifty50" },
  { symbol: "ADANIENT", name: "Adani Enterprises", sector: "Conglomerate", bucket: "nifty50" },
  { symbol: "ASIANPAINT", name: "Asian Paints", sector: "Consumer", bucket: "nifty50" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", sector: "Utilities", bucket: "nifty50" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation", sector: "Energy", bucket: "nifty50" },
  { symbol: "WIPRO", name: "Wipro", sector: "IT", bucket: "nifty50" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", sector: "Financial", bucket: "nifty50" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", sector: "Infrastructure", bucket: "nifty50" },
  { symbol: "JSWSTEEL", name: "JSW Steel", sector: "Metals", bucket: "nifty50" },
  { symbol: "TATAMOTORS", name: "Tata Motors", sector: "Auto", bucket: "nifty50" },
  { symbol: "COALINDIA", name: "Coal India", sector: "Energy", bucket: "nifty50" },
  { symbol: "NESTLEIND", name: "Nestle India", sector: "FMCG", bucket: "nifty50" },
  { symbol: "TATASTEEL", name: "Tata Steel", sector: "Metals", bucket: "nifty50" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", sector: "Banking", bucket: "nifty50" },
  { symbol: "GRASIM", name: "Grasim Industries", sector: "Cement", bucket: "nifty50" },
  { symbol: "HINDALCO", name: "Hindalco Industries", sector: "Metals", bucket: "nifty50" },
  { symbol: "TECHM", name: "Tech Mahindra", sector: "IT", bucket: "nifty50" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories", sector: "Pharma", bucket: "nifty50" },
  { symbol: "CIPLA", name: "Cipla", sector: "Pharma", bucket: "nifty50" },
  { symbol: "EICHERMOT", name: "Eicher Motors", sector: "Auto", bucket: "nifty50" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", sector: "Auto", bucket: "nifty50" },
  { symbol: "BRITANNIA", name: "Britannia Industries", sector: "FMCG", bucket: "nifty50" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", sector: "Auto", bucket: "nifty50" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", sector: "FMCG", bucket: "nifty50" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise", sector: "Healthcare", bucket: "nifty50" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance", sector: "NBFC", bucket: "nifty50" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", sector: "Insurance", bucket: "nifty50" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", sector: "Insurance", bucket: "nifty50" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories", sector: "Pharma", bucket: "nifty50" },
  { symbol: "TRENT", name: "Trent", sector: "Retail", bucket: "nifty50" },

  // ===== Nifty Next 50 =====
  { symbol: "ADANIGREEN", name: "Adani Green Energy", sector: "Utilities", bucket: "next50" },
  { symbol: "ADANIPOWER", name: "Adani Power", sector: "Utilities", bucket: "next50" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", sector: "Cement", bucket: "next50" },
  { symbol: "ATGL", name: "Adani Total Gas", sector: "Utilities", bucket: "next50" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings & Investment", sector: "Financial", bucket: "next50" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking", bucket: "next50" },
  { symbol: "BEL", name: "Bharat Electronics", sector: "Defence", bucket: "next50" },
  { symbol: "BERGEPAINT", name: "Berger Paints India", sector: "Consumer", bucket: "next50" },
  { symbol: "BOSCHLTD", name: "Bosch", sector: "Auto", bucket: "next50" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking", bucket: "next50" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance", sector: "NBFC", bucket: "next50" },
  { symbol: "DABUR", name: "Dabur India", sector: "FMCG", bucket: "next50" },
  { symbol: "DLF", name: "DLF", sector: "Realty", bucket: "next50" },
  { symbol: "DMART", name: "Avenue Supermarts (DMart)", sector: "Retail", bucket: "next50" },
  { symbol: "GAIL", name: "GAIL India", sector: "Energy", bucket: "next50" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", sector: "FMCG", bucket: "next50" },
  { symbol: "HAL", name: "Hindustan Aeronautics", sector: "Defence", bucket: "next50" },
  { symbol: "HAVELLS", name: "Havells India", sector: "Consumer", bucket: "next50" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", sector: "Insurance", bucket: "next50" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance", sector: "Insurance", bucket: "next50" },
  { symbol: "INDIGO", name: "InterGlobe Aviation (IndiGo)", sector: "Aviation", bucket: "next50" },
  { symbol: "IOC", name: "Indian Oil Corporation", sector: "Energy", bucket: "next50" },
  { symbol: "IRCTC", name: "Indian Railway Catering & Tourism", sector: "Services", bucket: "next50" },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation", sector: "NBFC", bucket: "next50" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", sector: "Metals", bucket: "next50" },
  { symbol: "JSWENERGY", name: "JSW Energy", sector: "Utilities", bucket: "next50" },
  { symbol: "LODHA", name: "Macrotech Developers (Lodha)", sector: "Realty", bucket: "next50" },
  { symbol: "LTIM", name: "LTIMindtree", sector: "IT", bucket: "next50" },
  { symbol: "MARICO", name: "Marico", sector: "FMCG", bucket: "next50" },
  { symbol: "NAUKRI", name: "Info Edge (India)", sector: "Internet", bucket: "next50" },
  { symbol: "PFC", name: "Power Finance Corporation", sector: "NBFC", bucket: "next50" },
  { symbol: "PIDILITIND", name: "Pidilite Industries", sector: "Consumer", bucket: "next50" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking", bucket: "next50" },
  { symbol: "RECLTD", name: "REC", sector: "NBFC", bucket: "next50" },
  { symbol: "SBICARD", name: "SBI Cards & Payment Services", sector: "NBFC", bucket: "next50" },
  { symbol: "SIEMENS", name: "Siemens", sector: "Capital Goods", bucket: "next50" },
  { symbol: "TATAPOWER", name: "Tata Power Company", sector: "Utilities", bucket: "next50" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals", sector: "Pharma", bucket: "next50" },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking", bucket: "next50" },
  { symbol: "VBL", name: "Varun Beverages", sector: "FMCG", bucket: "next50" },
  { symbol: "VEDL", name: "Vedanta", sector: "Metals", bucket: "next50" },
  { symbol: "ZOMATO", name: "Zomato", sector: "Internet", bucket: "next50" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences", sector: "Pharma", bucket: "next50" },
  { symbol: "ABB", name: "ABB India", sector: "Capital Goods", bucket: "next50" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", sector: "Pharma", bucket: "next50" },
  { symbol: "COLPAL", name: "Colgate Palmolive (India)", sector: "FMCG", bucket: "next50" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management", sector: "Financial", bucket: "next50" },
  { symbol: "INDHOTEL", name: "The Indian Hotels Company", sector: "Hospitality", bucket: "next50" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", sector: "NBFC", bucket: "next50" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", sector: "NBFC", bucket: "next50" },

  // ===== Midcap 150 (selected ~80) =====
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital", sector: "Financial", bucket: "midcap150" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion & Retail", sector: "Retail", bucket: "midcap150" },
  { symbol: "ACC", name: "ACC", sector: "Cement", bucket: "midcap150" },
  { symbol: "ALKEM", name: "Alkem Laboratories", sector: "Pharma", bucket: "midcap150" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes", sector: "Metals", bucket: "midcap150" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland", sector: "Auto", bucket: "midcap150" },
  { symbol: "ASTRAL", name: "Astral", sector: "Consumer", bucket: "midcap150" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", sector: "Auto", bucket: "midcap150" },
  { symbol: "BHARATFORG", name: "Bharat Forge", sector: "Auto", bucket: "midcap150" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals", sector: "Capital Goods", bucket: "midcap150" },
  { symbol: "BIOCON", name: "Biocon", sector: "Pharma", bucket: "midcap150" },
  { symbol: "BSE", name: "BSE", sector: "Financial", bucket: "midcap150" },
  { symbol: "CGPOWER", name: "CG Power & Industrial Solutions", sector: "Capital Goods", bucket: "midcap150" },
  { symbol: "COFORGE", name: "Coforge", sector: "IT", bucket: "midcap150" },
  { symbol: "COROMANDEL", name: "Coromandel International", sector: "Chemicals", bucket: "midcap150" },
  { symbol: "CUMMINSIND", name: "Cummins India", sector: "Capital Goods", bucket: "midcap150" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite", sector: "Chemicals", bucket: "midcap150" },
  { symbol: "DIXON", name: "Dixon Technologies (India)", sector: "Consumer", bucket: "midcap150" },
  { symbol: "ESCORTS", name: "Escorts Kubota", sector: "Auto", bucket: "midcap150" },
  { symbol: "EXIDEIND", name: "Exide Industries", sector: "Auto", bucket: "midcap150" },
  { symbol: "FEDERALBNK", name: "Federal Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "GLAND", name: "Gland Pharma", sector: "Pharma", bucket: "midcap150" },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure", sector: "Infrastructure", bucket: "midcap150" },
  { symbol: "GODREJPROP", name: "Godrej Properties", sector: "Realty", bucket: "midcap150" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas", sector: "Utilities", bucket: "midcap150" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum", sector: "Energy", bucket: "midcap150" },
  { symbol: "IDEA", name: "Vodafone Idea", sector: "Telecom", bucket: "midcap150" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "IGL", name: "Indraprastha Gas", sector: "Utilities", bucket: "midcap150" },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "INDUSTOWER", name: "Indus Towers", sector: "Telecom", bucket: "midcap150" },
  { symbol: "IPCALAB", name: "IPCA Laboratories", sector: "Pharma", bucket: "midcap150" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks", sector: "FMCG", bucket: "midcap150" },
  { symbol: "L&TFH", name: "L&T Finance Holdings", sector: "NBFC", bucket: "midcap150" },
  { symbol: "LAURUSLABS", name: "Laurus Labs", sector: "Pharma", bucket: "midcap150" },
  { symbol: "LUPIN", name: "Lupin", sector: "Pharma", bucket: "midcap150" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services", sector: "NBFC", bucket: "midcap150" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance", sector: "NBFC", bucket: "midcap150" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute", sector: "Healthcare", bucket: "midcap150" },
  { symbol: "MFSL", name: "Max Financial Services", sector: "Insurance", bucket: "midcap150" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International", sector: "Auto", bucket: "midcap150" },
  { symbol: "MPHASIS", name: "Mphasis", sector: "IT", bucket: "midcap150" },
  { symbol: "MRF", name: "MRF", sector: "Auto", bucket: "midcap150" },
  { symbol: "NMDC", name: "NMDC", sector: "Metals", bucket: "midcap150" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", sector: "Realty", bucket: "midcap150" },
  { symbol: "OFSS", name: "Oracle Financial Services Software", sector: "IT", bucket: "midcap150" },
  { symbol: "PAGEIND", name: "Page Industries", sector: "Consumer", bucket: "midcap150" },
  { symbol: "PERSISTENT", name: "Persistent Systems", sector: "IT", bucket: "midcap150" },
  { symbol: "PETRONET", name: "Petronet LNG", sector: "Energy", bucket: "midcap150" },
  { symbol: "PIIND", name: "PI Industries", sector: "Chemicals", bucket: "midcap150" },
  { symbol: "POLYCAB", name: "Polycab India", sector: "Consumer", bucket: "midcap150" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects", sector: "Realty", bucket: "midcap150" },
  { symbol: "RVNL", name: "Rail Vikas Nigam", sector: "Infrastructure", bucket: "midcap150" },
  { symbol: "SAIL", name: "Steel Authority of India", sector: "Metals", bucket: "midcap150" },
  { symbol: "SHREECEM", name: "Shree Cement", sector: "Cement", bucket: "midcap150" },
  { symbol: "SOLARINDS", name: "Solar Industries India", sector: "Defence", bucket: "midcap150" },
  { symbol: "SRF", name: "SRF", sector: "Chemicals", bucket: "midcap150" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance", sector: "NBFC", bucket: "midcap150" },
  { symbol: "SUPREMEIND", name: "Supreme Industries", sector: "Consumer", bucket: "midcap150" },
  { symbol: "SYNGENE", name: "Syngene International", sector: "Pharma", bucket: "midcap150" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", sector: "IT", bucket: "midcap150" },
  { symbol: "TATATECH", name: "Tata Technologies", sector: "IT", bucket: "midcap150" },
  { symbol: "TIINDIA", name: "Tube Investments of India", sector: "Auto", bucket: "midcap150" },
  { symbol: "TORNTPOWER", name: "Torrent Power", sector: "Utilities", bucket: "midcap150" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company", sector: "Auto", bucket: "midcap150" },
  { symbol: "UBL", name: "United Breweries", sector: "FMCG", bucket: "midcap150" },
  { symbol: "UPL", name: "UPL", sector: "Chemicals", bucket: "midcap150" },
  { symbol: "VOLTAS", name: "Voltas", sector: "Consumer", bucket: "midcap150" },
  { symbol: "YESBANK", name: "Yes Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises", sector: "Media", bucket: "midcap150" },
  { symbol: "JSWINFRA", name: "JSW Infrastructure", sector: "Infrastructure", bucket: "midcap150" },
  { symbol: "KPITTECH", name: "KPIT Technologies", sector: "IT", bucket: "midcap150" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", sector: "Defence", bucket: "midcap150" },
  { symbol: "POLICYBZR", name: "PB Fintech (PolicyBazaar)", sector: "Internet", bucket: "midcap150" },
  { symbol: "PAYTM", name: "One 97 Communications (Paytm)", sector: "Internet", bucket: "midcap150" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures (Nykaa)", sector: "Internet", bucket: "midcap150" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corp", sector: "NBFC", bucket: "midcap150" },
  { symbol: "IDBI", name: "IDBI Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank", sector: "Banking", bucket: "midcap150" },
  { symbol: "RBLBANK", name: "RBL Bank", sector: "Banking", bucket: "midcap150" },

  // ===== Smallcap 250 (selected ~70) =====
  { symbol: "AARTIIND", name: "Aarti Industries", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "AAVAS", name: "Aavas Financiers", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "ABBOTINDIA", name: "Abbott India", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "ACE", name: "Action Construction Equipment", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "AETHER", name: "Aether Industries", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "AFFLE", name: "Affle India", sector: "Internet", bucket: "smallcap250" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy & Mobility", sector: "Auto", bucket: "smallcap250" },
  { symbol: "ANGELONE", name: "Angel One", sector: "Financial", bucket: "smallcap250" },
  { symbol: "APARINDS", name: "Apar Industries", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "ASTERDM", name: "Aster DM Healthcare", sector: "Healthcare", bucket: "smallcap250" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "BATAINDIA", name: "Bata India", sector: "Retail", bucket: "smallcap250" },
  { symbol: "BAYERCROP", name: "Bayer CropScience", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "BIRLACORPN", name: "Birla Corporation", sector: "Cement", bucket: "smallcap250" },
  { symbol: "BLUEDART", name: "Blue Dart Express", sector: "Logistics", bucket: "smallcap250" },
  { symbol: "BLUESTARCO", name: "Blue Star", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "BSOFT", name: "BirlaSoft", sector: "IT", bucket: "smallcap250" },
  { symbol: "CAMPUS", name: "Campus Activewear", sector: "Retail", bucket: "smallcap250" },
  { symbol: "CANFINHOME", name: "Can Fin Homes", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "CASTROLIND", name: "Castrol India", sector: "Energy", bucket: "smallcap250" },
  { symbol: "CEATLTD", name: "CEAT", sector: "Auto", bucket: "smallcap250" },
  { symbol: "CENTRALBK", name: "Central Bank of India", sector: "Banking", bucket: "smallcap250" },
  { symbol: "CENTURYTEX", name: "Century Textiles & Industries", sector: "Realty", bucket: "smallcap250" },
  { symbol: "CESC", name: "CESC", sector: "Utilities", bucket: "smallcap250" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilizers", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "CHENNPETRO", name: "Chennai Petroleum Corporation", sector: "Energy", bucket: "smallcap250" },
  { symbol: "CRISIL", name: "CRISIL", sector: "Financial", bucket: "smallcap250" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "CUB", name: "City Union Bank", sector: "Banking", bucket: "smallcap250" },
  { symbol: "CYIENT", name: "Cyient", sector: "IT", bucket: "smallcap250" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilizers", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "DELHIVERY", name: "Delhivery", sector: "Logistics", bucket: "smallcap250" },
  { symbol: "EIDPARRY", name: "EID Parry (India)", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "EIHOTEL", name: "EIH", sector: "Hospitality", bucket: "smallcap250" },
  { symbol: "EMAMILTD", name: "Emami", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "ENGINERSIN", name: "Engineers India", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank", sector: "Banking", bucket: "smallcap250" },
  { symbol: "FACT", name: "Fertilizers & Chemicals Travancore", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "FINCABLES", name: "Finolex Cables", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "FINPIPE", name: "Finolex Industries", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "FIVESTAR", name: "Five Star Business Finance", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "FSL", name: "Firstsource Solutions", sector: "IT", bucket: "smallcap250" },
  { symbol: "GAEL", name: "Gujarat Ambuja Exports", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "GICRE", name: "General Insurance Corporation", sector: "Insurance", bucket: "smallcap250" },
  { symbol: "GILLETTE", name: "Gillette India", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "GMDCLTD", name: "Gujarat Mineral Development", sector: "Metals", bucket: "smallcap250" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", sector: "Chemicals", bucket: "smallcap250" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips India", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "GRANULES", name: "Granules India", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "GRINDWELL", name: "Grindwell Norton", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "GSPL", name: "Gujarat State Petronet", sector: "Energy", bucket: "smallcap250" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", sector: "IT", bucket: "smallcap250" },
  { symbol: "HATSUN", name: "Hatsun Agro Product", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "HEG", name: "HEG", sector: "Metals", bucket: "smallcap250" },
  { symbol: "HFCL", name: "HFCL", sector: "Telecom", bucket: "smallcap250" },
  { symbol: "HONAUT", name: "Honeywell Automation India", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "IDFC", name: "IDFC", sector: "Financial", bucket: "smallcap250" },
  { symbol: "IIFL", name: "IIFL Finance", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH", sector: "Internet", bucket: "smallcap250" },
  { symbol: "INDIANHUME", name: "Indian Hume Pipe", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "IOB", name: "Indian Overseas Bank", sector: "Banking", bucket: "smallcap250" },
  { symbol: "IRCON", name: "Ircon International", sector: "Infrastructure", bucket: "smallcap250" },
  { symbol: "JBCHEPHARM", name: "JB Chemicals & Pharmaceuticals", sector: "Pharma", bucket: "smallcap250" },
  { symbol: "JKCEMENT", name: "JK Cement", sector: "Cement", bucket: "smallcap250" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs", sector: "FMCG", bucket: "smallcap250" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India", sector: "Retail", bucket: "smallcap250" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank", sector: "Banking", bucket: "smallcap250" },
  { symbol: "KEC", name: "KEC International", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "KFINTECH", name: "KFin Technologies", sector: "Financial", bucket: "smallcap250" },
  { symbol: "KIRLOSENG", name: "Kirloskar Oil Engines", sector: "Capital Goods", bucket: "smallcap250" },
  { symbol: "KPRMILL", name: "KPR Mill", sector: "Consumer", bucket: "smallcap250" },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs", sector: "Healthcare", bucket: "smallcap250" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics", sector: "IT", bucket: "smallcap250" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", sector: "NBFC", bucket: "smallcap250" },
  { symbol: "LTTS", name: "L&T Technology Services", sector: "IT", bucket: "smallcap250" },
];

export const BUCKET_LABEL: Record<IndexBucket, string> = {
  nifty50: "Nifty 50",
  next50: "Nifty Next 50",
  midcap150: "Nifty Midcap 150",
  smallcap250: "Nifty Smallcap 250",
};

export function searchStocks(query: string, limit = 50): NiftyStock[] {
  const q = query.trim().toLowerCase();
  if (!q) return NIFTY500.slice(0, limit);
  return NIFTY500.filter(
    (s) =>
      s.symbol.toLowerCase().includes(q) ||
      s.name.toLowerCase().includes(q) ||
      s.sector.toLowerCase().includes(q)
  ).slice(0, limit);
}

export function getStockBySymbol(symbol: string): NiftyStock | undefined {
  return NIFTY500.find((s) => s.symbol.toUpperCase() === symbol.toUpperCase());
}
