/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as DematRouteImport } from './routes/demat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BacktesterRouteImport } from './routes/backtester'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const DematRoute = DematRouteImport.update({
  id: '/demat',
  path: '/demat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktesterRoute = BacktesterRouteImport.update({
  id: '/backtester',
  path: '/backtester',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/funds': typeof FundsRoute
  '/news': typeof NewsRoute
  '/pitch': typeof PitchRoute
  '/scanner': typeof ScannerRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/funds': typeof FundsRoute
  '/news': typeof NewsRoute
  '/pitch': typeof PitchRoute
  '/scanner': typeof ScannerRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/funds': typeof FundsRoute
  '/news': typeof NewsRoute
  '/pitch': typeof PitchRoute
  '/scanner': typeof ScannerRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtester'
    | '/dashboard'
    | '/demat'
    | '/funds'
    | '/news'
    | '/pitch'
    | '/scanner'
    | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtester'
    | '/dashboard'
    | '/demat'
    | '/funds'
    | '/news'
    | '/pitch'
    | '/scanner'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/backtester'
    | '/dashboard'
    | '/demat'
    | '/funds'
    | '/news'
    | '/pitch'
    | '/scanner'
    | '/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktesterRoute: typeof BacktesterRoute
  DashboardRoute: typeof DashboardRoute
  DematRoute: typeof DematRoute
  FundsRoute: typeof FundsRoute
  NewsRoute: typeof NewsRoute
  PitchRoute: typeof PitchRoute
  ScannerRoute: typeof ScannerRoute
  WatchlistRoute: typeof WatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demat': {
      id: '/demat'
      path: '/demat'
      fullPath: '/demat'
      preLoaderRoute: typeof DematRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtester': {
      id: '/backtester'
      path: '/backtester'
      fullPath: '/backtester'
      preLoaderRoute: typeof BacktesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktesterRoute: BacktesterRoute,
  DashboardRoute: DashboardRoute,
  DematRoute: DematRoute,
  FundsRoute: FundsRoute,
  NewsRoute: NewsRoute,
  PitchRoute: PitchRoute,
  ScannerRoute: ScannerRoute,
  WatchlistRoute: WatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
