/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SipRouteImport } from './routes/sip'
import { Route as ShadowRouteImport } from './routes/shadow'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DematRouteImport } from './routes/demat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BiometricsRouteImport } from './routes/biometrics'
import { Route as BacktesterRouteImport } from './routes/backtester'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SipRoute = SipRouteImport.update({
  id: '/sip',
  path: '/sip',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowRoute = ShadowRouteImport.update({
  id: '/shadow',
  path: '/shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DematRoute = DematRouteImport.update({
  id: '/demat',
  path: '/demat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricsRoute = BiometricsRouteImport.update({
  id: '/biometrics',
  path: '/biometrics',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktesterRoute = BacktesterRouteImport.update({
  id: '/backtester',
  path: '/backtester',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/biometrics': typeof BiometricsRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/forecast': typeof ForecastRoute
  '/funds': typeof FundsRoute
  '/goals': typeof GoalsRoute
  '/news': typeof NewsRoute
  '/optimizer': typeof OptimizerRoute
  '/pitch': typeof PitchRoute
  '/portfolio': typeof PortfolioRoute
  '/scanner': typeof ScannerRoute
  '/score': typeof ScoreRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/shadow': typeof ShadowRoute
  '/sip': typeof SipRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/biometrics': typeof BiometricsRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/forecast': typeof ForecastRoute
  '/funds': typeof FundsRoute
  '/goals': typeof GoalsRoute
  '/news': typeof NewsRoute
  '/optimizer': typeof OptimizerRoute
  '/pitch': typeof PitchRoute
  '/portfolio': typeof PortfolioRoute
  '/scanner': typeof ScannerRoute
  '/score': typeof ScoreRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/shadow': typeof ShadowRoute
  '/sip': typeof SipRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/biometrics': typeof BiometricsRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/forecast': typeof ForecastRoute
  '/funds': typeof FundsRoute
  '/goals': typeof GoalsRoute
  '/news': typeof NewsRoute
  '/optimizer': typeof OptimizerRoute
  '/pitch': typeof PitchRoute
  '/portfolio': typeof PortfolioRoute
  '/scanner': typeof ScannerRoute
  '/score': typeof ScoreRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/shadow': typeof ShadowRoute
  '/sip': typeof SipRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtester'
    | '/biometrics'
    | '/dashboard'
    | '/demat'
    | '/forecast'
    | '/funds'
    | '/goals'
    | '/news'
    | '/optimizer'
    | '/pitch'
    | '/portfolio'
    | '/scanner'
    | '/score'
    | '/screener'
    | '/settings'
    | '/shadow'
    | '/sip'
    | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtester'
    | '/biometrics'
    | '/dashboard'
    | '/demat'
    | '/forecast'
    | '/funds'
    | '/goals'
    | '/news'
    | '/optimizer'
    | '/pitch'
    | '/portfolio'
    | '/scanner'
    | '/score'
    | '/screener'
    | '/settings'
    | '/shadow'
    | '/sip'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/backtester'
    | '/biometrics'
    | '/dashboard'
    | '/demat'
    | '/forecast'
    | '/funds'
    | '/goals'
    | '/news'
    | '/optimizer'
    | '/pitch'
    | '/portfolio'
    | '/scanner'
    | '/score'
    | '/screener'
    | '/settings'
    | '/shadow'
    | '/sip'
    | '/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktesterRoute: typeof BacktesterRoute
  BiometricsRoute: typeof BiometricsRoute
  DashboardRoute: typeof DashboardRoute
  DematRoute: typeof DematRoute
  ForecastRoute: typeof ForecastRoute
  FundsRoute: typeof FundsRoute
  GoalsRoute: typeof GoalsRoute
  NewsRoute: typeof NewsRoute
  OptimizerRoute: typeof OptimizerRoute
  PitchRoute: typeof PitchRoute
  PortfolioRoute: typeof PortfolioRoute
  ScannerRoute: typeof ScannerRoute
  ScoreRoute: typeof ScoreRoute
  ScreenerRoute: typeof ScreenerRoute
  SettingsRoute: typeof SettingsRoute
  ShadowRoute: typeof ShadowRoute
  SipRoute: typeof SipRoute
  WatchlistRoute: typeof WatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sip': {
      id: '/sip'
      path: '/sip'
      fullPath: '/sip'
      preLoaderRoute: typeof SipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow': {
      id: '/shadow'
      path: '/shadow'
      fullPath: '/shadow'
      preLoaderRoute: typeof ShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demat': {
      id: '/demat'
      path: '/demat'
      fullPath: '/demat'
      preLoaderRoute: typeof DematRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometrics': {
      id: '/biometrics'
      path: '/biometrics'
      fullPath: '/biometrics'
      preLoaderRoute: typeof BiometricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtester': {
      id: '/backtester'
      path: '/backtester'
      fullPath: '/backtester'
      preLoaderRoute: typeof BacktesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktesterRoute: BacktesterRoute,
  BiometricsRoute: BiometricsRoute,
  DashboardRoute: DashboardRoute,
  DematRoute: DematRoute,
  ForecastRoute: ForecastRoute,
  FundsRoute: FundsRoute,
  GoalsRoute: GoalsRoute,
  NewsRoute: NewsRoute,
  OptimizerRoute: OptimizerRoute,
  PitchRoute: PitchRoute,
  PortfolioRoute: PortfolioRoute,
  ScannerRoute: ScannerRoute,
  ScoreRoute: ScoreRoute,
  ScreenerRoute: ScreenerRoute,
  SettingsRoute: SettingsRoute,
  ShadowRoute: ShadowRoute,
  SipRoute: SipRoute,
  WatchlistRoute: WatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
