/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as SipRouteImport } from './routes/sip'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as PortfolioAnalyserRouteImport } from './routes/portfolio-analyser'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InvestmentMasterclassRouteImport } from './routes/investment-masterclass'
import { Route as IndicesRouteImport } from './routes/indices'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as ForecastClassicRouteImport } from './routes/forecast-classic'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as EtfsRouteImport } from './routes/etfs'
import { Route as DematRouteImport } from './routes/demat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BiometricsRouteImport } from './routes/biometrics'
import { Route as BacktesterRouteImport } from './routes/backtester'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiForecastRouteImport } from './routes/api/forecast'
import { Route as ApiPublicSyncQuotesRouteImport } from './routes/api/public/sync-quotes'
import { Route as ApiPublicSyncEtfsRouteImport } from './routes/api/public/sync-etfs'
import { Route as ApiPublicDataRefreshEodRouteImport } from './routes/api/public/data-refresh-eod'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SipRoute = SipRouteImport.update({
  id: '/sip',
  path: '/sip',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioAnalyserRoute = PortfolioAnalyserRouteImport.update({
  id: '/portfolio-analyser',
  path: '/portfolio-analyser',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentMasterclassRoute = InvestmentMasterclassRouteImport.update({
  id: '/investment-masterclass',
  path: '/investment-masterclass',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesRoute = IndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastClassicRoute = ForecastClassicRouteImport.update({
  id: '/forecast-classic',
  path: '/forecast-classic',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const EtfsRoute = EtfsRouteImport.update({
  id: '/etfs',
  path: '/etfs',
  getParentRoute: () => rootRouteImport,
} as any)
const DematRoute = DematRouteImport.update({
  id: '/demat',
  path: '/demat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricsRoute = BiometricsRouteImport.update({
  id: '/biometrics',
  path: '/biometrics',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktesterRoute = BacktesterRouteImport.update({
  id: '/backtester',
  path: '/backtester',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForecastRoute = ApiForecastRouteImport.update({
  id: '/api/forecast',
  path: '/api/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncQuotesRoute = ApiPublicSyncQuotesRouteImport.update({
  id: '/api/public/sync-quotes',
  path: '/api/public/sync-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncEtfsRoute = ApiPublicSyncEtfsRouteImport.update({
  id: '/api/public/sync-etfs',
  path: '/api/public/sync-etfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDataRefreshEodRoute = ApiPublicDataRefreshEodRouteImport.update({
  id: '/api/public/data-refresh-eod',
  path: '/api/public/data-refresh-eod',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/biometrics': typeof BiometricsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/etfs': typeof EtfsRoute
  '/forecast': typeof ForecastRoute
  '/forecast-classic': typeof ForecastClassicRoute
  '/funds': typeof FundsRoute
  '/goals': typeof GoalsRoute
  '/heatmap': typeof HeatmapRoute
  '/indices': typeof IndicesRoute
  '/investment-masterclass': typeof InvestmentMasterclassRoute
  '/news': typeof NewsRoute
  '/optimizer': typeof OptimizerRoute
  '/pitch': typeof PitchRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio-analyser': typeof PortfolioAnalyserRoute
  '/scanner': typeof ScannerRoute
  '/score': typeof ScoreRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sip': typeof SipRoute
  '/tax': typeof TaxRoute
  '/watchlist': typeof WatchlistRoute
  '/api/forecast': typeof ApiForecastRoute
  '/api/public/data-refresh-eod': typeof ApiPublicDataRefreshEodRoute
  '/api/public/sync-etfs': typeof ApiPublicSyncEtfsRoute
  '/api/public/sync-quotes': typeof ApiPublicSyncQuotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/biometrics': typeof BiometricsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/etfs': typeof EtfsRoute
  '/forecast': typeof ForecastRoute
  '/forecast-classic': typeof ForecastClassicRoute
  '/funds': typeof FundsRoute
  '/goals': typeof GoalsRoute
  '/heatmap': typeof HeatmapRoute
  '/indices': typeof IndicesRoute
  '/investment-masterclass': typeof InvestmentMasterclassRoute
  '/news': typeof NewsRoute
  '/optimizer': typeof OptimizerRoute
  '/pitch': typeof PitchRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio-analyser': typeof PortfolioAnalyserRoute
  '/scanner': typeof ScannerRoute
  '/score': typeof ScoreRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sip': typeof SipRoute
  '/tax': typeof TaxRoute
  '/watchlist': typeof WatchlistRoute
  '/api/forecast': typeof ApiForecastRoute
  '/api/public/data-refresh-eod': typeof ApiPublicDataRefreshEodRoute
  '/api/public/sync-etfs': typeof ApiPublicSyncEtfsRoute
  '/api/public/sync-quotes': typeof ApiPublicSyncQuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtester': typeof BacktesterRoute
  '/biometrics': typeof BiometricsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demat': typeof DematRoute
  '/etfs': typeof EtfsRoute
  '/forecast': typeof ForecastRoute
  '/forecast-classic': typeof ForecastClassicRoute
  '/funds': typeof FundsRoute
  '/goals': typeof GoalsRoute
  '/heatmap': typeof HeatmapRoute
  '/indices': typeof IndicesRoute
  '/investment-masterclass': typeof InvestmentMasterclassRoute
  '/news': typeof NewsRoute
  '/optimizer': typeof OptimizerRoute
  '/pitch': typeof PitchRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio-analyser': typeof PortfolioAnalyserRoute
  '/scanner': typeof ScannerRoute
  '/score': typeof ScoreRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sip': typeof SipRoute
  '/tax': typeof TaxRoute
  '/watchlist': typeof WatchlistRoute
  '/api/forecast': typeof ApiForecastRoute
  '/api/public/data-refresh-eod': typeof ApiPublicDataRefreshEodRoute
  '/api/public/sync-etfs': typeof ApiPublicSyncEtfsRoute
  '/api/public/sync-quotes': typeof ApiPublicSyncQuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtester'
    | '/biometrics'
    | '/community'
    | '/dashboard'
    | '/demat'
    | '/etfs'
    | '/forecast'
    | '/forecast-classic'
    | '/funds'
    | '/goals'
    | '/heatmap'
    | '/indices'
    | '/investment-masterclass'
    | '/news'
    | '/optimizer'
    | '/pitch'
    | '/portfolio'
    | '/portfolio-analyser'
    | '/scanner'
    | '/score'
    | '/screener'
    | '/settings'
    | '/sip'
    | '/tax'
    | '/watchlist'
    | '/api/forecast'
    | '/api/public/data-refresh-eod'
    | '/api/public/sync-etfs'
    | '/api/public/sync-quotes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtester'
    | '/biometrics'
    | '/community'
    | '/dashboard'
    | '/demat'
    | '/etfs'
    | '/forecast'
    | '/forecast-classic'
    | '/funds'
    | '/goals'
    | '/heatmap'
    | '/indices'
    | '/investment-masterclass'
    | '/news'
    | '/optimizer'
    | '/pitch'
    | '/portfolio'
    | '/portfolio-analyser'
    | '/scanner'
    | '/score'
    | '/screener'
    | '/settings'
    | '/sip'
    | '/tax'
    | '/watchlist'
    | '/api/forecast'
    | '/api/public/data-refresh-eod'
    | '/api/public/sync-etfs'
    | '/api/public/sync-quotes'
  id:
    | '__root__'
    | '/'
    | '/backtester'
    | '/biometrics'
    | '/community'
    | '/dashboard'
    | '/demat'
    | '/etfs'
    | '/forecast'
    | '/forecast-classic'
    | '/funds'
    | '/goals'
    | '/heatmap'
    | '/indices'
    | '/investment-masterclass'
    | '/news'
    | '/optimizer'
    | '/pitch'
    | '/portfolio'
    | '/portfolio-analyser'
    | '/scanner'
    | '/score'
    | '/screener'
    | '/settings'
    | '/sip'
    | '/tax'
    | '/watchlist'
    | '/api/forecast'
    | '/api/public/data-refresh-eod'
    | '/api/public/sync-etfs'
    | '/api/public/sync-quotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktesterRoute: typeof BacktesterRoute
  BiometricsRoute: typeof BiometricsRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  DematRoute: typeof DematRoute
  EtfsRoute: typeof EtfsRoute
  ForecastRoute: typeof ForecastRoute
  ForecastClassicRoute: typeof ForecastClassicRoute
  FundsRoute: typeof FundsRoute
  GoalsRoute: typeof GoalsRoute
  HeatmapRoute: typeof HeatmapRoute
  IndicesRoute: typeof IndicesRoute
  InvestmentMasterclassRoute: typeof InvestmentMasterclassRoute
  NewsRoute: typeof NewsRoute
  OptimizerRoute: typeof OptimizerRoute
  PitchRoute: typeof PitchRoute
  PortfolioRoute: typeof PortfolioRoute
  PortfolioAnalyserRoute: typeof PortfolioAnalyserRoute
  ScannerRoute: typeof ScannerRoute
  ScoreRoute: typeof ScoreRoute
  ScreenerRoute: typeof ScreenerRoute
  SettingsRoute: typeof SettingsRoute
  SipRoute: typeof SipRoute
  TaxRoute: typeof TaxRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiForecastRoute: typeof ApiForecastRoute
  ApiPublicDataRefreshEodRoute: typeof ApiPublicDataRefreshEodRoute
  ApiPublicSyncEtfsRoute: typeof ApiPublicSyncEtfsRoute
  ApiPublicSyncQuotesRoute: typeof ApiPublicSyncQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sip': {
      id: '/sip'
      path: '/sip'
      fullPath: '/sip'
      preLoaderRoute: typeof SipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-analyser': {
      id: '/portfolio-analyser'
      path: '/portfolio-analyser'
      fullPath: '/portfolio-analyser'
      preLoaderRoute: typeof PortfolioAnalyserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-masterclass': {
      id: '/investment-masterclass'
      path: '/investment-masterclass'
      fullPath: '/investment-masterclass'
      preLoaderRoute: typeof InvestmentMasterclassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices': {
      id: '/indices'
      path: '/indices'
      fullPath: '/indices'
      preLoaderRoute: typeof IndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast-classic': {
      id: '/forecast-classic'
      path: '/forecast-classic'
      fullPath: '/forecast-classic'
      preLoaderRoute: typeof ForecastClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etfs': {
      id: '/etfs'
      path: '/etfs'
      fullPath: '/etfs'
      preLoaderRoute: typeof EtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demat': {
      id: '/demat'
      path: '/demat'
      fullPath: '/demat'
      preLoaderRoute: typeof DematRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometrics': {
      id: '/biometrics'
      path: '/biometrics'
      fullPath: '/biometrics'
      preLoaderRoute: typeof BiometricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtester': {
      id: '/backtester'
      path: '/backtester'
      fullPath: '/backtester'
      preLoaderRoute: typeof BacktesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forecast': {
      id: '/api/forecast'
      path: '/api/forecast'
      fullPath: '/api/forecast'
      preLoaderRoute: typeof ApiForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-quotes': {
      id: '/api/public/sync-quotes'
      path: '/api/public/sync-quotes'
      fullPath: '/api/public/sync-quotes'
      preLoaderRoute: typeof ApiPublicSyncQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-etfs': {
      id: '/api/public/sync-etfs'
      path: '/api/public/sync-etfs'
      fullPath: '/api/public/sync-etfs'
      preLoaderRoute: typeof ApiPublicSyncEtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/data-refresh-eod': {
      id: '/api/public/data-refresh-eod'
      path: '/api/public/data-refresh-eod'
      fullPath: '/api/public/data-refresh-eod'
      preLoaderRoute: typeof ApiPublicDataRefreshEodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktesterRoute: BacktesterRoute,
  BiometricsRoute: BiometricsRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  DematRoute: DematRoute,
  EtfsRoute: EtfsRoute,
  ForecastRoute: ForecastRoute,
  ForecastClassicRoute: ForecastClassicRoute,
  FundsRoute: FundsRoute,
  GoalsRoute: GoalsRoute,
  HeatmapRoute: HeatmapRoute,
  IndicesRoute: IndicesRoute,
  InvestmentMasterclassRoute: InvestmentMasterclassRoute,
  NewsRoute: NewsRoute,
  OptimizerRoute: OptimizerRoute,
  PitchRoute: PitchRoute,
  PortfolioRoute: PortfolioRoute,
  PortfolioAnalyserRoute: PortfolioAnalyserRoute,
  ScannerRoute: ScannerRoute,
  ScoreRoute: ScoreRoute,
  ScreenerRoute: ScreenerRoute,
  SettingsRoute: SettingsRoute,
  SipRoute: SipRoute,
  TaxRoute: TaxRoute,
  WatchlistRoute: WatchlistRoute,
  ApiForecastRoute: ApiForecastRoute,
  ApiPublicDataRefreshEodRoute: ApiPublicDataRefreshEodRoute,
  ApiPublicSyncEtfsRoute: ApiPublicSyncEtfsRoute,
  ApiPublicSyncQuotesRoute: ApiPublicSyncQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
