import type { Book } from "./types";

export const BOOKS: Book[] = [
  { slug: "intelligent-investor", title: "The Intelligent Investor", author: "Benjamin Graham", tags: ["Value"], takeaway: "Margin of safety & Mr. Market — the founding text of value investing.", investors: ["graham","buffett","klarman"], shelf: "core" },
  { slug: "security-analysis", title: "Security Analysis", author: "Graham & Dodd", tags: ["Value"], takeaway: "Rigorous fundamental valuation, the analyst's bible.", investors: ["graham","buffett","klarman"], shelf: "core" },
  { slug: "common-stocks", title: "Common Stocks and Uncommon Profits", author: "Philip Fisher", tags: ["Growth"], takeaway: "Scuttlebutt research and long-term growth compounding.", investors: ["fisher","buffett","munger"], shelf: "core" },
  { slug: "essays-buffett", title: "The Essays of Warren Buffett", author: "ed. Lawrence Cunningham", tags: ["Value"], takeaway: "Business-owner mindset distilled from decades of shareholder letters.", investors: ["buffett","munger"], shelf: "core" },
  { slug: "brk-letters", title: "Berkshire Hathaway Shareholder Letters", author: "Warren Buffett", tags: ["Value"], takeaway: "Free, primary-source compounding wisdom.", investors: ["buffett","munger"], shelf: "core" },
  { slug: "poor-charlies-almanack", title: "Poor Charlie's Almanack", author: "Charles Munger", tags: ["Mindset"], takeaway: "Mental models and multidisciplinary thinking.", investors: ["munger","spier","pabrai"], shelf: "core" },
  { slug: "one-up", title: "One Up on Wall Street", author: "Peter Lynch", tags: ["Growth"], takeaway: "Invest in what you understand and see in daily life.", investors: ["lynch"], shelf: "core" },
  { slug: "beating-street", title: "Beating the Street", author: "Peter Lynch", tags: ["Growth"], takeaway: "Practical stock-picking process from Magellan's peak years.", investors: ["lynch"], shelf: "core" },
  { slug: "most-important-thing", title: "The Most Important Thing", author: "Howard Marks", tags: ["Risk"], takeaway: "Second-level thinking, cycles, and risk control.", investors: ["marks","klarman","naren"], shelf: "core" },
  { slug: "margin-of-safety", title: "Margin of Safety", author: "Seth Klarman", tags: ["Value"], takeaway: "Deep value discipline (out of print, famously expensive).", investors: ["klarman","graham"], shelf: "core" },
  { slug: "dhandho", title: "The Dhandho Investor", author: "Mohnish Pabrai", tags: ["Value"], takeaway: "Heads I win, tails I don't lose much — low-risk, high-uncertainty bets.", investors: ["pabrai","spier"], shelf: "core" },
  { slug: "stock-market-genius", title: "You Can Be a Stock Market Genius", author: "Joel Greenblatt", tags: ["Special Situations"], takeaway: "Spin-offs, mergers, and other overlooked pockets of edge.", investors: ["greenblatt"], shelf: "core" },
  { slug: "little-book-beats", title: "The Little Book That Beats the Market", author: "Joel Greenblatt", tags: ["Quant"], takeaway: "Magic Formula quant value made simple.", investors: ["greenblatt"], shelf: "core" },
  { slug: "little-book-common-sense", title: "The Little Book of Common Sense Investing", author: "John Bogle", tags: ["Passive"], takeaway: "Low-cost indexing beats most stock pickers.", investors: ["bogle","malkiel"], shelf: "core" },
  { slug: "random-walk", title: "A Random Walk Down Wall Street", author: "Burton Malkiel", tags: ["Passive"], takeaway: "Efficient markets and the case for diversification.", investors: ["malkiel","bogle"], shelf: "core" },
  { slug: "reminiscences", title: "Reminiscences of a Stock Operator", author: "Edwin Lefèvre", tags: ["Psychology"], takeaway: "Trading psychology via the life of Jesse Livermore.", investors: ["livermore","tudor-jones"], shelf: "core" },
  { slug: "market-wizards", title: "Market Wizards", author: "Jack Schwager", tags: ["Psychology"], takeaway: "Interviews with elite traders across styles.", investors: ["tudor-jones","druckenmiller","soros"], shelf: "core" },
  { slug: "psychology-money", title: "The Psychology of Money", author: "Morgan Housel", tags: ["Behavioral"], takeaway: "Behaviour beats math — your temperament is the edge.", investors: ["bakshi","spier","housel-attrib"], shelf: "core" },
  { slug: "thinking-fast-slow", title: "Thinking, Fast and Slow", author: "Daniel Kahneman", tags: ["Behavioral"], takeaway: "The cognitive biases that quietly destroy portfolios.", investors: ["bakshi","spier"], shelf: "core" },
  { slug: "black-swan", title: "The Black Swan", author: "Nassim Taleb", tags: ["Risk"], takeaway: "Tail risk and the fragility of forecasts.", investors: ["taleb","burry"], shelf: "core" },
  { slug: "fooled-randomness", title: "Fooled by Randomness", author: "Nassim Taleb", tags: ["Risk"], takeaway: "Luck versus skill in markets.", investors: ["taleb"], shelf: "core" },
  { slug: "principles", title: "Principles", author: "Ray Dalio", tags: ["Macro"], takeaway: "Systematic decision-making and radical transparency.", investors: ["dalio"], shelf: "core" },
  { slug: "outsiders", title: "The Outsiders", author: "William Thorndike", tags: ["Capital Allocation"], takeaway: "Capital allocation by unconventional CEOs.", investors: ["buffett","berkowitz"], shelf: "core" },
  { slug: "man-for-all-markets", title: "A Man for All Markets", author: "Ed Thorp", tags: ["Quant"], takeaway: "Quantitative edge from blackjack to Wall Street.", investors: ["thorp","simons"], shelf: "core" },
  { slug: "alchemy-finance", title: "The Alchemy of Finance", author: "George Soros", tags: ["Macro"], takeaway: "Reflexivity: markets shape the fundamentals they price.", investors: ["soros","druckenmiller"], shelf: "core" },

  { slug: "coffee-can", title: "Coffee Can Investing", author: "Saurabh Mukherjea", tags: ["India","Value"], takeaway: "A no-touch portfolio of clean-accounting compounders.", investors: ["mukherjea"], shelf: "india" },
  { slug: "unusual-billionaires", title: "The Unusual Billionaires", author: "Saurabh Mukherjea", tags: ["India"], takeaway: "Case studies of Indian companies that compounded for decades.", investors: ["mukherjea"], shelf: "india" },
  { slug: "avoid-loss-earn", title: "How to Avoid Loss and Earn Consistently", author: "Prasenjit Paul", tags: ["India","Value"], takeaway: "Simple filters for Indian retail investors.", investors: [], shelf: "india" },
  { slug: "stocks-to-riches", title: "Stocks to Riches", author: "Parag Parikh", tags: ["India","Behavioral"], takeaway: "Behavioural traps every Indian investor must dodge.", investors: ["parikh"], shelf: "india" },
  { slug: "big-bull-essays", title: "The Big Bull of Dalal Street", author: "Neil Borate & others", tags: ["India"], takeaway: "Illustrative essays on Rakesh Jhunjhunwala's playbook.", investors: ["jhunjhunwala"], shelf: "india" },
];
