import type { Investor } from "./types";

// Every performance stat below is approximate, historical, and educational only.
// Quotes marked quoteVerified:false are widely attributed but not sourced to a primary text.

const mk = (i: Investor): Investor => i;

export const INVESTORS: Investor[] = [
  // ---------- GLOBAL LEGENDS ----------
  mk({
    slug: "buffett", name: "Warren Buffett", epithet: "The Oracle of Omaha", country: "USA", flag: "🇺🇸",
    era: "1965–present", eraStart: 1960, categories: ["Value","Growth"], primary: "Value",
    cagr: "~19–20% CAGR (Berkshire, ~1965–2023, approx./educational)", cagrNum: 19.8,
    bio: "Compounded Berkshire Hathaway from a failing textile mill into a global holding company by owning wonderful businesses forever.",
    principles: [
      "Buy wonderful businesses at fair prices, not fair businesses at wonderful prices",
      "Circle of competence — only own what you understand",
      "Economic moats: brand, cost, network, switching, regulation",
      "Time is the friend of a great business, the enemy of a mediocre one",
      "Be fearful when others are greedy; greedy when others are fearful",
    ],
    avoids: ["Businesses he cannot understand", "Excessive leverage", "IPO froth and hot themes"],
    allocation: [
      { name: "Consumer brands", value: 22 }, { name: "Financials", value: 24 },
      { name: "Tech (concentrated)", value: 30 }, { name: "Energy & utilities", value: 12 }, { name: "Cash", value: 12 },
    ],
    holdingPeriod: "Forever (average > 10 yrs)", concentration: "Top 5 ≈ 70% of equity book",
    framework: { name: "Circle of Competence", detail: "Only invest where you can honestly answer four questions.",
      items: ["Do I understand the product in one paragraph?","Is management honest and owner-oriented?","Is there a durable moat?","Is the price sensible vs. long-term earnings power?"] },
    caseStudy: "Buffett began accumulating Coca-Cola in 1988 after the 1987 crash, betting on global brand strength and pricing power. He paid ~15x earnings for a business he saw compounding for decades. The stake grew many-fold and pays dividends larger than the original cost basis annually.",
    quote: "Price is what you pay. Value is what you get.", quoteVerified: true,
    strength: "Temperament and patience under any market weather",
    blindspot: "Slow to embrace new technology paradigms; missed early tech waves",
    bookSlugs: ["essays-buffett","brk-letters","intelligent-investor","common-stocks"],
  }),
  mk({
    slug: "munger", name: "Charlie Munger", epithet: "The Abominable No-Man", country: "USA", flag: "🇺🇸",
    era: "1962–2023", eraStart: 1960, categories: ["Value","Growth"], primary: "Value",
    cagr: "Berkshire vice-chair; personal partnership ~19% CAGR 1962–1975 (approx.)", cagrNum: 19,
    bio: "Buffett's partner who upgraded Berkshire from cigar-butt value to quality-at-fair-price via multidisciplinary mental models.",
    principles: [
      "A great business at a fair price beats a fair business at a great price",
      "Invert, always invert — solve problems backwards",
      "Build a latticework of mental models across disciplines",
      "Sit on your hands until a fat pitch appears",
      "Avoid stupidity rather than seek brilliance",
    ],
    avoids: ["Envy-driven trades","Ideology","Complex derivatives he cannot explain simply"],
    allocation: [{name:"Concentrated equity",value:80},{name:"Cash & bonds",value:20}],
    holdingPeriod: "Decades", concentration: "3–5 positions at Daily Journal / Wesco style",
    framework: { name: "Mental Models Latticework", detail: "Combine ~100 big ideas from major disciplines to check any investment thesis.",
      items: ["Psychology of misjudgment","Basic microeconomics of moats","Physics of scale & feedback loops","Ecology of competition","Math of probabilities"] },
    caseStudy: "Munger backed BYD in 2008 as an under-appreciated Chinese battery-and-auto compounder. Despite volatility and years of scepticism, the position multiplied many times as EV adoption arrived — a textbook fat-pitch bet held with patience.",
    quote: "The big money is in the waiting, not the buying and selling.", quoteVerified: true,
    strength: "Rigorous inversion and behavioural discipline",
    blindspot: "Concentration means large drawdowns during panics",
    bookSlugs: ["poor-charlies-almanack","essays-buffett","psychology-money"],
  }),
  mk({
    slug: "graham", name: "Benjamin Graham", epithet: "Father of Value Investing", country: "USA", flag: "🇺🇸",
    era: "1928–1956", eraStart: 1920, categories: ["Value"], primary: "Value",
    cagr: "~20% CAGR Graham-Newman (approx., 1936–1956)", cagrNum: 20,
    bio: "Wrote Security Analysis and The Intelligent Investor; invented margin of safety and Mr. Market.",
    principles: [
      "Margin of safety is the single most important idea in investing",
      "Mr. Market is a bipolar business partner — use his moods, don't follow them",
      "An investment operation promises safety of principal and adequate return",
      "Buy net-nets: stocks below net current asset value",
      "Diversify widely at the deep-value end",
    ],
    avoids: ["Speculation on price alone","Story stocks without earnings","Leverage"],
    allocation: [{name:"Deep-value equities",value:60},{name:"Bonds",value:35},{name:"Cash",value:5}],
    holdingPeriod: "2–3 years or until fair value", concentration: "Wide (30+ positions)",
    framework: { name: "Net-Net Screen", detail: "Buy at less than 2/3 of Net Current Asset Value.",
      items: ["Current assets − total liabilities = NCAV","Market cap < 2/3 × NCAV","Positive earnings recent year","No looming solvency risk"] },
    caseStudy: "Graham's biggest win was GEICO — bought when insurance was unfashionable and it grew to dominate the partnership's returns, ironically dwarfing all his other net-net picks combined.",
    quote: "In the short run the market votes; in the long run it weighs.", quoteVerified: true,
    strength: "Codified a repeatable, teachable method",
    blindspot: "Net-nets barely exist in modern liquid markets",
    bookSlugs: ["intelligent-investor","security-analysis"],
  }),
  mk({
    slug: "lynch", name: "Peter Lynch", epithet: "The 10-Bagger Hunter", country: "USA", flag: "🇺🇸",
    era: "1977–1990 (Magellan Fund)", eraStart: 1970, categories: ["Growth","Value"], primary: "Growth",
    cagr: "~29% CAGR at Magellan 1977–1990 (approx.)", cagrNum: 29,
    bio: "Ran Fidelity Magellan to legendary performance by owning what he could see working in daily life.",
    principles: [
      "Invest in what you know and can explain to a 6th-grader",
      "Categorise stocks: slow growers, stalwarts, fast growers, cyclicals, turnarounds, asset plays",
      "Look for PEG ≤ 1 in the fast growers",
      "The best gains come from small, under-covered names",
      "Do the homework — earnings ultimately drive prices",
    ],
    avoids: ["Hot IPOs","Whisper stocks","Companies whose business he cannot draw on a napkin"],
    allocation: [{name:"Fast growers",value:40},{name:"Stalwarts",value:25},{name:"Cyclicals & turnarounds",value:20},{name:"Cash",value:15}],
    holdingPeriod: "2–5 years typical", concentration: "Wide (Magellan held 1000+ names)",
    framework: { name: "PEG ≤ 1", detail: "P/E divided by earnings growth rate; below 1 signals reasonable price for growth.",
      items: ["Estimate 3–5 yr EPS growth","Compute P/E ÷ growth","PEG ≤ 1 → cheap","PEG > 2 → expensive"] },
    caseStudy: "Lynch loaded up on Dunkin' Donuts after noticing crowded stores; a boring-but-visible growth story he understood. It became one of Magellan's memorable winners and defined his 'look around you' method.",
    quote: "Know what you own, and know why you own it.", quoteVerified: true,
    strength: "Making growth investing accessible to amateurs",
    blindspot: "Style struggles in narrow, mega-cap-led markets",
    bookSlugs: ["one-up","beating-street"],
  }),
  mk({
    slug: "fisher", name: "Philip Fisher", epithet: "The Scuttlebutt Investor", country: "USA", flag: "🇺🇸",
    era: "1931–1999", eraStart: 1930, categories: ["Growth"], primary: "Growth",
    cagr: "Exact partnership returns undisclosed; Motorola held 1955–2004 (illustrative)", cagrNum: 15,
    bio: "Pioneer of long-duration growth investing; taught Buffett the value of qualitative research (scuttlebutt).",
    principles: [
      "Talk to customers, suppliers, ex-employees before buying",
      "Own great businesses for decades",
      "Focus on R&D productivity and sales organisation quality",
      "Management integrity is non-negotiable",
      "Never sell the great compounder for a minor overvaluation",
    ],
    avoids: ["Frequent trading","Diversification for its own sake","Companies with weak sales culture"],
    allocation: [{name:"Growth equities",value:90},{name:"Cash",value:10}],
    holdingPeriod: "Multi-decade", concentration: "10–15 names",
    framework: { name: "15-Point Scuttlebutt Test", detail: "15 qualitative questions covering products, R&D, sales, margins, labour, integrity.",
      items: ["Products with runway of years?","R&D that pays for itself?","Sales org above peers?","Labour and executive relations sound?","Integrity beyond reproach?"] },
    caseStudy: "Fisher bought Motorola in 1955 and reportedly held it for the rest of his life, letting a single high-conviction growth compounder shape decades of returns.",
    quote: "The stock market is filled with people who know the price of everything and value of nothing.", quoteVerified: false,
    strength: "Qualitative research edge before it was fashionable",
    blindspot: "Extreme concentration risks slow reveals of management decay",
    bookSlugs: ["common-stocks"],
  }),
  mk({
    slug: "templeton", name: "John Templeton", epithet: "The Global Contrarian", country: "USA/Global", flag: "🌐",
    era: "1954–1992", eraStart: 1950, categories: ["Contrarian","Value"], primary: "Contrarian",
    cagr: "~15% CAGR Templeton Growth Fund (approx.)", cagrNum: 15,
    bio: "Pioneered global investing and contrarianism — bought at maximum pessimism, sold at maximum optimism.",
    principles: [
      "Buy at the point of maximum pessimism",
      "Search the world for bargains",
      "The four most dangerous words: 'this time it's different'",
      "Diversify by country, sector, and style",
      "Bull markets are born on pessimism, die on euphoria",
    ],
    avoids: ["Herd consensus","Home-country bias","Chasing momentum"],
    allocation: [{name:"US",value:30},{name:"Europe",value:25},{name:"EM & Asia",value:30},{name:"Cash",value:15}],
    holdingPeriod: "4–6 years", concentration: "Broad global",
    framework: { name: "Maximum Pessimism", detail: "Buy when news is worst and price implies extinction.",
      items: ["Is the sector universally hated?","Are surviving players cash-rich?","Is valuation < 10x normalised earnings?","Do you have a 5-year horizon?"] },
    caseStudy: "In 1939 Templeton borrowed money to buy 100 shares each of every NYSE stock trading below $1 — a bet on wartime recovery. Most survived and quadrupled within four years.",
    quote: "Bull markets are born on pessimism.", quoteVerified: true,
    strength: "Global scope decades before it was mainstream",
    blindspot: "Contrarian entries can be years early",
    bookSlugs: ["most-important-thing","intelligent-investor"],
  }),
  mk({
    slug: "mobius", name: "Mark Mobius", epithet: "Mr. Emerging Markets", country: "Germany/USA", flag: "🌏",
    era: "1987–present", eraStart: 1980, categories: ["Value","Contrarian"], primary: "Value",
    cagr: "Long-run EM equity returns (illustrative)", cagrNum: 12,
    bio: "Built Templeton Emerging Markets from a small fund into an EM investing institution.",
    principles: [
      "Boots on the ground: visit companies personally",
      "Corporate governance is the differentiator in EM",
      "Buy quality at a discount to developed-market peers",
      "Currency risk is part of the return equation",
      "Political shocks create opportunities",
    ],
    avoids: ["Uninvestable governance","Countries without rule of law","Illiquid micro-caps"],
    allocation: [{name:"EM equities",value:85},{name:"Cash / FX hedges",value:15}],
    holdingPeriod: "3–5 years", concentration: "Broad EM",
    framework: { name: "EM Quality-at-a-Discount", detail: "Screen for developed-market-like quality trading at EM discount.",
      items: ["ROE ≥ 15%","Debt/equity < 0.5","Independent board","Transparent related-party disclosures","P/E discount ≥ 30% vs DM peer"] },
    caseStudy: "Mobius championed Brazilian, Russian and Chinese equities in the 1990s when most Western investors ignored them, delivering strong long-run alpha through the EM growth cycle.",
    quote: "The best time to buy is when there's blood in the streets — even your own.", quoteVerified: false,
    strength: "Deep on-the-ground EM expertise",
    blindspot: "EM cycles can be brutal and long",
    bookSlugs: ["intelligent-investor"],
  }),
  mk({
    slug: "dalio", name: "Ray Dalio", epithet: "The Principles Macro", country: "USA", flag: "🇺🇸",
    era: "1975–present (Bridgewater)", eraStart: 1970, categories: ["Macro"], primary: "Macro",
    cagr: "Pure Alpha ~12% CAGR (approx., long-run)", cagrNum: 12,
    bio: "Built Bridgewater into the world's largest hedge fund on principles-based macro and the All Weather diversification model.",
    principles: [
      "Diversify across environments, not just assets",
      "Truth + radical transparency beats politeness",
      "Understand the machine: growth × inflation regimes",
      "Balance risk, not dollars, across holdings",
      "Bet on many uncorrelated return streams",
    ],
    avoids: ["Home-country dogma","Concentration in one asset class","Ignoring debt cycles"],
    allocation: [{name:"Long bonds",value:40},{name:"Equities",value:30},{name:"Commodities",value:15},{name:"Gold",value:7.5},{name:"Inflation-linked",value:7.5}],
    holdingPeriod: "Regime-dependent", concentration: "Balanced by risk contribution",
    framework: { name: "All Weather", detail: "Balance risk across four macro regimes: rising/falling growth × rising/falling inflation.",
      items: ["Rising growth → equities, EM debt","Falling growth → nominal bonds","Rising inflation → commodities, IL bonds, gold","Falling inflation → bonds, equities"] },
    caseStudy: "Dalio built the All Weather portfolio in the 1990s after realising Bridgewater's own pension needed a mix that survived any decade. It handled the 2008 crisis materially better than 60/40 benchmarks.",
    quote: "He who lives by the crystal ball is destined to eat glass.", quoteVerified: true,
    strength: "Systematising macro into replicable rules",
    blindspot: "Complex models can under-perform simple 60/40 for long stretches",
    bookSlugs: ["principles","alchemy-finance"],
  }),
  mk({
    slug: "soros", name: "George Soros", epithet: "The Man Who Broke the Bank of England", country: "USA/Hungary", flag: "🇭🇺",
    era: "1969–2011", eraStart: 1970, categories: ["Macro","Contrarian"], primary: "Macro",
    cagr: "~20% CAGR Quantum Fund (approx.)", cagrNum: 20,
    bio: "Ran Quantum Fund with reflexivity theory — price and fundamentals feed back on each other.",
    principles: [
      "Reflexivity: prices influence fundamentals, not just reflect them",
      "Bet big when the risk/reward is asymmetric",
      "Cut losers fast; ride winners hard",
      "Being right or wrong matters less than size when right",
      "Look for regime-change catalysts, not steady state",
    ],
    avoids: ["Sizing small when the setup is obvious","Ideological rigidity","Ignoring political signals"],
    allocation: [{name:"FX & rates macro",value:50},{name:"Equity long/short",value:30},{name:"Commodities",value:10},{name:"Cash",value:10}],
    holdingPeriod: "Weeks to years, catalyst-driven", concentration: "Very concentrated when convicted",
    framework: { name: "Reflexivity Loop", detail: "Identify a self-reinforcing loop between perception and reality.",
      items: ["Prevailing bias","Trend it reinforces","Catalyst confirming bias","Point of exhaustion","Reversal signal"] },
    caseStudy: "In 1992 Soros shorted the British pound with ~$10bn notional, betting the UK would exit the ERM. When it did, Quantum reportedly made ~$1bn in a day and the trade defined modern macro speculation.",
    quote: "It's not whether you're right or wrong — but how much when right.", quoteVerified: true,
    strength: "Asymmetric position sizing on macro catalysts",
    blindspot: "Highly personality-driven; hard to replicate",
    bookSlugs: ["alchemy-finance","market-wizards"],
  }),
  mk({
    slug: "druckenmiller", name: "Stanley Druckenmiller", epithet: "The Concentrated Macro", country: "USA", flag: "🇺🇸",
    era: "1981–present", eraStart: 1980, categories: ["Macro"], primary: "Macro",
    cagr: "~30% CAGR Duquesne (approx., 1986–2010, no losing year)", cagrNum: 30,
    bio: "Ran Duquesne with an unbroken record of positive years, combining top-down macro with concentrated position sizing.",
    principles: [
      "Preserve capital first — no losing years is the goal",
      "When you see it, bet the ranch",
      "Central-bank liquidity drives markets more than earnings",
      "Ride winners; don't top-tick",
      "Bonds tell you more than equities do",
    ],
    avoids: ["Diversifying great ideas","Fighting the Fed","Overtrading in low-conviction periods"],
    allocation: [{name:"Bonds / rates",value:35},{name:"Equities (concentrated)",value:35},{name:"Currencies",value:20},{name:"Cash",value:10}],
    holdingPeriod: "Months to years", concentration: "Top few positions dominate",
    framework: { name: "Fed-Liquidity Lens", detail: "Track central-bank balance sheet and rate cycle before any equity call.",
      items: ["Direction of policy rates","Balance-sheet expansion or QT","Real yields trend","Dollar direction","Credit spreads"] },
    caseStudy: "In 1999 Druckenmiller reluctantly bought late-cycle tech, then sold, then rebought at the peak — losing billions. The lesson he tells publicly: even legends succumb to FOMO if they abandon their discipline.",
    quote: "Never, ever invest in the present.", quoteVerified: true,
    strength: "Ruthless capital preservation and sizing",
    blindspot: "Very personality-dependent; hard to systematise",
    bookSlugs: ["market-wizards","principles"],
  }),
  mk({
    slug: "tudor-jones", name: "Paul Tudor Jones", epithet: "The Risk Manager's Trader", country: "USA", flag: "🇺🇸",
    era: "1980–present", eraStart: 1980, categories: ["Macro","Trend"], primary: "Trend",
    cagr: "~19% CAGR long-run (approx.)", cagrNum: 19,
    bio: "Global macro trader famous for shorting the 1987 crash and for uncompromising risk management.",
    principles: [
      "Play great defence, not great offence",
      "Never risk more than you can lose gracefully",
      "The trend is your friend until the end",
      "Trade the price action, not your opinion",
      "Cut the losers; let winners run",
    ],
    avoids: ["Averaging into losers","Falling in love with a thesis","Trading tired or emotional"],
    allocation: [{name:"Macro trades",value:60},{name:"Trend follow",value:25},{name:"Cash / dry powder",value:15}],
    holdingPeriod: "Days to months", concentration: "Trade-by-trade",
    framework: { name: "5:1 Risk/Reward Rule", detail: "Only take trades where potential reward is ≥ 5× the risk.",
      items: ["Define entry, stop, target","Compute R/R","Reject if < 5:1","Predefine max daily loss","Journal the trade"] },
    caseStudy: "PTJ correctly forecast the 1987 crash using Elliott-wave analogues and made a fortune while most of Wall Street burned — one of the defining trades of modern macro.",
    quote: "The most important rule is to play great defence.", quoteVerified: true,
    strength: "Disciplined risk management",
    blindspot: "Style requires screen time few can sustain",
    bookSlugs: ["market-wizards","reminiscences"],
  }),
  mk({
    slug: "simons", name: "Jim Simons", epithet: "The Quant King", country: "USA", flag: "🇺🇸",
    era: "1982–2010 (Renaissance)", eraStart: 1980, categories: ["Quant"], primary: "Quant",
    cagr: "Medallion Fund ~39% net CAGR 1988–2018 (approx./famous)", cagrNum: 39,
    bio: "Mathematician who built Renaissance Technologies' Medallion Fund into arguably the greatest track record in finance.",
    principles: [
      "Trust the model, not the story",
      "Hire scientists, not MBAs",
      "Data pre-processing is 80% of the edge",
      "Diversify across thousands of small edges",
      "Never let anyone override the system in a drawdown",
    ],
    avoids: ["Discretionary override","Storytelling","Naive extrapolation"],
    allocation: [{name:"Short-horizon signals",value:70},{name:"Medium-horizon signals",value:25},{name:"Cash",value:5}],
    holdingPeriod: "Seconds to weeks", concentration: "Thousands of tiny positions",
    framework: { name: "Statistical Arbitrage", detail: "Exploit tiny, replicable statistical anomalies at scale.",
      items: ["Clean, aligned datasets","Signal with positive t-stat OOS","Position sized by signal & risk","Costs and slippage modelled","Continuous retraining"] },
    caseStudy: "Renaissance's Medallion Fund reportedly compounded at ~39% net for three decades — impossible to attribute to any single trade, and closed to outside capital for a reason.",
    quote: "The advantage is process, not prediction.", quoteVerified: false,
    strength: "Institutional-grade research infrastructure",
    blindspot: "Not replicable at home; scale is capped",
    bookSlugs: ["man-for-all-markets"],
  }),
  mk({
    slug: "thorp", name: "Ed Thorp", epithet: "The Quant Grandfather", country: "USA", flag: "🇺🇸",
    era: "1969–present", eraStart: 1960, categories: ["Quant"], primary: "Quant",
    cagr: "Princeton-Newport ~19% CAGR (approx., 1969–1988)", cagrNum: 19,
    bio: "Math professor who beat blackjack, then invented modern statistical arbitrage.",
    principles: [
      "Only bet when the math is in your favour",
      "Kelly criterion controls position size",
      "Small edges compound into fortunes",
      "Verify with data, not intuition",
      "Preserve capital during losing streaks",
    ],
    avoids: ["Sizing above Kelly","Gambler's fallacy","Guessing without a model"],
    allocation: [{name:"Statistical arb",value:70},{name:"Convertible arb",value:20},{name:"Cash",value:10}],
    holdingPeriod: "Days to months", concentration: "Many small edges",
    framework: { name: "Kelly Criterion", detail: "Optimal bet fraction = edge / odds.",
      items: ["Estimate win probability p","Estimate payoff b","f* = (bp − (1−p)) / b","Bet fraction of bankroll = f*","Halve it in real life for safety"] },
    caseStudy: "Thorp turned card-counting into a hedge fund by realising the same probabilistic edge existed in options mispricing — codified in Beat the Market and later Beat the Dealer.",
    quote: "Only bet when the math is on your side.", quoteVerified: false,
    strength: "Rigorous probabilistic mindset",
    blindspot: "Requires infrastructure most investors lack",
    bookSlugs: ["man-for-all-markets"],
  }),
  mk({
    slug: "marks", name: "Howard Marks", epithet: "The Cycle Whisperer", country: "USA", flag: "🇺🇸",
    era: "1995–present (Oaktree)", eraStart: 1990, categories: ["Value","Contrarian"], primary: "Value",
    cagr: "Distressed-debt long-run ~15%+ CAGR (approx.)", cagrNum: 15,
    bio: "Co-founded Oaktree Capital; famous for memos on risk, cycles and second-level thinking.",
    principles: [
      "You can't predict, but you can prepare",
      "It's not what you buy, it's what you pay",
      "Second-level thinking beats first-level consensus",
      "Cycles always come — plan for the down move",
      "Risk is the probability of permanent loss, not volatility",
    ],
    avoids: ["Chasing momentum","Ignoring credit cycle","Confusing volatility with risk"],
    allocation: [{name:"Distressed debt",value:60},{name:"High yield",value:25},{name:"Cash",value:15}],
    holdingPeriod: "3–7 years", concentration: "Diversified across issuers",
    framework: { name: "The Cycle Thermometer", detail: "Assess where the cycle stands across 6 signals.",
      items: ["Valuations","Sentiment","Credit availability","IPO froth","Prevailing narratives","Yield spreads"] },
    caseStudy: "Oaktree deployed record capital into distressed debt in late 2008 as spreads blew out, harvesting outsized returns as the credit cycle turned in 2009–2010.",
    quote: "Being too far ahead of your time is indistinguishable from being wrong.", quoteVerified: true,
    strength: "Cycle awareness and communication",
    blindspot: "Cautious posture can underperform in long bull runs",
    bookSlugs: ["most-important-thing"],
  }),
  mk({
    slug: "klarman", name: "Seth Klarman", epithet: "The Modern Graham", country: "USA", flag: "🇺🇸",
    era: "1982–present (Baupost)", eraStart: 1980, categories: ["Value","Contrarian"], primary: "Value",
    cagr: "~15%+ CAGR long-run (approx.)", cagrNum: 15,
    bio: "Runs Baupost Group with deep value discipline and willingness to hold large cash balances until fat pitches appear.",
    principles: [
      "Margin of safety above all",
      "Cash is a strategic weapon, not a drag",
      "Absolute returns beat relative returns",
      "Look where others cannot or will not",
      "Focus on downside first, then upside",
    ],
    avoids: ["Forced deployment","Style boxes","Owning what everyone else owns"],
    allocation: [{name:"Deep value equities",value:45},{name:"Distressed / special sit",value:25},{name:"Real estate",value:10},{name:"Cash",value:20}],
    holdingPeriod: "3–5 years", concentration: "Concentrated in best ideas",
    framework: { name: "Margin of Safety Framework", detail: "Buy only when conservative intrinsic value is materially above price.",
      items: ["Conservative valuation","Stress-test downside","Discount ≥ 30–40%","Catalyst identified","Position sized to survive being early"] },
    caseStudy: "Baupost bought Puerto Rico general obligation bonds during the 2015 crisis when most funds were fleeing — a controversial deep-value bet on legal restructuring value.",
    quote: "Only when you sell do you know what price to buy at.", quoteVerified: false,
    strength: "Patience and cash discipline",
    blindspot: "Cash drag in raging bull markets",
    bookSlugs: ["margin-of-safety","intelligent-investor","security-analysis"],
  }),
  mk({
    slug: "greenblatt", name: "Joel Greenblatt", epithet: "The Special-Situations Professor", country: "USA", flag: "🇺🇸",
    era: "1985–present (Gotham)", eraStart: 1980, categories: ["Value","Quant"], primary: "Value",
    cagr: "Gotham ~40% CAGR 1985–1994 (approx., closed to outside capital)", cagrNum: 40,
    bio: "Runs Gotham Capital; teaches at Columbia; created the Magic Formula.",
    principles: [
      "Buy good businesses at cheap prices",
      "Spin-offs and special situations are structurally mispriced",
      "Simple rules, systematically applied, beat clever ones",
      "Concentrate in your best 5–8 ideas as an amateur",
      "Volatility is the price paid for outperformance",
    ],
    avoids: ["Chasing narratives","Over-diversification","Selling winners early"],
    allocation: [{name:"Special sit / spin-offs",value:50},{name:"Cheap quality equity",value:40},{name:"Cash",value:10}],
    holdingPeriod: "1–3 years", concentration: "5–10 names historically",
    framework: { name: "Magic Formula", detail: "Rank stocks by earnings yield AND return on capital, buy top decile.",
      items: ["Earnings Yield = EBIT / EV","ROC = EBIT / (NWC + Net PP&E)","Rank both, sum ranks","Buy top 20–30","Hold 12 months, rebalance"] },
    caseStudy: "Greenblatt famously wrote about the Marriott spin-off, where the split into a real-estate REIT and operating company created a mispricing exploited by patient special-sit investors.",
    quote: "Cheap and good beats expensive and great.", quoteVerified: false,
    strength: "Turning value into a system amateurs can follow",
    blindspot: "Magic Formula endures long droughts",
    bookSlugs: ["stock-market-genius","little-book-beats"],
  }),
  mk({
    slug: "pabrai", name: "Mohnish Pabrai", epithet: "The Cloner", country: "USA/India", flag: "🇮🇳",
    era: "1999–present", eraStart: 1990, categories: ["Value"], primary: "Value",
    cagr: "Pabrai Funds ~15%+ CAGR long-run (approx.)", cagrNum: 15,
    bio: "Runs Pabrai Investment Funds; openly clones best ideas from investors he respects and uses a strict checklist.",
    principles: [
      "Heads I win, tails I don't lose much",
      "Copy shamelessly from great investors",
      "Concentrate in fat pitches",
      "Low downside first, upside second",
      "Do less, but with total conviction",
    ],
    avoids: ["Original thinking for its own sake","Excessive activity","Complexity"],
    allocation: [{name:"Concentrated value",value:80},{name:"Cash",value:20}],
    holdingPeriod: "3–5 years", concentration: "Top 5 ≈ 60%+",
    framework: { name: "Dhandho Checklist", detail: "A pre-purchase mistake-catcher inspired by aviation checklists.",
      items: ["Simple, understandable business","Durable moat","Strong balance sheet","Owner-oriented management","≥ 50% margin of safety"] },
    caseStudy: "Pabrai bought Frontline Ltd during the 2002 shipping-rate collapse at a fraction of scrap value — a low-risk, high-uncertainty bet that multiplied several-fold within two years.",
    quote: "Heads I win, tails I don't lose much.", quoteVerified: true,
    strength: "Discipline of a written checklist",
    blindspot: "Concentration hurts when a clone thesis breaks",
    bookSlugs: ["dhandho","poor-charlies-almanack"],
  }),
  mk({
    slug: "li-lu", name: "Li Lu", epithet: "The China Value Investor", country: "China/USA", flag: "🇨🇳",
    era: "1997–present (Himalaya Capital)", eraStart: 1990, categories: ["Value","Growth"], primary: "Value",
    cagr: "~26% CAGR Himalaya (approx.)", cagrNum: 26,
    bio: "Only outside manager Munger openly entrusted with capital; specialises in Chinese and Asian value.",
    principles: [
      "Stay within a narrow circle of competence",
      "Concentrate in a handful of great businesses",
      "Long-term thinking beats short-term cleverness",
      "Cultural fluency is an edge",
      "Compound the character of the investor",
    ],
    avoids: ["Businesses outside his circle","Momentum","Governance red flags"],
    allocation: [{name:"Asia equities",value:75},{name:"Cash",value:25}],
    holdingPeriod: "5–10 years+", concentration: "5–6 core positions",
    framework: { name: "Circle-of-Competence Discipline", detail: "Own only businesses whose next 10 years you can predict.",
      items: ["Do I understand the industry cycle?","Do I trust management?","Is moat widening?","Is 10-yr FCF forecastable?","Is price sensible vs FCF?"] },
    caseStudy: "Li Lu's early investment in BYD (later co-invested with Berkshire/Munger) is a canonical example of concentrated, patient EM value investing.",
    quote: "Investing is the last liberal art.", quoteVerified: true,
    strength: "China insight and patience",
    blindspot: "China governance risk out of investors' control",
    bookSlugs: ["poor-charlies-almanack","intelligent-investor"],
  }),
  mk({
    slug: "spier", name: "Guy Spier", epithet: "The Patient Value Investor", country: "Switzerland", flag: "🇨🇭",
    era: "1997–present", eraStart: 1990, categories: ["Value","Behavioral"], primary: "Value",
    cagr: "Aquamarine Fund ~9%+ CAGR (approx.)", cagrNum: 10,
    bio: "Runs Aquamarine Fund from Zurich; famous for a written checklist and behavioural rewiring inspired by Buffett/Munger.",
    principles: [
      "Curate your environment for good decisions",
      "Use a checklist for every purchase",
      "Don't check prices intraday",
      "Compound reputation and relationships",
      "Move to a city that supports your temperament",
    ],
    avoids: ["Noise and CNBC","Short-term thinking","Prestige-driven trades"],
    allocation: [{name:"Long-term value equities",value:85},{name:"Cash",value:15}],
    holdingPeriod: "5–10 years", concentration: "10–15 names",
    framework: { name: "Investor's Checklist", detail: "A written checklist inspired by aviation safety.",
      items: ["Do I understand this business?","Is management aligned?","What is downside case?","Am I anchored to entry price?","Would Buffett approve?"] },
    caseStudy: "Spier documents how he moved from New York to Zurich to escape hyper-competitive short-termism, arguing the environmental change compounded his returns as much as any single stock pick.",
    quote: "Compound reputation the same way you compound money.", quoteVerified: false,
    strength: "Self-awareness and process discipline",
    blindspot: "Modest raw returns vs peers",
    bookSlugs: ["dhandho","poor-charlies-almanack","psychology-money"],
  }),
  mk({
    slug: "burry", name: "Michael Burry", epithet: "The Big Short", country: "USA", flag: "🇺🇸",
    era: "2000–present (Scion)", eraStart: 2000, categories: ["Contrarian","Value"], primary: "Contrarian",
    cagr: "Scion long-run difficult to attribute; famous Big Short win 2007–08", cagrNum: 15,
    bio: "Doctor-turned-hedge-fund manager who shorted subprime before 2008 and continues to make contrarian macro-value bets.",
    principles: [
      "Do original research others aren't willing to do",
      "Ignore the crowd, especially when uncomfortable",
      "Small-cap value screens still work",
      "Tail risks matter more than they seem",
      "Sit on ideas until price meets thesis",
    ],
    avoids: ["Consensus trades","Crowded factor bets","Ignoring balance sheets"],
    allocation: [{name:"Concentrated value / macro shorts",value:80},{name:"Cash",value:20}],
    holdingPeriod: "1–3 years", concentration: "Very concentrated",
    framework: { name: "Deep-Research Contrarianism", detail: "Buy what the crowd hates once the numbers demand it.",
      items: ["What is universally hated?","Does data actually justify hate?","Is downside floored by asset value?","Is a catalyst in view?","Can I hold through pain?"] },
    caseStudy: "Burry read subprime mortgage documents in 2005, correctly identifying that many pools would default. He bought CDS on them before others saw it, making Scion's investors ~500%.",
    quote: "You have to say no to a lot of good ideas to say yes to a great one.", quoteVerified: false,
    strength: "Independent thinking and primary-source research",
    blindspot: "Early calls, communication style creates career risk",
    bookSlugs: ["black-swan","intelligent-investor"],
  }),
  mk({
    slug: "ackman", name: "Bill Ackman", epithet: "The Concentrated Activist", country: "USA", flag: "🇺🇸",
    era: "2004–present (Pershing Square)", eraStart: 2000, categories: ["Activist","Value"], primary: "Activist",
    cagr: "~15%+ CAGR Pershing Square long-run (approx.)", cagrNum: 15,
    bio: "Runs Pershing Square with a concentrated activist / high-quality-business playbook.",
    principles: [
      "Own a small number of great businesses",
      "Push management for value-unlocking action when needed",
      "Hedge tail risk cheaply when priced attractively",
      "Long horizons on quality; short horizons on tactical hedges",
      "Communicate the thesis publicly",
    ],
    avoids: ["Over-diversification","Consensus mega-caps","Value traps"],
    allocation: [{name:"Concentrated quality",value:80},{name:"Tactical hedges",value:10},{name:"Cash",value:10}],
    holdingPeriod: "3–7 years for cores", concentration: "8–12 positions",
    framework: { name: "Activist Quality Filter", detail: "Only agitate on businesses worth owning even without activism.",
      items: ["Great business economics","Underperforming vs peers","Path to unlock value","Board willing to engage","Public thesis defensible"] },
    caseStudy: "Ackman famously bought CDS on investment-grade credit in early 2020, turning a small hedge into ~$2.6bn as COVID hit — enabling him to redeploy into quality equities near lows.",
    quote: "Do the work, own quality, act decisively.", quoteVerified: false,
    strength: "Willingness to act and communicate publicly",
    blindspot: "Public spats can amplify losses (Herbalife)",
    bookSlugs: ["essays-buffett","most-important-thing"],
  }),
  mk({
    slug: "icahn", name: "Carl Icahn", epithet: "The Corporate Raider", country: "USA", flag: "🇺🇸",
    era: "1968–present", eraStart: 1960, categories: ["Activist"], primary: "Activist",
    cagr: "Icahn Enterprises long-run difficult to attribute; personal fortune multi-billion", cagrNum: 15,
    bio: "Pioneer of shareholder activism; forces boards to unlock value or return capital.",
    principles: [
      "The best returns come from forcing change",
      "Vote your shares like an owner",
      "Cash on the balance sheet belongs to shareholders",
      "Boards need pressure, not applause",
      "Never fall in love with a position",
    ],
    avoids: ["Passive management","Empire-building CEOs","Cross-shareholdings that entrench"],
    allocation: [{name:"Activist equity",value:70},{name:"Special situations",value:20},{name:"Cash",value:10}],
    holdingPeriod: "1–4 years", concentration: "Concentrated",
    framework: { name: "Corporate Value Unlock", detail: "Identify assets whose sum-of-parts vastly exceeds current market cap.",
      items: ["Break-up value > market cap?","Non-core assets to divest?","Excess cash to return?","Weak board / poor governance?","Willing catalyst path?"] },
    caseStudy: "Icahn's TWA takeover in the late 1980s epitomised the raider era — extracting value shareholders never would have seen without activism, though controversially for employees.",
    quote: "When most people are afraid to buy, you should buy.", quoteVerified: false,
    strength: "Willingness to fight",
    blindspot: "Legacy reputation cuts both ways",
    bookSlugs: ["outsiders"],
  }),
  mk({
    slug: "einhorn", name: "David Einhorn", epithet: "The Long/Short Researcher", country: "USA", flag: "🇺🇸",
    era: "1996–present (Greenlight)", eraStart: 1990, categories: ["Value","Activist"], primary: "Value",
    cagr: "~12%+ CAGR long-run Greenlight (approx.)", cagrNum: 12,
    bio: "Runs Greenlight Capital with a research-driven long/short value playbook; famous Lehman short.",
    principles: [
      "Do the accounting work others skip",
      "Short accounting frauds and structurally challenged businesses",
      "Long undervalued cash generators",
      "Communicate the thesis to force market recognition",
      "Patience through years of underperformance",
    ],
    avoids: ["Momentum longs","Crowded shorts","Consensus tech valuations"],
    allocation: [{name:"Long value",value:60},{name:"Short frauds/structural",value:25},{name:"Cash",value:15}],
    holdingPeriod: "1–3 years", concentration: "Concentrated on both sides",
    framework: { name: "Forensic Long/Short", detail: "Read 10-Ks like an auditor before sizing anything.",
      items: ["Cash flow vs earnings","Working-capital anomalies","Off-balance-sheet items","Insider selling","Accounting policy changes"] },
    caseStudy: "Einhorn publicly warned about Lehman's balance sheet months before it collapsed in 2008, delivering the archetypal example of forensic short-selling.",
    quote: "You either understand the accounting or you're guessing.", quoteVerified: false,
    strength: "Forensic accounting skill",
    blindspot: "Value style can lag for years",
    bookSlugs: ["security-analysis","intelligent-investor"],
  }),
  mk({
    slug: "loeb", name: "Daniel Loeb", epithet: "The Activist Letter Writer", country: "USA", flag: "🇺🇸",
    era: "1995–present (Third Point)", eraStart: 1990, categories: ["Activist","Value"], primary: "Activist",
    cagr: "~15%+ CAGR long-run Third Point (approx.)", cagrNum: 15,
    bio: "Runs Third Point with event-driven activism, famous for pointed letters to boards.",
    principles: [
      "Catalysts, not stories, create returns",
      "Public pressure works when data is on your side",
      "Own operators, not empire-builders",
      "Diversify catalysts, concentrate conviction",
      "Move fast when the setup emerges",
    ],
    avoids: ["Passive long-only","Weak governance","No catalyst path"],
    allocation: [{name:"Event-driven equity",value:60},{name:"Credit",value:20},{name:"Cash",value:20}],
    holdingPeriod: "6–24 months", concentration: "Concentrated by catalyst",
    framework: { name: "Catalyst Map", detail: "Every position tied to an identifiable catalyst.",
      items: ["Spin-off / split","Management change","Balance-sheet re-cap","M&A / activism","Regulatory change"] },
    caseStudy: "Third Point pushed for change at Yahoo in the early 2010s, precipitating a management overhaul that eventually monetised Alibaba stakes for shareholders.",
    quote: "Catalysts pay you; narratives cost you.", quoteVerified: false,
    strength: "Event-driven analysis",
    blindspot: "Public activism can backfire",
    bookSlugs: ["stock-market-genius"],
  }),
  mk({
    slug: "griffin", name: "Ken Griffin", epithet: "The Multi-Strategy Machine", country: "USA", flag: "🇺🇸",
    era: "1990–present (Citadel)", eraStart: 1990, categories: ["Quant","Macro"], primary: "Quant",
    cagr: "Citadel Wellington long-run ~19%+ CAGR (approx.)", cagrNum: 19,
    bio: "Founded Citadel while at Harvard; built a global multi-strategy hedge fund and top market-maker.",
    principles: [
      "Institutional risk management beats stars",
      "Diversify across many uncorrelated pods",
      "Technology is infrastructure, not a nice-to-have",
      "Attract and retain top talent aggressively",
      "Kill losing books quickly",
    ],
    avoids: ["Individual star risk","Style concentration","Under-investment in tech"],
    allocation: [{name:"Equities pods",value:35},{name:"Fixed income & macro",value:25},{name:"Commodities",value:15},{name:"Credit",value:15},{name:"Cash",value:10}],
    holdingPeriod: "Per pod (days to years)", concentration: "Diversified across pods",
    framework: { name: "Pod Risk Model", detail: "Each pod has a hard drawdown limit; capital reallocated to winners.",
      items: ["Pre-defined stop per pod","Daily risk aggregation","Kill switch on breach","Reallocate to compounders","Blind-eye reviews forbidden"] },
    caseStudy: "Citadel navigated 2008 near-fatally then rebuilt into one of the most consistent multi-strat platforms in the world by hardening risk systems.",
    quote: "Discipline is the only durable edge.", quoteVerified: false,
    strength: "Institutionalised risk & tech",
    blindspot: "High turnover, personality-heavy culture",
    bookSlugs: ["market-wizards"],
  }),
  mk({
    slug: "bogle", name: "John Bogle", epithet: "The Father of Indexing", country: "USA", flag: "🇺🇸",
    era: "1975–2019 (Vanguard)", eraStart: 1970, categories: ["Passive"], primary: "Passive",
    cagr: "S&P 500 long-run ~10% CAGR (illustrative)", cagrNum: 10,
    bio: "Founded Vanguard and popularised the low-cost index fund, arguably the biggest gift ever given to retail investors.",
    principles: [
      "Costs matter more than skill for most",
      "Own the whole market, forever",
      "Simplicity beats complexity",
      "Time in the market beats timing",
      "Reversion to the mean is undefeated",
    ],
    avoids: ["Active management fees","Trading","Complex products"],
    allocation: [{name:"Total stock index",value:60},{name:"Total bond index",value:40}],
    holdingPeriod: "Decades", concentration: "Broad market",
    framework: { name: "Cost Matters Hypothesis", detail: "Gross return − cost = net return; costs compound negatively.",
      items: ["Prefer ≤ 0.10% expense ratios","Avoid load funds","Auto-rebalance yearly","Automate SIP","Ignore predictions"] },
    caseStudy: "Bogle launched the first index fund in 1976 to widespread ridicule; today Vanguard manages trillions and has arguably transferred trillions of dollars from Wall Street to Main Street.",
    quote: "Don't look for the needle in the haystack — buy the haystack.", quoteVerified: true,
    strength: "Democratising investing",
    blindspot: "Cannot beat the market by construction",
    bookSlugs: ["little-book-common-sense","random-walk"],
  }),
  mk({
    slug: "malkiel", name: "Burton Malkiel", epithet: "The Random Walk Professor", country: "USA", flag: "🇺🇸",
    era: "1973–present", eraStart: 1970, categories: ["Passive"], primary: "Passive",
    cagr: "S&P 500 long-run (illustrative)", cagrNum: 10,
    bio: "Princeton economist whose Random Walk Down Wall Street championed efficient markets and indexing to retail investors.",
    principles: [
      "Prices reflect available information",
      "Broad diversification is a free lunch",
      "Rebalance regularly, don't market-time",
      "Fees are the enemy",
      "Behaviour, not stock picks, drives outcomes",
    ],
    avoids: ["Chart-only trading","Fads","Concentrated bets without edge"],
    allocation: [{name:"Global equity index",value:55},{name:"Bonds",value:35},{name:"REITs",value:10}],
    holdingPeriod: "Decades", concentration: "Broad",
    framework: { name: "Lifecycle Allocation", detail: "Equity weight shrinks as retirement approaches.",
      items: ["Age 30 → 70/30","Age 45 → 60/40","Age 55 → 50/40/10","Age 65 → 40/50/10","Rebalance annually"] },
    caseStudy: "Malkiel argued that a blindfolded monkey throwing darts at the WSJ would match professional stock pickers — an idea empirically supported by decades of SPIVA reports.",
    quote: "Investors would do far better buying and holding an index fund.", quoteVerified: true,
    strength: "Public advocacy for evidence-based investing",
    blindspot: "Underplays the tails at both ends of skill",
    bookSlugs: ["random-walk","little-book-common-sense"],
  }),
  mk({
    slug: "livermore", name: "Jesse Livermore", epithet: "The Boy Plunger", country: "USA", flag: "🇺🇸",
    era: "1900–1934", eraStart: 1900, categories: ["Trend"], primary: "Trend",
    cagr: "Multiple boom-bust cycles; peak wealth vs bankruptcies", cagrNum: 0,
    bio: "Iconic tape reader whose life is a cautionary tale about leverage and psychology in trend-following.",
    principles: [
      "The market is never wrong; opinions often are",
      "Trend follow, don't top-tick",
      "Cut losses immediately",
      "Position size by conviction and price action",
      "Sit tight when right",
    ],
    avoids: ["Averaging losers","Trading tired or emotional","Ignoring stop losses"],
    allocation: [{name:"Speculative long/short",value:100}],
    holdingPeriod: "Days to months", concentration: "All-in when convicted",
    framework: { name: "Pivotal Point Trading", detail: "Enter only when a stock breaks past a defined pivotal price.",
      items: ["Identify base pattern","Wait for breakout","Enter on confirmation","Trail stop below pivots","Add on strength"] },
    caseStudy: "Livermore shorted the 1929 crash and reportedly made $100m — then lost it all through leverage, poor discipline, and mental illness. A permanent lesson in risk management.",
    quote: "The market is never wrong; opinions often are.", quoteVerified: true,
    strength: "Trend & tape-reading intuition",
    blindspot: "Leverage without survival math",
    bookSlugs: ["reminiscences"],
  }),
  mk({
    slug: "taleb", name: "Nassim Nicholas Taleb", epithet: "The Black Swan", country: "USA/Lebanon", flag: "🇱🇧",
    era: "1990s–present", eraStart: 1990, categories: ["Contrarian","Macro"], primary: "Contrarian",
    cagr: "Barbell tail hedges plus safe assets (asymmetric)", cagrNum: 0,
    bio: "Former options trader turned philosopher of uncertainty; champion of antifragility and tail-risk hedging.",
    principles: [
      "Barbell: extreme safety on one end, tiny convex bets on the other",
      "Avoid the middle — moderate risk with fat tails is worst",
      "Antifragility > robustness > fragility",
      "Absence of evidence ≠ evidence of absence",
      "Skin in the game aligns incentives",
    ],
    avoids: ["Naive VaR models","Middle-risk allocations","Forecast-driven strategies"],
    allocation: [{name:"Cash / T-bills",value:85},{name:"Deep OTM options / tail hedges",value:15}],
    holdingPeriod: "Barbell held indefinitely", concentration: "Bimodal",
    framework: { name: "Barbell Strategy", detail: "Combine ultra-safe assets with a small tail-risk book.",
      items: ["80–90% in T-bills / cash","5–15% in convex tail options","Never in the middle","Rebalance yearly","Never sell insurance you can't afford to pay out"] },
    caseStudy: "Taleb-influenced Universa reportedly generated ~4000% returns in the March 2020 COVID crash on a small book — the empirical case for tail hedging.",
    quote: "Absence of evidence is not evidence of absence.", quoteVerified: true,
    strength: "Framework for tail risk",
    blindspot: "Bleeds premium in calm markets",
    bookSlugs: ["black-swan","fooled-randomness"],
  }),
  mk({
    slug: "berkowitz", name: "Bruce Berkowitz", epithet: "The Concentrated Contrarian", country: "USA", flag: "🇺🇸",
    era: "1999–present (Fairholme)", eraStart: 1990, categories: ["Value","Contrarian"], primary: "Value",
    cagr: "~10%+ CAGR long-run Fairholme (approx., volatile)", cagrNum: 10,
    bio: "Runs Fairholme with a highly concentrated deep-value approach; known for large financial-sector bets.",
    principles: [
      "Ignore benchmarks",
      "Buy hated, financially strong businesses",
      "Concentrate in best ideas",
      "Do not trade around positions",
      "Give thesis 3–5 years to work",
    ],
    avoids: ["Diversification for its own sake","Style boxes","Consensus trades"],
    allocation: [{name:"Deep-value concentrated",value:90},{name:"Cash",value:10}],
    holdingPeriod: "3–7 years", concentration: "Top 5 ≈ 80%",
    framework: { name: "Ignore the Crowd", detail: "Buy what the crowd cannot even discuss without emotion.",
      items: ["Is it universally hated?","Is downside floored by book value?","Does management have skin in the game?","Are cash flows durable?","Am I willing to look wrong for years?"] },
    caseStudy: "Berkowitz built massive positions in AIG and Bank of America post-2008 when the market feared they were uninvestable — a controversial but ultimately profitable deep-value bet.",
    quote: "You have to be willing to look wrong for years.", quoteVerified: false,
    strength: "Conviction under pressure",
    blindspot: "Concentration breeds huge drawdowns",
    bookSlugs: ["outsiders","most-important-thing"],
  }),

  // ---------- INDIA ICONS ----------
  mk({
    slug: "jhunjhunwala", name: "Rakesh Jhunjhunwala", epithet: "India's Big Bull", country: "India", flag: "🇮🇳",
    era: "1985–2022", eraStart: 1980, categories: ["Growth","India"], primary: "India",
    cagr: "Turned ~₹5,000 into ~₹40,000 cr fortune (approx./widely reported)", cagrNum: 30,
    bio: "Turned a tiny stake into one of India's largest personal fortunes with concentrated conviction on quality growth.",
    principles: [
      "India is a multi-decade compounding story",
      "Big returns come from patience with quality",
      "Concentrate in conviction bets",
      "Emotional discipline beats intelligence",
      "Ride winners, don't book profits early",
    ],
    avoids: ["Frequent portfolio churn","Ignoring management quality","Chasing IPO froth"],
    allocation: [{name:"Concentrated Indian equities",value:80},{name:"Cash",value:20}],
    holdingPeriod: "5–20 years for cores", concentration: "Top holdings dominate",
    framework: { name: "Conviction Compounding", detail: "Bet big and sit tight when the setup is generational.",
      items: ["Growing India-tailwind sector","Management with skin in game","Runway of 10–20 years","Position sized to matter","Willingness to endure drawdowns"] },
    caseStudy: "Rakesh's Titan position (bought in the early 2000s) became a multi-bagger over two decades and epitomised his patient conviction with Indian consumer compounders.",
    quote: "Markets are like women — always commanding, mysterious, unpredictable.", quoteVerified: true,
    strength: "Conviction and India-story fluency",
    blindspot: "Concentration and personality-driven bets",
    bookSlugs: ["big-bull-essays","one-up"],
  }),
  mk({
    slug: "damani", name: "Radhakishan Damani", epithet: "The Value Ninja", country: "India", flag: "🇮🇳",
    era: "1990–present", eraStart: 1990, categories: ["Value","India"], primary: "India",
    cagr: "Built DMart (Avenue Supermarts) to multi-lakh-crore market cap", cagrNum: 25,
    bio: "Legendary trader-turned-value investor and founder of DMart; secretive, disciplined, deeply value-driven.",
    principles: [
      "Buy quality businesses at reasonable prices",
      "Long-term holds beat frequent trading",
      "Own the operating business when you can",
      "Under-promise, over-deliver",
      "Simplicity in strategy",
    ],
    avoids: ["Publicity","Leverage","Businesses he does not understand"],
    allocation: [{name:"Concentrated Indian equity",value:80},{name:"Cash",value:20}],
    holdingPeriod: "10+ years", concentration: "Highly concentrated",
    framework: { name: "Owner-Operator Value", detail: "Own great everyday businesses run by disciplined operators.",
      items: ["Steady cash generation","Low leverage","Owner-operator alignment","Sustainable unit economics","Fair valuation"] },
    caseStudy: "Damani built DMart into a high-quality, low-cost retailer whose IPO in 2017 made him one of India's richest men — value investing turned operator.",
    quote: "In the market, patience is priced.", quoteVerified: false,
    strength: "Value discipline & operator mindset",
    blindspot: "Very few observable public positions",
    bookSlugs: ["intelligent-investor","coffee-can"],
  }),
  mk({
    slug: "agrawal", name: "Raamdeo Agrawal", epithet: "The QGLP Evangelist", country: "India", flag: "🇮🇳",
    era: "1987–present (Motilal Oswal)", eraStart: 1980, categories: ["Growth","India"], primary: "India",
    cagr: "Motilal Oswal Wealth Study long-run growth CAGRs (illustrative)", cagrNum: 20,
    bio: "Co-founder of Motilal Oswal; popularised the QGLP framework and 'buy right, sit tight' investing in India.",
    principles: [
      "Quality of business first",
      "Growth of earnings second",
      "Longevity of both",
      "Reasonable price fourth",
      "Sit tight after buying right",
    ],
    avoids: ["Weak governance","Cyclical bets without runway","Fads"],
    allocation: [{name:"Quality growth equities",value:90},{name:"Cash",value:10}],
    holdingPeriod: "5–10 years+", concentration: "20–30 names",
    framework: { name: "QGLP", detail: "Quality × Growth × Longevity × Price scorecard.",
      items: ["ROCE ≥ 20%","Earnings growth ≥ 15%","Runway ≥ 10 years","P/E reasonable vs growth","Ethical management"] },
    caseStudy: "Motilal Oswal's Value Migration and Wealth Creation studies popularised QGLP through decades of case studies on Indian compounders like Bajaj Finance, Page Industries, Nestle India.",
    quote: "Buy right, sit tight.", quoteVerified: true,
    strength: "Codifying long-term Indian compounding",
    blindspot: "QGLP names get crowded and expensive",
    bookSlugs: ["coffee-can","common-stocks"],
  }),
  mk({
    slug: "ramesh-damani", name: "Ramesh Damani", epithet: "The Market Historian", country: "India", flag: "🇮🇳",
    era: "1988–present", eraStart: 1980, categories: ["Growth","India"], primary: "India",
    cagr: "Multi-decade equity growth (illustrative)", cagrNum: 20,
    bio: "BSE member and public equity investor; famous for calling long-term compounders early.",
    principles: [
      "India's macro tailwinds are decades long",
      "Bet on secular themes",
      "Do the fundamental work",
      "Study market history",
      "Concentrate when convinced",
    ],
    avoids: ["Frequent trading","IPO speculation","Ignoring history"],
    allocation: [{name:"Concentrated Indian equity",value:85},{name:"Cash",value:15}],
    holdingPeriod: "5–15 years", concentration: "Concentrated",
    framework: { name: "Secular Theme Bet", detail: "Anchor bets on India's structural growth themes.",
      items: ["Rising per-capita income","Formalisation","Digital adoption","Financialisation of savings","Domestic manufacturing"] },
    caseStudy: "Ramesh was an early advocate of Infosys and other Indian IT compounders — a bet on a secular theme that redefined Indian equity investing in the 1990s.",
    quote: "Bet on India — the longest compounding story of our times.", quoteVerified: false,
    strength: "Long-term theme identification",
    blindspot: "Themes can take a decade to play out",
    bookSlugs: ["one-up","coffee-can"],
  }),
  mk({
    slug: "kedia", name: "Vijay Kedia", epithet: "The SMILE Investor", country: "India", flag: "🇮🇳",
    era: "1989–present", eraStart: 1980, categories: ["Growth","India"], primary: "India",
    cagr: "Multi-bagger portfolio (illustrative, widely reported)", cagrNum: 25,
    bio: "Small/mid-cap specialist who codified the SMILE framework for early growth spotting.",
    principles: [
      "Small in size — early stage matters",
      "Medium in experience — track record exists",
      "Large in aspiration — leadership wants to scale",
      "Extra-large market potential — TAM must be huge",
      "Ride winners for years",
    ],
    avoids: ["Momentum without fundamentals","Weak governance micro-caps","Excessive diversification"],
    allocation: [{name:"Small & midcap growth",value:85},{name:"Cash",value:15}],
    holdingPeriod: "5–15 years", concentration: "10–15 names",
    framework: { name: "SMILE", detail: "Small size, Medium experience, Large aspiration, Extra-large market.",
      items: ["Small: micro/small-cap","Medium: 5–10 yr track","Large: ambitious mgmt","Extra-large: big TAM","Ride winners for years"] },
    caseStudy: "Kedia's bets on Cera Sanitaryware and Atul Auto in the 2000s exemplify the SMILE approach — small companies with big markets that compounded for a decade.",
    quote: "Bet on SMILE and let time do the work.", quoteVerified: false,
    strength: "Early growth identification",
    blindspot: "Small-cap illiquidity in downturns",
    bookSlugs: ["one-up","coffee-can"],
  }),
  mk({
    slug: "porinju", name: "Porinju Veliyath", epithet: "The Turnaround Hunter", country: "India", flag: "🇮🇳",
    era: "1990–present", eraStart: 1990, categories: ["Contrarian","India"], primary: "India",
    cagr: "Volatile smallcap returns (approx./widely discussed)", cagrNum: 15,
    bio: "Contrarian small/midcap investor known for turnaround and neglected-name bets.",
    principles: [
      "Neglected names offer the biggest rewards",
      "Buy when others give up",
      "Look for management change and capital reallocation",
      "Concentration matters in smallcaps",
      "Accept volatility as the price of admission",
    ],
    avoids: ["Consensus large-caps","Story-only names","Overpaying"],
    allocation: [{name:"Turnaround smallcaps",value:80},{name:"Cash",value:20}],
    holdingPeriod: "2–5 years", concentration: "Concentrated smallcap",
    framework: { name: "Turnaround Screen", detail: "Look for cheap smallcaps with a credible turnaround catalyst.",
      items: ["Recent management change","Improving margins","Debt reduction","Low P/B vs replacement","Insider buying"] },
    caseStudy: "Porinju's early public calls on names like Shreyas Shipping generated multi-baggers when the turnaround thesis played out — offset by sharp drawdowns when it didn't.",
    quote: "Where others see risk, we look for reward.", quoteVerified: false,
    strength: "Contrarian smallcap eye",
    blindspot: "Small-cap drawdowns can be brutal",
    bookSlugs: ["stock-market-genius"],
  }),
  mk({
    slug: "bakshi", name: "Sanjay Bakshi", epithet: "The Behavioural Value Investor", country: "India", flag: "🇮🇳",
    era: "1994–present", eraStart: 1990, categories: ["Value","Behavioral","India"], primary: "India",
    cagr: "Concentrated long-term equity (illustrative)", cagrNum: 15,
    bio: "Professor and value investor who fuses Graham, Munger and behavioural finance for Indian markets.",
    principles: [
      "Combine value with mental models",
      "Avoid unforced errors",
      "Read widely across disciplines",
      "Prefer 'inevitables' when reasonably priced",
      "Behaviour is the durable edge",
    ],
    avoids: ["Cyclical low-quality bets","Complex leverage","Fads"],
    allocation: [{name:"Concentrated quality",value:85},{name:"Cash",value:15}],
    holdingPeriod: "5–10 years", concentration: "10–15 names",
    framework: { name: "Behavioural Value Filter", detail: "Combine Graham numbers with Munger's mental models before buying.",
      items: ["Margin of safety","Quality of business","Behavioural moat","Latticework check","Position sized to conviction"] },
    caseStudy: "Bakshi's writings on Relaxo Footwear and Vaibhav Global illustrate how behavioural discipline plus quality-at-fair-price generated multi-year Indian compounders.",
    quote: "The key to investing is what you avoid, not what you do.", quoteVerified: false,
    strength: "Behavioural rigour + value discipline",
    blindspot: "Style out-of-favour in narrow bull markets",
    bookSlugs: ["poor-charlies-almanack","psychology-money","thinking-fast-slow"],
  }),
  mk({
    slug: "basant", name: "Basant Maheshwari", epithet: "The Art of Quality Growth", country: "India", flag: "🇮🇳",
    era: "1995–present", eraStart: 1990, categories: ["Growth","India"], primary: "India",
    cagr: "Long-term concentrated growth (illustrative)", cagrNum: 20,
    bio: "Founded EquityMaster forum culture; author of The Art of Stock Investing.",
    principles: [
      "Growth compounders create real wealth",
      "Concentrate in your best 5–10 names",
      "Sell only when the growth story breaks",
      "Sit tight through volatility",
      "Understand the business, not the ticker",
    ],
    avoids: ["Value traps","Cyclicals without runway","Frequent churn"],
    allocation: [{name:"Quality growth equities",value:90},{name:"Cash",value:10}],
    holdingPeriod: "3–7 years", concentration: "5–10 concentrated",
    framework: { name: "Quality-Growth Screen", detail: "Focus on companies with high ROCE and secular growth.",
      items: ["ROCE > 20%","Sales growth > 20% for 3+ years","Debt-light","Owner-operator","Wide moat"] },
    caseStudy: "Basant championed Page Industries in its early years as a classic Indian consumer growth compounder that rewarded patience with multi-baggers.",
    quote: "You get rich only by owning the very best businesses.", quoteVerified: false,
    strength: "Growth-quality bias",
    blindspot: "Concentration risk in growth downturns",
    bookSlugs: ["coffee-can","common-stocks"],
  }),
  mk({
    slug: "kacholia", name: "Ashish Kacholia", epithet: "The Small-Cap Whisperer", country: "India", flag: "🇮🇳",
    era: "2003–present", eraStart: 2000, categories: ["Growth","India"], primary: "India",
    cagr: "Multi-bagger smallcaps (illustrative)", cagrNum: 25,
    bio: "Ex-Enam; now among India's most-tracked small/microcap investors.",
    principles: [
      "Own emerging leaders early",
      "Meet management before buying",
      "Concentrate in convictions",
      "Ride winners for years",
      "Ignore short-term noise",
    ],
    avoids: ["Governance red flags","Illiquid microcaps without cash","Consensus names"],
    allocation: [{name:"Smallcap growth",value:85},{name:"Cash",value:15}],
    holdingPeriod: "3–7 years", concentration: "20–30 names publicly disclosed",
    framework: { name: "Emerging Leader Screen", detail: "Look for niche category leaders early in their scale-up.",
      items: ["Niche leadership","Sales momentum","Improving margins","Clean audit","Founder skin in game"] },
    caseStudy: "Kacholia's early positions in names like Safari Industries and Xpro India illustrate the emerging-leader smallcap approach — held through several drawdowns for multi-year returns.",
    quote: "Emerging leaders create the biggest wealth.", quoteVerified: false,
    strength: "Deep smallcap network & research",
    blindspot: "Smallcap liquidity risk",
    bookSlugs: ["one-up"],
  }),
  mk({
    slug: "dolly", name: "Dolly Khanna", epithet: "The Quiet Compounder", country: "India", flag: "🇮🇳",
    era: "1996–present", eraStart: 1990, categories: ["Value","India"], primary: "India",
    cagr: "Multi-bagger smallcap portfolio (illustrative)", cagrNum: 20,
    bio: "Low-profile Chennai-based investor famous for spotting deep-value smallcaps in overlooked sectors.",
    principles: [
      "Look where analysts don't",
      "Buy cheap, boring, cash-flowing businesses",
      "Concentrate quietly, no fanfare",
      "Ride until valuations catch up",
      "Live within reach of the businesses you own",
    ],
    avoids: ["Consensus names","Momentum","Publicity"],
    allocation: [{name:"Deep-value smallcaps",value:85},{name:"Cash",value:15}],
    holdingPeriod: "3–7 years", concentration: "Concentrated in a few boring names",
    framework: { name: "Boring & Cheap", detail: "Buy overlooked businesses at low multiples with real cash flows.",
      items: ["Low P/E vs peers","Positive FCF","Clean promoter","Sector under-covered","Reasonable debt"] },
    caseStudy: "Dolly's positions in names like Nitin Spinners and Rain Industries at deep-value points delivered multi-baggers as cycles turned.",
    quote: "The best deals are boring.", quoteVerified: false,
    strength: "Off-consensus deep value",
    blindspot: "Cyclical smallcaps carry cycle risk",
    bookSlugs: ["intelligent-investor"],
  }),
  mk({
    slug: "nemish", name: "Nemish Shah", epithet: "The Patient Concentrator", country: "India", flag: "🇮🇳",
    era: "1984–present (Enam)", eraStart: 1980, categories: ["Value","Growth","India"], primary: "India",
    cagr: "Enam long-term compounding (illustrative)", cagrNum: 20,
    bio: "Enam co-founder; runs highly concentrated, long-hold portfolios with patience through cycles.",
    principles: [
      "Concentration in high-conviction names",
      "Multi-decade holding periods",
      "Own businesses, not tickers",
      "Ignore benchmarks",
      "Wait years for the right pitch",
    ],
    avoids: ["Frequent trading","Style-drift","Chasing themes"],
    allocation: [{name:"Concentrated Indian quality",value:85},{name:"Cash",value:15}],
    holdingPeriod: "10+ years", concentration: "Very concentrated",
    framework: { name: "Fat-Pitch Discipline", detail: "Do very little; act big when it counts.",
      items: ["Wait for obvious mispricing","Prefer great business economics","Long runway","Owner-operator alignment","Position sized to matter"] },
    caseStudy: "Nemish's long-term bets on names like Asian Paints and Bajaj Auto illustrate the patience-and-concentration playbook that defined Enam's institutional approach.",
    quote: "Do less. Own better. Wait longer.", quoteVerified: false,
    strength: "Institutional patience",
    blindspot: "Low turnover means missed cycles",
    bookSlugs: ["essays-buffett","coffee-can"],
  }),
  mk({
    slug: "akash", name: "Akash Bhanshali", epithet: "The Value Craftsman", country: "India", flag: "🇮🇳",
    era: "1990–present", eraStart: 1990, categories: ["Value","India"], primary: "India",
    cagr: "Concentrated value long-term (illustrative)", cagrNum: 18,
    bio: "Low-profile Mumbai investor with concentrated long-term value bets in Indian equities.",
    principles: [
      "Buy quality when out of favour",
      "Hold through cycles",
      "Concentrate in best ideas",
      "Sit with cash when nothing is cheap",
      "Never lose money is rule 1",
    ],
    avoids: ["Overpaying","Momentum names","Publicity"],
    allocation: [{name:"Concentrated value",value:80},{name:"Cash",value:20}],
    holdingPeriod: "5–10 years", concentration: "Concentrated",
    framework: { name: "Cycle-Aware Value", detail: "Buy value when cycles turn against a good business.",
      items: ["Down-cycle sector","Balance-sheet strength","Management resilience","Sensible valuation","Long horizon"] },
    caseStudy: "Bhanshali's concentrated bets across Indian value cycles illustrate that patient contrarianism, done quietly, still works in Indian equities.",
    quote: "Great returns come from doing less, well.", quoteVerified: false,
    strength: "Cycle patience",
    blindspot: "Underperformance during long momentum runs",
    bookSlugs: ["intelligent-investor","coffee-can"],
  }),
  mk({
    slug: "bikhchandani", name: "Sanjeev Bikhchandani", epithet: "The Operator-Investor", country: "India", flag: "🇮🇳",
    era: "1990s–present (Info Edge)", eraStart: 1990, categories: ["Growth","India"], primary: "India",
    cagr: "Info Edge + Zomato/Policybazaar early-stage bets (illustrative)", cagrNum: 25,
    bio: "Founder of Info Edge (naukri.com); one of India's best operator-investors, backing Zomato and Policybazaar early.",
    principles: [
      "Back founders early",
      "Own the digital rails of India's formalisation",
      "Reinvest cash into optionality",
      "Long-term thinking beats quarter-to-quarter",
      "Operator empathy is the edge",
    ],
    avoids: ["Consumer-adjacent fads","Empire-building without unit economics"],
    allocation: [{name:"Core operating business",value:60},{name:"Early-stage tech bets",value:30},{name:"Cash",value:10}],
    holdingPeriod: "5–15 years", concentration: "Concentrated in the digital consumer stack",
    framework: { name: "Digital-Rails Bet", detail: "Own platforms that will formalise Indian consumer life.",
      items: ["Two-sided platform economics","Long payback horizon","Network effects","Founder alignment","Capital efficiency at scale"] },
    caseStudy: "Info Edge invested in Zomato at seed stage and reaped billion-dollar returns at IPO — a textbook operator-investor bet on India's digital consumer economy.",
    quote: "Bet on founders and let compounding work.", quoteVerified: false,
    strength: "Operator empathy",
    blindspot: "Early-stage bets are illiquid and long-dated",
    bookSlugs: ["outsiders"],
  }),
  mk({
    slug: "madhu-kela", name: "Madhusudan Kela", epithet: "The Macro-Aware Growth Investor", country: "India", flag: "🇮🇳",
    era: "1993–present", eraStart: 1990, categories: ["Growth","Macro","India"], primary: "India",
    cagr: "Multi-cycle Indian equity growth (illustrative)", cagrNum: 20,
    bio: "Veteran market voice who combines macro reads with growth investing.",
    principles: [
      "Ride India's macro cycles with growth names",
      "Balance thematic bets with quality",
      "Concentrate in convictions",
      "Respect valuation extremes",
      "Sit tight through corrections",
    ],
    avoids: ["Style-drift","Momentum chasing","Ignoring valuation"],
    allocation: [{name:"Growth equities",value:75},{name:"Cyclicals",value:15},{name:"Cash",value:10}],
    holdingPeriod: "3–7 years", concentration: "Concentrated in themes",
    framework: { name: "Macro + Growth Overlay", detail: "Combine macro read with quality-growth stock picking.",
      items: ["India macro tailwind","Sector benefiting","Company with pricing power","Valuation vs growth","Position size vs conviction"] },
    caseStudy: "Madhusudan's early advocacy of Indian infrastructure and financials during the 2003–07 cycle illustrates how macro-aware growth investing can compound Indian returns.",
    quote: "Ride India, but respect valuations.", quoteVerified: false,
    strength: "Macro fluency + growth pick",
    blindspot: "Macro calls are hard even for pros",
    bookSlugs: ["principles","one-up"],
  }),
  mk({
    slug: "shankar", name: "Shankar Sharma", epithet: "The Contrarian Trader-Investor", country: "India", flag: "🇮🇳",
    era: "1990–present", eraStart: 1990, categories: ["Contrarian","Macro","India"], primary: "India",
    cagr: "Multi-cycle Indian and global equity (illustrative)", cagrNum: 15,
    bio: "Founder of First Global; blends contrarian macro views with trader instinct.",
    principles: [
      "Question consensus loudly",
      "Blend macro and micro",
      "Smallcaps outperform over long horizons",
      "Manage risk actively",
      "Global diversification matters",
    ],
    avoids: ["Home-country bias","Herding","Complacency in bull markets"],
    allocation: [{name:"Global equities",value:50},{name:"Indian smallcaps",value:35},{name:"Cash",value:15}],
    holdingPeriod: "1–5 years", concentration: "Diversified globally",
    framework: { name: "Contrarian Macro-Micro", detail: "Marry a non-consensus macro read with bottom-up smallcap picks.",
      items: ["Macro divergence identified","Sector benefiting","Smallcap winners inside","Risk sized carefully","Willingness to be early"] },
    caseStudy: "Sharma has publicly championed Indian smallcaps and global diversification through multiple cycles, sometimes controversially, but consistently arguing against home-country bias.",
    quote: "Consensus is comfort. Comfort is expensive.", quoteVerified: false,
    strength: "Independent macro view",
    blindspot: "Contrarian bets can be early for years",
    bookSlugs: ["market-wizards","principles"],
  }),
  mk({
    slug: "parikh", name: "Parag Parikh", epithet: "The Behavioural Pioneer (India)", country: "India", flag: "🇮🇳",
    era: "1983–2015", eraStart: 1980, categories: ["Value","Behavioral","India"], primary: "India",
    cagr: "PPFAS Flexi-Cap long-run growth (illustrative)", cagrNum: 15,
    bio: "Founder of PPFAS; brought behavioural finance discipline to Indian investors.",
    principles: [
      "Behaviour is the biggest edge",
      "Global diversification for Indian portfolios",
      "Skin-in-the-game aligned management",
      "Patience, patience, patience",
      "Own the fund like your own money",
    ],
    avoids: ["Home-country bias","Style-drift","Frequent churn"],
    allocation: [{name:"Indian equities",value:65},{name:"Global equities",value:30},{name:"Cash",value:5}],
    holdingPeriod: "5–10 years", concentration: "Diversified global-plus-India",
    framework: { name: "Behavioural Value", detail: "Blend value, behaviour and global diversification.",
      items: ["Margin of safety","Global diversification","Skin-in-the-game manager","Long horizon","Behavioural checklist"] },
    caseStudy: "PPFAS Flexi-Cap's structural allocation to global businesses gave Indian retail investors exposure to Alphabet and Meta long before it was mainstream — a behavioural + diversification win.",
    quote: "Behaviour matters more than intelligence.", quoteVerified: true,
    strength: "Behavioural rigour",
    blindspot: "Global bets add FX volatility",
    bookSlugs: ["stocks-to-riches","psychology-money"],
  }),
  mk({
    slug: "naren", name: "S. Naren", epithet: "The Contrarian Countercyclicalist", country: "India", flag: "🇮🇳",
    era: "1989–present (ICICI Pru MF)", eraStart: 1980, categories: ["Value","Contrarian","India"], primary: "India",
    cagr: "ICICI Pru Value/Balanced Advantage long-run (illustrative)", cagrNum: 15,
    bio: "CIO at ICICI Prudential MF; ran the Value Discovery Fund with a contrarian, counter-cyclical bias.",
    principles: [
      "Sell what's expensive; buy what's cheap",
      "Cycle-aware allocation between equity and debt",
      "Ignore short-term relative performance",
      "Value works if you can wait",
      "Sizing matters as much as picking",
    ],
    avoids: ["Chasing momentum","Style-drift","Ignoring cycle signals"],
    allocation: [{name:"Value equities",value:60},{name:"Debt / cash",value:30},{name:"Global",value:10}],
    holdingPeriod: "3–5 years", concentration: "Diversified value tilt",
    framework: { name: "Counter-Cyclical Allocation", detail: "Rotate between equity and debt based on valuation extremes.",
      items: ["Nifty PE vs 5-yr avg","Earnings yield vs bond yield","Sector valuation gaps","Sentiment extremes","Rebalance rules-based"] },
    caseStudy: "Naren's early call to overweight PSU and value stocks in the 2020 low was contrarian at the time but rewarded investors over the subsequent value cycle.",
    quote: "Sell what's expensive. Buy what's cheap.", quoteVerified: true,
    strength: "Cycle awareness + discipline",
    blindspot: "Value can underperform for long stretches",
    bookSlugs: ["most-important-thing","intelligent-investor"],
  }),
  mk({
    slug: "prashant-jain", name: "Prashant Jain", epithet: "The Compounder CIO", country: "India", flag: "🇮🇳",
    era: "1991–present (ex-HDFC MF)", eraStart: 1990, categories: ["Value","Growth","India"], primary: "India",
    cagr: "HDFC Equity/Balanced Fund long-run ~18–20% CAGR (approx.)", cagrNum: 18,
    bio: "Longest-serving Indian equity fund manager; ran HDFC Equity Fund for 20+ years with quality-value discipline.",
    principles: [
      "Buy and hold quality compounders",
      "Cyclicals only at valuation extremes",
      "Sector tilts, not stock churn",
      "Simplicity beats complexity",
      "Trust earnings over narratives",
    ],
    avoids: ["Consensus expensive names","Style-drift","Overtrading"],
    allocation: [{name:"Quality large-caps",value:65},{name:"Selective cyclicals",value:25},{name:"Cash",value:10}],
    holdingPeriod: "5–10 years+", concentration: "Diversified quality",
    framework: { name: "Quality-at-Reasonable-Price", detail: "Own great franchises when priced sensibly and stay put.",
      items: ["ROE > 15%","Debt-light","Sector tailwind","Sensible valuation","Long horizon"] },
    caseStudy: "Prashant Jain's steady overweight to Indian financials and quality large-caps through the 2000s and 2010s produced one of India's best long-run mutual-fund track records.",
    quote: "Time in the market matters more than timing it.", quoteVerified: false,
    strength: "Discipline over decades",
    blindspot: "Slow to rotate out of laggards",
    bookSlugs: ["coffee-can","essays-buffett"],
  }),
  mk({
    slug: "mukherjea", name: "Saurabh Mukherjea", epithet: "The Consistent Compounders", country: "India", flag: "🇮🇳",
    era: "2003–present (Marcellus)", eraStart: 2000, categories: ["Value","Growth","India"], primary: "India",
    cagr: "Marcellus Consistent Compounders (illustrative)", cagrNum: 17,
    bio: "Founder of Marcellus; popularised the Consistent Compounders framework and clean-accounting scoring.",
    principles: [
      "Clean accounting is non-negotiable",
      "High and stable ROCE",
      "Long runway, category leadership",
      "Concentrate in top compounders",
      "Ignore short-term noise",
    ],
    avoids: ["Weak accounting","Cyclicals","Momentum names"],
    allocation: [{name:"Consistent compounders",value:90},{name:"Cash",value:10}],
    holdingPeriod: "5–10 years+", concentration: "10–15 names",
    framework: { name: "Coffee Can Filter", detail: "Only own companies with 10 years of ≥10% revenue growth and ≥15% ROCE.",
      items: ["10-yr revenue growth ≥ 10% every year","ROCE ≥ 15% every year","Clean audit","Strong FCF","Owner-operator or professional excellence"] },
    caseStudy: "Marcellus's Coffee Can portfolios have publicly showcased names like Asian Paints, Pidilite and HDFC Bank as the archetypal Indian consistent compounders.",
    quote: "Own great businesses. Do nothing.", quoteVerified: false,
    strength: "Systematic quality filter",
    blindspot: "Quality names get expensive and crowd trade",
    bookSlugs: ["coffee-can","unusual-billionaires","essays-buffett"],
  }),
  mk({
    slug: "kenneth-andrade", name: "Kenneth Andrade", epithet: "The Cycle Investor", country: "India", flag: "🇮🇳",
    era: "2000–present", eraStart: 2000, categories: ["Value","Growth","India"], primary: "India",
    cagr: "Long-run Indian equity (illustrative)", cagrNum: 15,
    bio: "Founder of Old Bridge Capital; former CIO of IDFC MF; known for business-cycle-aware value investing.",
    principles: [
      "Understand where the sector cycle stands",
      "Own leaders emerging from a down cycle",
      "Balance sheet quality is the moat",
      "Reinvestment discipline matters",
      "Ride winners through the up-cycle",
    ],
    avoids: ["Chasing peak-cycle winners","Weak balance sheets","Story stocks"],
    allocation: [{name:"Cyclical sector leaders",value:70},{name:"Cash",value:30}],
    holdingPeriod: "3–7 years", concentration: "Concentrated in cycle winners",
    framework: { name: "Sector-Cycle Positioning", detail: "Position portfolios by the phase of each sector cycle.",
      items: ["Down cycle: accumulate leaders","Recovery: overweight winners","Expansion: ride","Peak: reduce","Downturn: rotate to cash"] },
    caseStudy: "Andrade's early call on Indian capital-goods and materials during the 2020 cycle-turn is a textbook cycle-aware value bet that rewarded patience.",
    quote: "Cycles pay you if you respect them.", quoteVerified: false,
    strength: "Business-cycle fluency",
    blindspot: "Timing cycles is inherently hard",
    bookSlugs: ["most-important-thing","principles"],
  }),
];

export const INVESTORS_BY_SLUG: Record<string, Investor> = Object.fromEntries(
  INVESTORS.map((i) => [i.slug, i]),
);
