export const HERO_QUOTES: Array<{ text: string; author: string; verified: boolean }> = [
  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett", verified: true },
  { text: "The big money is not in the buying and selling, but in the waiting.", author: "Charlie Munger", verified: true },
  { text: "In the short run the market is a voting machine, in the long run a weighing machine.", author: "Benjamin Graham", verified: true },
  { text: "Know what you own, and know why you own it.", author: "Peter Lynch", verified: true },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett", verified: true },
  { text: "The four most dangerous words: this time it's different.", author: "John Templeton", verified: true },
  { text: "It's not whether you're right or wrong, but how much when right and wrong.", author: "George Soros", verified: true },
  { text: "The intelligent investor is a realist who sells to optimists and buys from pessimists.", author: "Benjamin Graham", verified: true },
  { text: "Diversification is protection against ignorance.", author: "Warren Buffett", verified: true },
  { text: "Being right is not enough. You have to be right and non-consensus.", author: "Howard Marks", verified: false },
  { text: "The market can stay irrational longer than you can stay solvent.", author: "attributed to Keynes / Druckenmiller lore", verified: false },
  { text: "Buy right, sit tight.", author: "Raamdeo Agrawal", verified: true },
  { text: "Bull markets are born on pessimism.", author: "John Templeton", verified: true },
  { text: "Time in the market beats timing the market.", author: "widely attributed", verified: false },
  { text: "Compound interest is the eighth wonder of the world.", author: "attributed to Einstein", verified: false },
  { text: "Invest for the long haul. Don't get too greedy, don't get too scared.", author: "Shelby Davis (attributed)", verified: false },
  { text: "Behaviour is more important than intelligence in investing.", author: "Morgan Housel", verified: true },
  { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett", verified: true },
  { text: "Cash combined with courage in a crisis is priceless.", author: "Warren Buffett", verified: true },
  { text: "Never test the depth of the river with both feet.", author: "Warren Buffett (attributed)", verified: false },
];
