import type { NewsItem } from "@/lib/news.functions";
import type { YahooEvent } from "@/lib/yahoo.functions";
export type CatalystType="earnings"|"ex-dividend"|"corporate action"|"index rebalance";
export interface Catalyst { id:string; type:CatalystType; title:string; date:string; source:string; url?:string; bias:"Positive"|"Negative"|"Neutral / unknown"; magnitudePct:number|null; magnitudeSource:string; impact:number }
const DATE_PATTERNS=[/\b(20\d{2})-(\d{1,2})-(\d{1,2})\b/,/\b(\d{1,2})[\/-](\d{1,2})[\/-](20\d{2})\b/,/\b(\d{1,2})\s+(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+(20\d{2})\b/i];
function explicitDate(text:string){for(const r of DATE_PATTERNS){const m=text.match(r);if(!m)continue;let d:Date;if(/[A-Za-z]/.test(m[0]))d=new Date(`${m[1]} ${m[2]} ${m[3]} UTC`);else if(m[1].length===4)d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));else d=new Date(Date.UTC(+m[3],+m[2]-1,+m[1]));if(!isNaN(d.getTime()))return d.toISOString().slice(0,10);}return null;}
function classify(text:string):CatalystType|null{const t=text.toLowerCase();if(/earnings|results|quarterly result/.test(t))return"earnings";if(/ex[- ]dividend/.test(t))return"ex-dividend";if(/split|bonus|buyback|rights issue|merger|demerger/.test(t))return"corporate action";if(/index rebalance|reconstitution/.test(t))return"index rebalance";return null;}
export function buildCatalysts(args:{events:YahooEvent[];news:NewsItem[];symbol:string;name:string;endDate:string}){const today=new Date().toISOString().slice(0,10);const out:Catalyst[]=[];for(const e of args.events){if(e.date<today||e.date>args.endDate)continue;out.push({id:`y-${e.type}-${e.date}`,type:e.type,title:e.title,date:e.date,source:"Yahoo Finance calendar",bias:"Neutral / unknown",magnitudePct:null,magnitudeSource:"Magnitude unknown — no matching event history available",impact:0});}
 const terms=[args.symbol.replace(/\.NS$|\.BO$/,''),...args.name.split(/\s+/).filter(x=>x.length>4).slice(0,2)].map(x=>x.toLowerCase()); for(const n of args.news){const text=`${n.title} ${n.description}`;if(!terms.some(t=>text.toLowerCase().includes(t)))continue;const type=classify(text),date=explicitDate(text);if(!type||!date||date<today||date>args.endDate)continue;out.push({id:n.id,type,title:n.title,date,source:n.source,url:n.url,bias:"Neutral / unknown",magnitudePct:null,magnitudeSource:"Magnitude unknown — article states a date but not an evidenced move",impact:0});}
 return out.filter((v,i,a)=>a.findIndex(x=>x.type===v.type&&x.date===v.date)===i).sort((a,b)=>b.impact-a.impact||a.date.localeCompare(b.date));}
