import type { LayerKey, LayerResult } from "./ensemble";
import type { OHLCV } from "./engine12";
export const TRACK_KEY="dx_quant_forecast_log_v1"; const MIN_SAMPLE=5;
export interface ForecastRecord {id:string;ticker:string;sector:string;horizon:string;modelKey:string;createdAt:string;maturityDate:string;startPrice:number;layers:Array<Pick<LayerResult,"key"|"target"|"call">>;ensembleTarget:number;ensembleCall:"UP"|"FLAT"|"DOWN";weightSource:string;resolvedAt?:string;actualPrice?:number;results?:Partial<Record<LayerKey|"ensemble",{correct:boolean;errorPct:number}>>}
const read=():ForecastRecord[]=>{try{const v=JSON.parse(localStorage.getItem(TRACK_KEY)??"[]");return Array.isArray(v)?v:[];}catch{return[];}}; const write=(v:ForecastRecord[])=>{try{localStorage.setItem(TRACK_KEY,JSON.stringify(v.slice(-300)));}catch{}};
const call=(target:number,start:number):"UP"|"FLAT"|"DOWN"=>target>start*1.01?"UP":target<start*.99?"DOWN":"FLAT"; const actualCall=call;
export function logForecast(input:Omit<ForecastRecord,"id"|"createdAt"|"ensembleCall">){if(typeof localStorage==="undefined")return read();const id=[input.ticker,input.horizon,input.modelKey,input.maturityDate].join("|");const all=read();if(!all.some(r=>r.id===id)){all.push({...input,id,createdAt:new Date().toISOString(),ensembleCall:call(input.ensembleTarget,input.startPrice)});write(all);}return all;}
export function resolveForecasts(ticker:string,bars:OHLCV[]){if(typeof localStorage==="undefined")return[];const all=read(), today=bars.at(-1)?.date??"";let changed=false;for(const r of all){if(r.ticker!==ticker||r.resolvedAt||r.maturityDate>today)continue;const bar=bars.find(b=>b.date>=r.maturityDate);if(!bar)continue;const ac=actualCall(bar.close,r.startPrice);const results:ForecastRecord["results"]={};for(const l of r.layers)if(l.target!=null&&l.call)results[l.key]={correct:l.call===ac,errorPct:Math.abs(l.target-bar.close)/bar.close*100};results.ensemble={correct:r.ensembleCall===ac,errorPct:Math.abs(r.ensembleTarget-bar.close)/bar.close*100};r.actualPrice=bar.close;r.resolvedAt=bar.date;r.results=results;changed=true;}if(changed)write(all);return all.filter(r=>r.ticker===ticker);}
export function trackStats(records:ForecastRecord[]){const resolved=records.filter(r=>r.results);const keys:Array<LayerKey|"ensemble">=["technical","statistical","valuation","ensemble"];const stats=Object.fromEntries(keys.map(k=>{const rows=resolved.flatMap(r=>r.results?.[k]?[r.results[k]]:[]);return[k,{n:rows.length,hitRate:rows.length?rows.filter(x=>x.correct).length/rows.length*100:null,error:rows.length?rows.reduce((s,x)=>s+x.errorPct,0)/rows.length:null}]})) as Record<LayerKey|"ensemble",{n:number;hitRate:number|null;error:number|null}>;return{resolved,stats,ready:stats.ensemble.n>=MIN_SAMPLE};}
export function deriveWeights(tickerRecords:ForecastRecord[],sectorRecords:ForecastRecord[]){for(const [rows,label,min] of [[tickerRecords,"Ticker track record",MIN_SAMPLE],[sectorRecords,"Sector track record",8]] as const){const s=trackStats(rows).stats;const keys:LayerKey[]=["technical","statistical","valuation"];if(keys.every(k=>s[k].n>=min&&s[k].hitRate!=null)){const scores=Object.fromEntries(keys.map(k=>[k,Math.max(1,(s[k].hitRate??50)+5)])) as Record<LayerKey,number>;return{weights:scores,source:`${label} · smoothed hit rates`};}}return{source:"Equal weights — track record building"};}
export function allRecords(){return typeof localStorage==="undefined"?[]:read();}
